// Code generated by Kitex v0.16.1. DO NOT EDIT.

package chatservice

import (
	"context"
	"errors"
	chat "example.com/aim/chat-service/kitex_gen/chat"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newChatServiceHealthArgs,
		newChatServiceHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateGroup": kitex.NewMethodInfo(
		createGroupHandler,
		newChatServiceCreateGroupArgs,
		newChatServiceCreateGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateSingleConversation": kitex.NewMethodInfo(
		createSingleConversationHandler,
		newChatServiceCreateSingleConversationArgs,
		newChatServiceCreateSingleConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversations": kitex.NewMethodInfo(
		listConversationsHandler,
		newChatServiceListConversationsArgs,
		newChatServiceListConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"JoinGroup": kitex.NewMethodInfo(
		joinGroupHandler,
		newChatServiceJoinGroupArgs,
		newChatServiceJoinGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"InviteMember": kitex.NewMethodInfo(
		inviteMemberHandler,
		newChatServiceInviteMemberArgs,
		newChatServiceInviteMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LeaveGroup": kitex.NewMethodInfo(
		leaveGroupHandler,
		newChatServiceLeaveGroupArgs,
		newChatServiceLeaveGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListMembers": kitex.NewMethodInfo(
		listMembersHandler,
		newChatServiceListMembersArgs,
		newChatServiceListMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListMessages": kitex.NewMethodInfo(
		listMessagesHandler,
		newChatServiceListMessagesArgs,
		newChatServiceListMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListBots": kitex.NewMethodInfo(
		listBotsHandler,
		newChatServiceListBotsArgs,
		newChatServiceListBotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversationBots": kitex.NewMethodInfo(
		listConversationBotsHandler,
		newChatServiceListConversationBotsArgs,
		newChatServiceListConversationBotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddConversationBot": kitex.NewMethodInfo(
		addConversationBotHandler,
		newChatServiceAddConversationBotArgs,
		newChatServiceAddConversationBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveConversationBot": kitex.NewMethodInfo(
		removeConversationBotHandler,
		newChatServiceRemoveConversationBotArgs,
		newChatServiceRemoveConversationBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAICallLogs": kitex.NewMethodInfo(
		listAICallLogsHandler,
		newChatServiceListAICallLogsArgs,
		newChatServiceListAICallLogsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateMessage": kitex.NewMethodInfo(
		createMessageHandler,
		newChatServiceCreateMessageArgs,
		newChatServiceCreateMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FindSingleByUsers": kitex.NewMethodInfo(
		findSingleByUsersHandler,
		newChatServiceFindSingleByUsersArgs,
		newChatServiceFindSingleByUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	chatServiceServiceInfo                = NewServiceInfo()
	chatServiceServiceInfoForClient       = NewServiceInfoForClient()
	chatServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return chatServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ChatService"
	handlerType := (*chat.ChatService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "chat",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceHealthArgs)
	realResult := result.(*chat.ChatServiceHealthResult)
	success, err := handler.(chat.ChatService).Health(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceHealthArgs() interface{} {
	return chat.NewChatServiceHealthArgs()
}

func newChatServiceHealthResult() interface{} {
	return chat.NewChatServiceHealthResult()
}

func createGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateGroupArgs)
	realResult := result.(*chat.ChatServiceCreateGroupResult)
	success, err := handler.(chat.ChatService).CreateGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateGroupArgs() interface{} {
	return chat.NewChatServiceCreateGroupArgs()
}

func newChatServiceCreateGroupResult() interface{} {
	return chat.NewChatServiceCreateGroupResult()
}

func createSingleConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateSingleConversationArgs)
	realResult := result.(*chat.ChatServiceCreateSingleConversationResult)
	success, err := handler.(chat.ChatService).CreateSingleConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateSingleConversationArgs() interface{} {
	return chat.NewChatServiceCreateSingleConversationArgs()
}

func newChatServiceCreateSingleConversationResult() interface{} {
	return chat.NewChatServiceCreateSingleConversationResult()
}

func listConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListConversationsArgs)
	realResult := result.(*chat.ChatServiceListConversationsResult)
	success, err := handler.(chat.ChatService).ListConversations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListConversationsArgs() interface{} {
	return chat.NewChatServiceListConversationsArgs()
}

func newChatServiceListConversationsResult() interface{} {
	return chat.NewChatServiceListConversationsResult()
}

func joinGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceJoinGroupArgs)
	realResult := result.(*chat.ChatServiceJoinGroupResult)
	success, err := handler.(chat.ChatService).JoinGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceJoinGroupArgs() interface{} {
	return chat.NewChatServiceJoinGroupArgs()
}

func newChatServiceJoinGroupResult() interface{} {
	return chat.NewChatServiceJoinGroupResult()
}

func inviteMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceInviteMemberArgs)
	realResult := result.(*chat.ChatServiceInviteMemberResult)
	success, err := handler.(chat.ChatService).InviteMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceInviteMemberArgs() interface{} {
	return chat.NewChatServiceInviteMemberArgs()
}

func newChatServiceInviteMemberResult() interface{} {
	return chat.NewChatServiceInviteMemberResult()
}

func leaveGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceLeaveGroupArgs)
	realResult := result.(*chat.ChatServiceLeaveGroupResult)
	success, err := handler.(chat.ChatService).LeaveGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceLeaveGroupArgs() interface{} {
	return chat.NewChatServiceLeaveGroupArgs()
}

func newChatServiceLeaveGroupResult() interface{} {
	return chat.NewChatServiceLeaveGroupResult()
}

func listMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListMembersArgs)
	realResult := result.(*chat.ChatServiceListMembersResult)
	success, err := handler.(chat.ChatService).ListMembers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListMembersArgs() interface{} {
	return chat.NewChatServiceListMembersArgs()
}

func newChatServiceListMembersResult() interface{} {
	return chat.NewChatServiceListMembersResult()
}

func listMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListMessagesArgs)
	realResult := result.(*chat.ChatServiceListMessagesResult)
	success, err := handler.(chat.ChatService).ListMessages(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListMessagesArgs() interface{} {
	return chat.NewChatServiceListMessagesArgs()
}

func newChatServiceListMessagesResult() interface{} {
	return chat.NewChatServiceListMessagesResult()
}

func listBotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListBotsArgs)
	realResult := result.(*chat.ChatServiceListBotsResult)
	success, err := handler.(chat.ChatService).ListBots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListBotsArgs() interface{} {
	return chat.NewChatServiceListBotsArgs()
}

func newChatServiceListBotsResult() interface{} {
	return chat.NewChatServiceListBotsResult()
}

func listConversationBotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListConversationBotsArgs)
	realResult := result.(*chat.ChatServiceListConversationBotsResult)
	success, err := handler.(chat.ChatService).ListConversationBots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListConversationBotsArgs() interface{} {
	return chat.NewChatServiceListConversationBotsArgs()
}

func newChatServiceListConversationBotsResult() interface{} {
	return chat.NewChatServiceListConversationBotsResult()
}

func addConversationBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceAddConversationBotArgs)
	realResult := result.(*chat.ChatServiceAddConversationBotResult)
	success, err := handler.(chat.ChatService).AddConversationBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceAddConversationBotArgs() interface{} {
	return chat.NewChatServiceAddConversationBotArgs()
}

func newChatServiceAddConversationBotResult() interface{} {
	return chat.NewChatServiceAddConversationBotResult()
}

func removeConversationBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceRemoveConversationBotArgs)
	realResult := result.(*chat.ChatServiceRemoveConversationBotResult)
	success, err := handler.(chat.ChatService).RemoveConversationBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceRemoveConversationBotArgs() interface{} {
	return chat.NewChatServiceRemoveConversationBotArgs()
}

func newChatServiceRemoveConversationBotResult() interface{} {
	return chat.NewChatServiceRemoveConversationBotResult()
}

func listAICallLogsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListAICallLogsArgs)
	realResult := result.(*chat.ChatServiceListAICallLogsResult)
	success, err := handler.(chat.ChatService).ListAICallLogs(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListAICallLogsArgs() interface{} {
	return chat.NewChatServiceListAICallLogsArgs()
}

func newChatServiceListAICallLogsResult() interface{} {
	return chat.NewChatServiceListAICallLogsResult()
}

func createMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateMessageArgs)
	realResult := result.(*chat.ChatServiceCreateMessageResult)
	success, err := handler.(chat.ChatService).CreateMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateMessageArgs() interface{} {
	return chat.NewChatServiceCreateMessageArgs()
}

func newChatServiceCreateMessageResult() interface{} {
	return chat.NewChatServiceCreateMessageResult()
}

func findSingleByUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceFindSingleByUsersArgs)
	realResult := result.(*chat.ChatServiceFindSingleByUsersResult)
	success, err := handler.(chat.ChatService).FindSingleByUsers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newChatServiceFindSingleByUsersArgs() interface{} {
	return chat.NewChatServiceFindSingleByUsersArgs()
}

func newChatServiceFindSingleByUsersResult() interface{} {
	return chat.NewChatServiceFindSingleByUsersResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Health(ctx context.Context, req *chat.HealthRequest) (r *chat.HealthResponse, err error) {
	var _args chat.ChatServiceHealthArgs
	_args.Req = req
	var _result chat.ChatServiceHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateGroup(ctx context.Context, req *chat.CreateGroupRequest) (r *chat.CreateGroupResponse, err error) {
	var _args chat.ChatServiceCreateGroupArgs
	_args.Req = req
	var _result chat.ChatServiceCreateGroupResult
	if err = p.c.Call(ctx, "CreateGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateSingleConversation(ctx context.Context, req *chat.CreateSingleConversationRequest) (r *chat.CreateSingleConversationResponse, err error) {
	var _args chat.ChatServiceCreateSingleConversationArgs
	_args.Req = req
	var _result chat.ChatServiceCreateSingleConversationResult
	if err = p.c.Call(ctx, "CreateSingleConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversations(ctx context.Context, req *chat.ListConversationsRequest) (r *chat.ListConversationsResponse, err error) {
	var _args chat.ChatServiceListConversationsArgs
	_args.Req = req
	var _result chat.ChatServiceListConversationsResult
	if err = p.c.Call(ctx, "ListConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) JoinGroup(ctx context.Context, req *chat.JoinGroupRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceJoinGroupArgs
	_args.Req = req
	var _result chat.ChatServiceJoinGroupResult
	if err = p.c.Call(ctx, "JoinGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InviteMember(ctx context.Context, req *chat.InviteMemberRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceInviteMemberArgs
	_args.Req = req
	var _result chat.ChatServiceInviteMemberResult
	if err = p.c.Call(ctx, "InviteMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LeaveGroup(ctx context.Context, req *chat.LeaveGroupRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceLeaveGroupArgs
	_args.Req = req
	var _result chat.ChatServiceLeaveGroupResult
	if err = p.c.Call(ctx, "LeaveGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListMembers(ctx context.Context, req *chat.ListMembersRequest) (r *chat.ListMembersResponse, err error) {
	var _args chat.ChatServiceListMembersArgs
	_args.Req = req
	var _result chat.ChatServiceListMembersResult
	if err = p.c.Call(ctx, "ListMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListMessages(ctx context.Context, req *chat.ListMessagesRequest) (r *chat.ListMessagesResponse, err error) {
	var _args chat.ChatServiceListMessagesArgs
	_args.Req = req
	var _result chat.ChatServiceListMessagesResult
	if err = p.c.Call(ctx, "ListMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListBots(ctx context.Context, req *chat.ListBotsRequest) (r *chat.ListBotsResponse, err error) {
	var _args chat.ChatServiceListBotsArgs
	_args.Req = req
	var _result chat.ChatServiceListBotsResult
	if err = p.c.Call(ctx, "ListBots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversationBots(ctx context.Context, req *chat.ListConversationBotsRequest) (r *chat.ListConversationBotsResponse, err error) {
	var _args chat.ChatServiceListConversationBotsArgs
	_args.Req = req
	var _result chat.ChatServiceListConversationBotsResult
	if err = p.c.Call(ctx, "ListConversationBots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddConversationBot(ctx context.Context, req *chat.AddConversationBotRequest) (r *chat.AddConversationBotResponse, err error) {
	var _args chat.ChatServiceAddConversationBotArgs
	_args.Req = req
	var _result chat.ChatServiceAddConversationBotResult
	if err = p.c.Call(ctx, "AddConversationBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveConversationBot(ctx context.Context, req *chat.RemoveConversationBotRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceRemoveConversationBotArgs
	_args.Req = req
	var _result chat.ChatServiceRemoveConversationBotResult
	if err = p.c.Call(ctx, "RemoveConversationBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAICallLogs(ctx context.Context, req *chat.ListAICallLogsRequest) (r *chat.ListAICallLogsResponse, err error) {
	var _args chat.ChatServiceListAICallLogsArgs
	_args.Req = req
	var _result chat.ChatServiceListAICallLogsResult
	if err = p.c.Call(ctx, "ListAICallLogs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateMessage(ctx context.Context, req *chat.CreateMessageRequest) (r *chat.CreateMessageResponse, err error) {
	var _args chat.ChatServiceCreateMessageArgs
	_args.Req = req
	var _result chat.ChatServiceCreateMessageResult
	if err = p.c.Call(ctx, "CreateMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FindSingleByUsers(ctx context.Context, req *chat.FindSingleByUsersRequest) (r *chat.FindSingleByUsersResponse, err error) {
	var _args chat.ChatServiceFindSingleByUsersArgs
	_args.Req = req
	var _result chat.ChatServiceFindSingleByUsersResult
	if err = p.c.Call(ctx, "FindSingleByUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
