// Code generated by Kitex v0.16.1. DO NOT EDIT.

package chatservice

import (
	"context"
	chat "example.com/aim/chat-service/kitex_gen/chat"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Health(ctx context.Context, req *chat.HealthRequest, callOptions ...callopt.Option) (r *chat.HealthResponse, err error)
	CreateGroup(ctx context.Context, req *chat.CreateGroupRequest, callOptions ...callopt.Option) (r *chat.CreateGroupResponse, err error)
	CreateSingleConversation(ctx context.Context, req *chat.CreateSingleConversationRequest, callOptions ...callopt.Option) (r *chat.CreateSingleConversationResponse, err error)
	ListConversations(ctx context.Context, req *chat.ListConversationsRequest, callOptions ...callopt.Option) (r *chat.ListConversationsResponse, err error)
	JoinGroup(ctx context.Context, req *chat.JoinGroupRequest, callOptions ...callopt.Option) (r *chat.CommonResponse, err error)
	InviteMember(ctx context.Context, req *chat.InviteMemberRequest, callOptions ...callopt.Option) (r *chat.CommonResponse, err error)
	LeaveGroup(ctx context.Context, req *chat.LeaveGroupRequest, callOptions ...callopt.Option) (r *chat.CommonResponse, err error)
	ListMembers(ctx context.Context, req *chat.ListMembersRequest, callOptions ...callopt.Option) (r *chat.ListMembersResponse, err error)
	ListMessages(ctx context.Context, req *chat.ListMessagesRequest, callOptions ...callopt.Option) (r *chat.ListMessagesResponse, err error)
	ListBots(ctx context.Context, req *chat.ListBotsRequest, callOptions ...callopt.Option) (r *chat.ListBotsResponse, err error)
	ListConversationBots(ctx context.Context, req *chat.ListConversationBotsRequest, callOptions ...callopt.Option) (r *chat.ListConversationBotsResponse, err error)
	AddConversationBot(ctx context.Context, req *chat.AddConversationBotRequest, callOptions ...callopt.Option) (r *chat.AddConversationBotResponse, err error)
	RemoveConversationBot(ctx context.Context, req *chat.RemoveConversationBotRequest, callOptions ...callopt.Option) (r *chat.CommonResponse, err error)
	ListAICallLogs(ctx context.Context, req *chat.ListAICallLogsRequest, callOptions ...callopt.Option) (r *chat.ListAICallLogsResponse, err error)
	CreateMessage(ctx context.Context, req *chat.CreateMessageRequest, callOptions ...callopt.Option) (r *chat.CreateMessageResponse, err error)
	FindSingleByUsers(ctx context.Context, req *chat.FindSingleByUsersRequest, callOptions ...callopt.Option) (r *chat.FindSingleByUsersResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChatServiceClient struct {
	*kClient
}

func (p *kChatServiceClient) Health(ctx context.Context, req *chat.HealthRequest, callOptions ...callopt.Option) (r *chat.HealthResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx, req)
}

func (p *kChatServiceClient) CreateGroup(ctx context.Context, req *chat.CreateGroupRequest, callOptions ...callopt.Option) (r *chat.CreateGroupResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateGroup(ctx, req)
}

func (p *kChatServiceClient) CreateSingleConversation(ctx context.Context, req *chat.CreateSingleConversationRequest, callOptions ...callopt.Option) (r *chat.CreateSingleConversationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSingleConversation(ctx, req)
}

func (p *kChatServiceClient) ListConversations(ctx context.Context, req *chat.ListConversationsRequest, callOptions ...callopt.Option) (r *chat.ListConversationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConversations(ctx, req)
}

func (p *kChatServiceClient) JoinGroup(ctx context.Context, req *chat.JoinGroupRequest, callOptions ...callopt.Option) (r *chat.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.JoinGroup(ctx, req)
}

func (p *kChatServiceClient) InviteMember(ctx context.Context, req *chat.InviteMemberRequest, callOptions ...callopt.Option) (r *chat.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InviteMember(ctx, req)
}

func (p *kChatServiceClient) LeaveGroup(ctx context.Context, req *chat.LeaveGroupRequest, callOptions ...callopt.Option) (r *chat.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LeaveGroup(ctx, req)
}

func (p *kChatServiceClient) ListMembers(ctx context.Context, req *chat.ListMembersRequest, callOptions ...callopt.Option) (r *chat.ListMembersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMembers(ctx, req)
}

func (p *kChatServiceClient) ListMessages(ctx context.Context, req *chat.ListMessagesRequest, callOptions ...callopt.Option) (r *chat.ListMessagesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMessages(ctx, req)
}

func (p *kChatServiceClient) ListBots(ctx context.Context, req *chat.ListBotsRequest, callOptions ...callopt.Option) (r *chat.ListBotsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBots(ctx, req)
}

func (p *kChatServiceClient) ListConversationBots(ctx context.Context, req *chat.ListConversationBotsRequest, callOptions ...callopt.Option) (r *chat.ListConversationBotsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConversationBots(ctx, req)
}

func (p *kChatServiceClient) AddConversationBot(ctx context.Context, req *chat.AddConversationBotRequest, callOptions ...callopt.Option) (r *chat.AddConversationBotResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddConversationBot(ctx, req)
}

func (p *kChatServiceClient) RemoveConversationBot(ctx context.Context, req *chat.RemoveConversationBotRequest, callOptions ...callopt.Option) (r *chat.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveConversationBot(ctx, req)
}

func (p *kChatServiceClient) ListAICallLogs(ctx context.Context, req *chat.ListAICallLogsRequest, callOptions ...callopt.Option) (r *chat.ListAICallLogsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAICallLogs(ctx, req)
}

func (p *kChatServiceClient) CreateMessage(ctx context.Context, req *chat.CreateMessageRequest, callOptions ...callopt.Option) (r *chat.CreateMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateMessage(ctx, req)
}

func (p *kChatServiceClient) FindSingleByUsers(ctx context.Context, req *chat.FindSingleByUsersRequest, callOptions ...callopt.Option) (r *chat.FindSingleByUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindSingleByUsers(ctx, req)
}
