// Code generated by Kitex v0.16.1. DO NOT EDIT.

package chatservice

import (
	"context"
	"errors"
	chat "example.com/aim/gateway/kitex_gen/chat"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newChatServiceHealthArgs,
		newChatServiceHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateGroup": kitex.NewMethodInfo(
		createGroupHandler,
		newChatServiceCreateGroupArgs,
		newChatServiceCreateGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupInfo": kitex.NewMethodInfo(
		getGroupInfoHandler,
		newChatServiceGetGroupInfoArgs,
		newChatServiceGetGroupInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateSingleConversation": kitex.NewMethodInfo(
		createSingleConversationHandler,
		newChatServiceCreateSingleConversationArgs,
		newChatServiceCreateSingleConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversations": kitex.NewMethodInfo(
		listConversationsHandler,
		newChatServiceListConversationsArgs,
		newChatServiceListConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"JoinGroup": kitex.NewMethodInfo(
		joinGroupHandler,
		newChatServiceJoinGroupArgs,
		newChatServiceJoinGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"InviteMember": kitex.NewMethodInfo(
		inviteMemberHandler,
		newChatServiceInviteMemberArgs,
		newChatServiceInviteMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LeaveGroup": kitex.NewMethodInfo(
		leaveGroupHandler,
		newChatServiceLeaveGroupArgs,
		newChatServiceLeaveGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TransferOwner": kitex.NewMethodInfo(
		transferOwnerHandler,
		newChatServiceTransferOwnerArgs,
		newChatServiceTransferOwnerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetAdmin": kitex.NewMethodInfo(
		setAdminHandler,
		newChatServiceSetAdminArgs,
		newChatServiceSetAdminResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveAdmin": kitex.NewMethodInfo(
		removeAdminHandler,
		newChatServiceRemoveAdminArgs,
		newChatServiceRemoveAdminResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MuteMember": kitex.NewMethodInfo(
		muteMemberHandler,
		newChatServiceMuteMemberArgs,
		newChatServiceMuteMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnmuteMember": kitex.NewMethodInfo(
		unmuteMemberHandler,
		newChatServiceUnmuteMemberArgs,
		newChatServiceUnmuteMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveMember": kitex.NewMethodInfo(
		removeMemberHandler,
		newChatServiceRemoveMemberArgs,
		newChatServiceRemoveMemberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetGroupMuteAll": kitex.NewMethodInfo(
		setGroupMuteAllHandler,
		newChatServiceSetGroupMuteAllArgs,
		newChatServiceSetGroupMuteAllResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateGroupAnnouncement": kitex.NewMethodInfo(
		updateGroupAnnouncementHandler,
		newChatServiceUpdateGroupAnnouncementArgs,
		newChatServiceUpdateGroupAnnouncementResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListMembers": kitex.NewMethodInfo(
		listMembersHandler,
		newChatServiceListMembersArgs,
		newChatServiceListMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListMessages": kitex.NewMethodInfo(
		listMessagesHandler,
		newChatServiceListMessagesArgs,
		newChatServiceListMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkConversationRead": kitex.NewMethodInfo(
		markConversationReadHandler,
		newChatServiceMarkConversationReadArgs,
		newChatServiceMarkConversationReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RecallMessage": kitex.NewMethodInfo(
		recallMessageHandler,
		newChatServiceRecallMessageArgs,
		newChatServiceRecallMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListBots": kitex.NewMethodInfo(
		listBotsHandler,
		newChatServiceListBotsArgs,
		newChatServiceListBotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateCustomBot": kitex.NewMethodInfo(
		createCustomBotHandler,
		newChatServiceCreateCustomBotArgs,
		newChatServiceCreateCustomBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListCustomBots": kitex.NewMethodInfo(
		listCustomBotsHandler,
		newChatServiceListCustomBotsArgs,
		newChatServiceListCustomBotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateCustomBot": kitex.NewMethodInfo(
		updateCustomBotHandler,
		newChatServiceUpdateCustomBotArgs,
		newChatServiceUpdateCustomBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteCustomBot": kitex.NewMethodInfo(
		deleteCustomBotHandler,
		newChatServiceDeleteCustomBotArgs,
		newChatServiceDeleteCustomBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversationBots": kitex.NewMethodInfo(
		listConversationBotsHandler,
		newChatServiceListConversationBotsArgs,
		newChatServiceListConversationBotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddConversationBot": kitex.NewMethodInfo(
		addConversationBotHandler,
		newChatServiceAddConversationBotArgs,
		newChatServiceAddConversationBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveConversationBot": kitex.NewMethodInfo(
		removeConversationBotHandler,
		newChatServiceRemoveConversationBotArgs,
		newChatServiceRemoveConversationBotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAICallLogs": kitex.NewMethodInfo(
		listAICallLogsHandler,
		newChatServiceListAICallLogsArgs,
		newChatServiceListAICallLogsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListNotifications": kitex.NewMethodInfo(
		listNotificationsHandler,
		newChatServiceListNotificationsArgs,
		newChatServiceListNotificationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkNotificationRead": kitex.NewMethodInfo(
		markNotificationReadHandler,
		newChatServiceMarkNotificationReadArgs,
		newChatServiceMarkNotificationReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkAllNotificationsRead": kitex.NewMethodInfo(
		markAllNotificationsReadHandler,
		newChatServiceMarkAllNotificationsReadArgs,
		newChatServiceMarkAllNotificationsReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateNotification": kitex.NewMethodInfo(
		createNotificationHandler,
		newChatServiceCreateNotificationArgs,
		newChatServiceCreateNotificationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateKnowledgeBase": kitex.NewMethodInfo(
		createKnowledgeBaseHandler,
		newChatServiceCreateKnowledgeBaseArgs,
		newChatServiceCreateKnowledgeBaseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListKnowledgeBases": kitex.NewMethodInfo(
		listKnowledgeBasesHandler,
		newChatServiceListKnowledgeBasesArgs,
		newChatServiceListKnowledgeBasesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddKnowledgeDocumentText": kitex.NewMethodInfo(
		addKnowledgeDocumentTextHandler,
		newChatServiceAddKnowledgeDocumentTextArgs,
		newChatServiceAddKnowledgeDocumentTextResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListKnowledgeDocuments": kitex.NewMethodInfo(
		listKnowledgeDocumentsHandler,
		newChatServiceListKnowledgeDocumentsArgs,
		newChatServiceListKnowledgeDocumentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchKnowledgeBase": kitex.NewMethodInfo(
		searchKnowledgeBaseHandler,
		newChatServiceSearchKnowledgeBaseArgs,
		newChatServiceSearchKnowledgeBaseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindConversationKnowledgeBase": kitex.NewMethodInfo(
		bindConversationKnowledgeBaseHandler,
		newChatServiceBindConversationKnowledgeBaseArgs,
		newChatServiceBindConversationKnowledgeBaseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversationKnowledgeBases": kitex.NewMethodInfo(
		listConversationKnowledgeBasesHandler,
		newChatServiceListConversationKnowledgeBasesArgs,
		newChatServiceListConversationKnowledgeBasesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnbindConversationKnowledgeBase": kitex.NewMethodInfo(
		unbindConversationKnowledgeBaseHandler,
		newChatServiceUnbindConversationKnowledgeBaseArgs,
		newChatServiceUnbindConversationKnowledgeBaseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateMessage": kitex.NewMethodInfo(
		createMessageHandler,
		newChatServiceCreateMessageArgs,
		newChatServiceCreateMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FindSingleByUsers": kitex.NewMethodInfo(
		findSingleByUsersHandler,
		newChatServiceFindSingleByUsersArgs,
		newChatServiceFindSingleByUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"WriteUserMemory": kitex.NewMethodInfo(
		writeUserMemoryHandler,
		newChatServiceWriteUserMemoryArgs,
		newChatServiceWriteUserMemoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListUserMemories": kitex.NewMethodInfo(
		listUserMemoriesHandler,
		newChatServiceListUserMemoriesArgs,
		newChatServiceListUserMemoriesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserMemory": kitex.NewMethodInfo(
		updateUserMemoryHandler,
		newChatServiceUpdateUserMemoryArgs,
		newChatServiceUpdateUserMemoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	chatServiceServiceInfo                = NewServiceInfo()
	chatServiceServiceInfoForClient       = NewServiceInfoForClient()
	chatServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return chatServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ChatService"
	handlerType := (*chat.ChatService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "chat",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceHealthArgs)
	realResult := result.(*chat.ChatServiceHealthResult)
	success, err := handler.(chat.ChatService).Health(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceHealthArgs() interface{} {
	return chat.NewChatServiceHealthArgs()
}

func newChatServiceHealthResult() interface{} {
	return chat.NewChatServiceHealthResult()
}

func createGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateGroupArgs)
	realResult := result.(*chat.ChatServiceCreateGroupResult)
	success, err := handler.(chat.ChatService).CreateGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateGroupArgs() interface{} {
	return chat.NewChatServiceCreateGroupArgs()
}

func newChatServiceCreateGroupResult() interface{} {
	return chat.NewChatServiceCreateGroupResult()
}

func getGroupInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceGetGroupInfoArgs)
	realResult := result.(*chat.ChatServiceGetGroupInfoResult)
	success, err := handler.(chat.ChatService).GetGroupInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceGetGroupInfoArgs() interface{} {
	return chat.NewChatServiceGetGroupInfoArgs()
}

func newChatServiceGetGroupInfoResult() interface{} {
	return chat.NewChatServiceGetGroupInfoResult()
}

func createSingleConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateSingleConversationArgs)
	realResult := result.(*chat.ChatServiceCreateSingleConversationResult)
	success, err := handler.(chat.ChatService).CreateSingleConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateSingleConversationArgs() interface{} {
	return chat.NewChatServiceCreateSingleConversationArgs()
}

func newChatServiceCreateSingleConversationResult() interface{} {
	return chat.NewChatServiceCreateSingleConversationResult()
}

func listConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListConversationsArgs)
	realResult := result.(*chat.ChatServiceListConversationsResult)
	success, err := handler.(chat.ChatService).ListConversations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListConversationsArgs() interface{} {
	return chat.NewChatServiceListConversationsArgs()
}

func newChatServiceListConversationsResult() interface{} {
	return chat.NewChatServiceListConversationsResult()
}

func joinGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceJoinGroupArgs)
	realResult := result.(*chat.ChatServiceJoinGroupResult)
	success, err := handler.(chat.ChatService).JoinGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceJoinGroupArgs() interface{} {
	return chat.NewChatServiceJoinGroupArgs()
}

func newChatServiceJoinGroupResult() interface{} {
	return chat.NewChatServiceJoinGroupResult()
}

func inviteMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceInviteMemberArgs)
	realResult := result.(*chat.ChatServiceInviteMemberResult)
	success, err := handler.(chat.ChatService).InviteMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceInviteMemberArgs() interface{} {
	return chat.NewChatServiceInviteMemberArgs()
}

func newChatServiceInviteMemberResult() interface{} {
	return chat.NewChatServiceInviteMemberResult()
}

func leaveGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceLeaveGroupArgs)
	realResult := result.(*chat.ChatServiceLeaveGroupResult)
	success, err := handler.(chat.ChatService).LeaveGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceLeaveGroupArgs() interface{} {
	return chat.NewChatServiceLeaveGroupArgs()
}

func newChatServiceLeaveGroupResult() interface{} {
	return chat.NewChatServiceLeaveGroupResult()
}

func transferOwnerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceTransferOwnerArgs)
	realResult := result.(*chat.ChatServiceTransferOwnerResult)
	success, err := handler.(chat.ChatService).TransferOwner(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceTransferOwnerArgs() interface{} {
	return chat.NewChatServiceTransferOwnerArgs()
}

func newChatServiceTransferOwnerResult() interface{} {
	return chat.NewChatServiceTransferOwnerResult()
}

func setAdminHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceSetAdminArgs)
	realResult := result.(*chat.ChatServiceSetAdminResult)
	success, err := handler.(chat.ChatService).SetAdmin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceSetAdminArgs() interface{} {
	return chat.NewChatServiceSetAdminArgs()
}

func newChatServiceSetAdminResult() interface{} {
	return chat.NewChatServiceSetAdminResult()
}

func removeAdminHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceRemoveAdminArgs)
	realResult := result.(*chat.ChatServiceRemoveAdminResult)
	success, err := handler.(chat.ChatService).RemoveAdmin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceRemoveAdminArgs() interface{} {
	return chat.NewChatServiceRemoveAdminArgs()
}

func newChatServiceRemoveAdminResult() interface{} {
	return chat.NewChatServiceRemoveAdminResult()
}

func muteMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceMuteMemberArgs)
	realResult := result.(*chat.ChatServiceMuteMemberResult)
	success, err := handler.(chat.ChatService).MuteMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceMuteMemberArgs() interface{} {
	return chat.NewChatServiceMuteMemberArgs()
}

func newChatServiceMuteMemberResult() interface{} {
	return chat.NewChatServiceMuteMemberResult()
}

func unmuteMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceUnmuteMemberArgs)
	realResult := result.(*chat.ChatServiceUnmuteMemberResult)
	success, err := handler.(chat.ChatService).UnmuteMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceUnmuteMemberArgs() interface{} {
	return chat.NewChatServiceUnmuteMemberArgs()
}

func newChatServiceUnmuteMemberResult() interface{} {
	return chat.NewChatServiceUnmuteMemberResult()
}

func removeMemberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceRemoveMemberArgs)
	realResult := result.(*chat.ChatServiceRemoveMemberResult)
	success, err := handler.(chat.ChatService).RemoveMember(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceRemoveMemberArgs() interface{} {
	return chat.NewChatServiceRemoveMemberArgs()
}

func newChatServiceRemoveMemberResult() interface{} {
	return chat.NewChatServiceRemoveMemberResult()
}

func setGroupMuteAllHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceSetGroupMuteAllArgs)
	realResult := result.(*chat.ChatServiceSetGroupMuteAllResult)
	success, err := handler.(chat.ChatService).SetGroupMuteAll(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceSetGroupMuteAllArgs() interface{} {
	return chat.NewChatServiceSetGroupMuteAllArgs()
}

func newChatServiceSetGroupMuteAllResult() interface{} {
	return chat.NewChatServiceSetGroupMuteAllResult()
}

func updateGroupAnnouncementHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceUpdateGroupAnnouncementArgs)
	realResult := result.(*chat.ChatServiceUpdateGroupAnnouncementResult)
	success, err := handler.(chat.ChatService).UpdateGroupAnnouncement(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceUpdateGroupAnnouncementArgs() interface{} {
	return chat.NewChatServiceUpdateGroupAnnouncementArgs()
}

func newChatServiceUpdateGroupAnnouncementResult() interface{} {
	return chat.NewChatServiceUpdateGroupAnnouncementResult()
}

func listMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListMembersArgs)
	realResult := result.(*chat.ChatServiceListMembersResult)
	success, err := handler.(chat.ChatService).ListMembers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListMembersArgs() interface{} {
	return chat.NewChatServiceListMembersArgs()
}

func newChatServiceListMembersResult() interface{} {
	return chat.NewChatServiceListMembersResult()
}

func listMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListMessagesArgs)
	realResult := result.(*chat.ChatServiceListMessagesResult)
	success, err := handler.(chat.ChatService).ListMessages(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListMessagesArgs() interface{} {
	return chat.NewChatServiceListMessagesArgs()
}

func newChatServiceListMessagesResult() interface{} {
	return chat.NewChatServiceListMessagesResult()
}

func markConversationReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceMarkConversationReadArgs)
	realResult := result.(*chat.ChatServiceMarkConversationReadResult)
	success, err := handler.(chat.ChatService).MarkConversationRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceMarkConversationReadArgs() interface{} {
	return chat.NewChatServiceMarkConversationReadArgs()
}

func newChatServiceMarkConversationReadResult() interface{} {
	return chat.NewChatServiceMarkConversationReadResult()
}

func recallMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceRecallMessageArgs)
	realResult := result.(*chat.ChatServiceRecallMessageResult)
	success, err := handler.(chat.ChatService).RecallMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceRecallMessageArgs() interface{} {
	return chat.NewChatServiceRecallMessageArgs()
}

func newChatServiceRecallMessageResult() interface{} {
	return chat.NewChatServiceRecallMessageResult()
}

func listBotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListBotsArgs)
	realResult := result.(*chat.ChatServiceListBotsResult)
	success, err := handler.(chat.ChatService).ListBots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListBotsArgs() interface{} {
	return chat.NewChatServiceListBotsArgs()
}

func newChatServiceListBotsResult() interface{} {
	return chat.NewChatServiceListBotsResult()
}

func createCustomBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateCustomBotArgs)
	realResult := result.(*chat.ChatServiceCreateCustomBotResult)
	success, err := handler.(chat.ChatService).CreateCustomBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateCustomBotArgs() interface{} {
	return chat.NewChatServiceCreateCustomBotArgs()
}

func newChatServiceCreateCustomBotResult() interface{} {
	return chat.NewChatServiceCreateCustomBotResult()
}

func listCustomBotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListCustomBotsArgs)
	realResult := result.(*chat.ChatServiceListCustomBotsResult)
	success, err := handler.(chat.ChatService).ListCustomBots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListCustomBotsArgs() interface{} {
	return chat.NewChatServiceListCustomBotsArgs()
}

func newChatServiceListCustomBotsResult() interface{} {
	return chat.NewChatServiceListCustomBotsResult()
}

func updateCustomBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceUpdateCustomBotArgs)
	realResult := result.(*chat.ChatServiceUpdateCustomBotResult)
	success, err := handler.(chat.ChatService).UpdateCustomBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceUpdateCustomBotArgs() interface{} {
	return chat.NewChatServiceUpdateCustomBotArgs()
}

func newChatServiceUpdateCustomBotResult() interface{} {
	return chat.NewChatServiceUpdateCustomBotResult()
}

func deleteCustomBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceDeleteCustomBotArgs)
	realResult := result.(*chat.ChatServiceDeleteCustomBotResult)
	success, err := handler.(chat.ChatService).DeleteCustomBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceDeleteCustomBotArgs() interface{} {
	return chat.NewChatServiceDeleteCustomBotArgs()
}

func newChatServiceDeleteCustomBotResult() interface{} {
	return chat.NewChatServiceDeleteCustomBotResult()
}

func listConversationBotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListConversationBotsArgs)
	realResult := result.(*chat.ChatServiceListConversationBotsResult)
	success, err := handler.(chat.ChatService).ListConversationBots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListConversationBotsArgs() interface{} {
	return chat.NewChatServiceListConversationBotsArgs()
}

func newChatServiceListConversationBotsResult() interface{} {
	return chat.NewChatServiceListConversationBotsResult()
}

func addConversationBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceAddConversationBotArgs)
	realResult := result.(*chat.ChatServiceAddConversationBotResult)
	success, err := handler.(chat.ChatService).AddConversationBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceAddConversationBotArgs() interface{} {
	return chat.NewChatServiceAddConversationBotArgs()
}

func newChatServiceAddConversationBotResult() interface{} {
	return chat.NewChatServiceAddConversationBotResult()
}

func removeConversationBotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceRemoveConversationBotArgs)
	realResult := result.(*chat.ChatServiceRemoveConversationBotResult)
	success, err := handler.(chat.ChatService).RemoveConversationBot(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceRemoveConversationBotArgs() interface{} {
	return chat.NewChatServiceRemoveConversationBotArgs()
}

func newChatServiceRemoveConversationBotResult() interface{} {
	return chat.NewChatServiceRemoveConversationBotResult()
}

func listAICallLogsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListAICallLogsArgs)
	realResult := result.(*chat.ChatServiceListAICallLogsResult)
	success, err := handler.(chat.ChatService).ListAICallLogs(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListAICallLogsArgs() interface{} {
	return chat.NewChatServiceListAICallLogsArgs()
}

func newChatServiceListAICallLogsResult() interface{} {
	return chat.NewChatServiceListAICallLogsResult()
}

func listNotificationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListNotificationsArgs)
	realResult := result.(*chat.ChatServiceListNotificationsResult)
	success, err := handler.(chat.ChatService).ListNotifications(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListNotificationsArgs() interface{} {
	return chat.NewChatServiceListNotificationsArgs()
}

func newChatServiceListNotificationsResult() interface{} {
	return chat.NewChatServiceListNotificationsResult()
}

func markNotificationReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceMarkNotificationReadArgs)
	realResult := result.(*chat.ChatServiceMarkNotificationReadResult)
	success, err := handler.(chat.ChatService).MarkNotificationRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceMarkNotificationReadArgs() interface{} {
	return chat.NewChatServiceMarkNotificationReadArgs()
}

func newChatServiceMarkNotificationReadResult() interface{} {
	return chat.NewChatServiceMarkNotificationReadResult()
}

func markAllNotificationsReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceMarkAllNotificationsReadArgs)
	realResult := result.(*chat.ChatServiceMarkAllNotificationsReadResult)
	success, err := handler.(chat.ChatService).MarkAllNotificationsRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceMarkAllNotificationsReadArgs() interface{} {
	return chat.NewChatServiceMarkAllNotificationsReadArgs()
}

func newChatServiceMarkAllNotificationsReadResult() interface{} {
	return chat.NewChatServiceMarkAllNotificationsReadResult()
}

func createNotificationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateNotificationArgs)
	realResult := result.(*chat.ChatServiceCreateNotificationResult)
	success, err := handler.(chat.ChatService).CreateNotification(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateNotificationArgs() interface{} {
	return chat.NewChatServiceCreateNotificationArgs()
}

func newChatServiceCreateNotificationResult() interface{} {
	return chat.NewChatServiceCreateNotificationResult()
}

func createKnowledgeBaseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateKnowledgeBaseArgs)
	realResult := result.(*chat.ChatServiceCreateKnowledgeBaseResult)
	success, err := handler.(chat.ChatService).CreateKnowledgeBase(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateKnowledgeBaseArgs() interface{} {
	return chat.NewChatServiceCreateKnowledgeBaseArgs()
}

func newChatServiceCreateKnowledgeBaseResult() interface{} {
	return chat.NewChatServiceCreateKnowledgeBaseResult()
}

func listKnowledgeBasesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListKnowledgeBasesArgs)
	realResult := result.(*chat.ChatServiceListKnowledgeBasesResult)
	success, err := handler.(chat.ChatService).ListKnowledgeBases(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListKnowledgeBasesArgs() interface{} {
	return chat.NewChatServiceListKnowledgeBasesArgs()
}

func newChatServiceListKnowledgeBasesResult() interface{} {
	return chat.NewChatServiceListKnowledgeBasesResult()
}

func addKnowledgeDocumentTextHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceAddKnowledgeDocumentTextArgs)
	realResult := result.(*chat.ChatServiceAddKnowledgeDocumentTextResult)
	success, err := handler.(chat.ChatService).AddKnowledgeDocumentText(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceAddKnowledgeDocumentTextArgs() interface{} {
	return chat.NewChatServiceAddKnowledgeDocumentTextArgs()
}

func newChatServiceAddKnowledgeDocumentTextResult() interface{} {
	return chat.NewChatServiceAddKnowledgeDocumentTextResult()
}

func listKnowledgeDocumentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListKnowledgeDocumentsArgs)
	realResult := result.(*chat.ChatServiceListKnowledgeDocumentsResult)
	success, err := handler.(chat.ChatService).ListKnowledgeDocuments(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListKnowledgeDocumentsArgs() interface{} {
	return chat.NewChatServiceListKnowledgeDocumentsArgs()
}

func newChatServiceListKnowledgeDocumentsResult() interface{} {
	return chat.NewChatServiceListKnowledgeDocumentsResult()
}

func searchKnowledgeBaseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceSearchKnowledgeBaseArgs)
	realResult := result.(*chat.ChatServiceSearchKnowledgeBaseResult)
	success, err := handler.(chat.ChatService).SearchKnowledgeBase(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceSearchKnowledgeBaseArgs() interface{} {
	return chat.NewChatServiceSearchKnowledgeBaseArgs()
}

func newChatServiceSearchKnowledgeBaseResult() interface{} {
	return chat.NewChatServiceSearchKnowledgeBaseResult()
}

func bindConversationKnowledgeBaseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceBindConversationKnowledgeBaseArgs)
	realResult := result.(*chat.ChatServiceBindConversationKnowledgeBaseResult)
	success, err := handler.(chat.ChatService).BindConversationKnowledgeBase(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceBindConversationKnowledgeBaseArgs() interface{} {
	return chat.NewChatServiceBindConversationKnowledgeBaseArgs()
}

func newChatServiceBindConversationKnowledgeBaseResult() interface{} {
	return chat.NewChatServiceBindConversationKnowledgeBaseResult()
}

func listConversationKnowledgeBasesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListConversationKnowledgeBasesArgs)
	realResult := result.(*chat.ChatServiceListConversationKnowledgeBasesResult)
	success, err := handler.(chat.ChatService).ListConversationKnowledgeBases(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListConversationKnowledgeBasesArgs() interface{} {
	return chat.NewChatServiceListConversationKnowledgeBasesArgs()
}

func newChatServiceListConversationKnowledgeBasesResult() interface{} {
	return chat.NewChatServiceListConversationKnowledgeBasesResult()
}

func unbindConversationKnowledgeBaseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceUnbindConversationKnowledgeBaseArgs)
	realResult := result.(*chat.ChatServiceUnbindConversationKnowledgeBaseResult)
	success, err := handler.(chat.ChatService).UnbindConversationKnowledgeBase(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceUnbindConversationKnowledgeBaseArgs() interface{} {
	return chat.NewChatServiceUnbindConversationKnowledgeBaseArgs()
}

func newChatServiceUnbindConversationKnowledgeBaseResult() interface{} {
	return chat.NewChatServiceUnbindConversationKnowledgeBaseResult()
}

func createMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateMessageArgs)
	realResult := result.(*chat.ChatServiceCreateMessageResult)
	success, err := handler.(chat.ChatService).CreateMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateMessageArgs() interface{} {
	return chat.NewChatServiceCreateMessageArgs()
}

func newChatServiceCreateMessageResult() interface{} {
	return chat.NewChatServiceCreateMessageResult()
}

func findSingleByUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceFindSingleByUsersArgs)
	realResult := result.(*chat.ChatServiceFindSingleByUsersResult)
	success, err := handler.(chat.ChatService).FindSingleByUsers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceFindSingleByUsersArgs() interface{} {
	return chat.NewChatServiceFindSingleByUsersArgs()
}

func newChatServiceFindSingleByUsersResult() interface{} {
	return chat.NewChatServiceFindSingleByUsersResult()
}

func writeUserMemoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceWriteUserMemoryArgs)
	realResult := result.(*chat.ChatServiceWriteUserMemoryResult)
	success, err := handler.(chat.ChatService).WriteUserMemory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceWriteUserMemoryArgs() interface{} {
	return chat.NewChatServiceWriteUserMemoryArgs()
}

func newChatServiceWriteUserMemoryResult() interface{} {
	return chat.NewChatServiceWriteUserMemoryResult()
}

func listUserMemoriesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceListUserMemoriesArgs)
	realResult := result.(*chat.ChatServiceListUserMemoriesResult)
	success, err := handler.(chat.ChatService).ListUserMemories(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceListUserMemoriesArgs() interface{} {
	return chat.NewChatServiceListUserMemoriesArgs()
}

func newChatServiceListUserMemoriesResult() interface{} {
	return chat.NewChatServiceListUserMemoriesResult()
}

func updateUserMemoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceUpdateUserMemoryArgs)
	realResult := result.(*chat.ChatServiceUpdateUserMemoryResult)
	success, err := handler.(chat.ChatService).UpdateUserMemory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceUpdateUserMemoryArgs() interface{} {
	return chat.NewChatServiceUpdateUserMemoryArgs()
}

func newChatServiceUpdateUserMemoryResult() interface{} {
	return chat.NewChatServiceUpdateUserMemoryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Health(ctx context.Context, req *chat.HealthRequest) (r *chat.HealthResponse, err error) {
	var _args chat.ChatServiceHealthArgs
	_args.Req = req
	var _result chat.ChatServiceHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateGroup(ctx context.Context, req *chat.CreateGroupRequest) (r *chat.CreateGroupResponse, err error) {
	var _args chat.ChatServiceCreateGroupArgs
	_args.Req = req
	var _result chat.ChatServiceCreateGroupResult
	if err = p.c.Call(ctx, "CreateGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupInfo(ctx context.Context, req *chat.GetGroupInfoRequest) (r *chat.GetGroupInfoResponse, err error) {
	var _args chat.ChatServiceGetGroupInfoArgs
	_args.Req = req
	var _result chat.ChatServiceGetGroupInfoResult
	if err = p.c.Call(ctx, "GetGroupInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateSingleConversation(ctx context.Context, req *chat.CreateSingleConversationRequest) (r *chat.CreateSingleConversationResponse, err error) {
	var _args chat.ChatServiceCreateSingleConversationArgs
	_args.Req = req
	var _result chat.ChatServiceCreateSingleConversationResult
	if err = p.c.Call(ctx, "CreateSingleConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversations(ctx context.Context, req *chat.ListConversationsRequest) (r *chat.ListConversationsResponse, err error) {
	var _args chat.ChatServiceListConversationsArgs
	_args.Req = req
	var _result chat.ChatServiceListConversationsResult
	if err = p.c.Call(ctx, "ListConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) JoinGroup(ctx context.Context, req *chat.JoinGroupRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceJoinGroupArgs
	_args.Req = req
	var _result chat.ChatServiceJoinGroupResult
	if err = p.c.Call(ctx, "JoinGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InviteMember(ctx context.Context, req *chat.InviteMemberRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceInviteMemberArgs
	_args.Req = req
	var _result chat.ChatServiceInviteMemberResult
	if err = p.c.Call(ctx, "InviteMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LeaveGroup(ctx context.Context, req *chat.LeaveGroupRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceLeaveGroupArgs
	_args.Req = req
	var _result chat.ChatServiceLeaveGroupResult
	if err = p.c.Call(ctx, "LeaveGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TransferOwner(ctx context.Context, req *chat.TransferOwnerRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceTransferOwnerArgs
	_args.Req = req
	var _result chat.ChatServiceTransferOwnerResult
	if err = p.c.Call(ctx, "TransferOwner", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetAdmin(ctx context.Context, req *chat.SetAdminRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceSetAdminArgs
	_args.Req = req
	var _result chat.ChatServiceSetAdminResult
	if err = p.c.Call(ctx, "SetAdmin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveAdmin(ctx context.Context, req *chat.RemoveAdminRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceRemoveAdminArgs
	_args.Req = req
	var _result chat.ChatServiceRemoveAdminResult
	if err = p.c.Call(ctx, "RemoveAdmin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MuteMember(ctx context.Context, req *chat.MuteMemberRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceMuteMemberArgs
	_args.Req = req
	var _result chat.ChatServiceMuteMemberResult
	if err = p.c.Call(ctx, "MuteMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnmuteMember(ctx context.Context, req *chat.UnmuteMemberRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceUnmuteMemberArgs
	_args.Req = req
	var _result chat.ChatServiceUnmuteMemberResult
	if err = p.c.Call(ctx, "UnmuteMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveMember(ctx context.Context, req *chat.RemoveMemberRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceRemoveMemberArgs
	_args.Req = req
	var _result chat.ChatServiceRemoveMemberResult
	if err = p.c.Call(ctx, "RemoveMember", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetGroupMuteAll(ctx context.Context, req *chat.SetGroupMuteAllRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceSetGroupMuteAllArgs
	_args.Req = req
	var _result chat.ChatServiceSetGroupMuteAllResult
	if err = p.c.Call(ctx, "SetGroupMuteAll", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateGroupAnnouncement(ctx context.Context, req *chat.UpdateGroupAnnouncementRequest) (r *chat.ConversationEventResponse, err error) {
	var _args chat.ChatServiceUpdateGroupAnnouncementArgs
	_args.Req = req
	var _result chat.ChatServiceUpdateGroupAnnouncementResult
	if err = p.c.Call(ctx, "UpdateGroupAnnouncement", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListMembers(ctx context.Context, req *chat.ListMembersRequest) (r *chat.ListMembersResponse, err error) {
	var _args chat.ChatServiceListMembersArgs
	_args.Req = req
	var _result chat.ChatServiceListMembersResult
	if err = p.c.Call(ctx, "ListMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListMessages(ctx context.Context, req *chat.ListMessagesRequest) (r *chat.ListMessagesResponse, err error) {
	var _args chat.ChatServiceListMessagesArgs
	_args.Req = req
	var _result chat.ChatServiceListMessagesResult
	if err = p.c.Call(ctx, "ListMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkConversationRead(ctx context.Context, req *chat.MarkConversationReadRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceMarkConversationReadArgs
	_args.Req = req
	var _result chat.ChatServiceMarkConversationReadResult
	if err = p.c.Call(ctx, "MarkConversationRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RecallMessage(ctx context.Context, req *chat.RecallMessageRequest) (r *chat.MessageRecalledEventResponse, err error) {
	var _args chat.ChatServiceRecallMessageArgs
	_args.Req = req
	var _result chat.ChatServiceRecallMessageResult
	if err = p.c.Call(ctx, "RecallMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListBots(ctx context.Context, req *chat.ListBotsRequest) (r *chat.ListBotsResponse, err error) {
	var _args chat.ChatServiceListBotsArgs
	_args.Req = req
	var _result chat.ChatServiceListBotsResult
	if err = p.c.Call(ctx, "ListBots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateCustomBot(ctx context.Context, req *chat.CreateCustomBotRequest) (r *chat.CreateCustomBotResponse, err error) {
	var _args chat.ChatServiceCreateCustomBotArgs
	_args.Req = req
	var _result chat.ChatServiceCreateCustomBotResult
	if err = p.c.Call(ctx, "CreateCustomBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListCustomBots(ctx context.Context, req *chat.ListCustomBotsRequest) (r *chat.ListCustomBotsResponse, err error) {
	var _args chat.ChatServiceListCustomBotsArgs
	_args.Req = req
	var _result chat.ChatServiceListCustomBotsResult
	if err = p.c.Call(ctx, "ListCustomBots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateCustomBot(ctx context.Context, req *chat.UpdateCustomBotRequest) (r *chat.UpdateCustomBotResponse, err error) {
	var _args chat.ChatServiceUpdateCustomBotArgs
	_args.Req = req
	var _result chat.ChatServiceUpdateCustomBotResult
	if err = p.c.Call(ctx, "UpdateCustomBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteCustomBot(ctx context.Context, req *chat.DeleteCustomBotRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceDeleteCustomBotArgs
	_args.Req = req
	var _result chat.ChatServiceDeleteCustomBotResult
	if err = p.c.Call(ctx, "DeleteCustomBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversationBots(ctx context.Context, req *chat.ListConversationBotsRequest) (r *chat.ListConversationBotsResponse, err error) {
	var _args chat.ChatServiceListConversationBotsArgs
	_args.Req = req
	var _result chat.ChatServiceListConversationBotsResult
	if err = p.c.Call(ctx, "ListConversationBots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddConversationBot(ctx context.Context, req *chat.AddConversationBotRequest) (r *chat.AddConversationBotResponse, err error) {
	var _args chat.ChatServiceAddConversationBotArgs
	_args.Req = req
	var _result chat.ChatServiceAddConversationBotResult
	if err = p.c.Call(ctx, "AddConversationBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveConversationBot(ctx context.Context, req *chat.RemoveConversationBotRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceRemoveConversationBotArgs
	_args.Req = req
	var _result chat.ChatServiceRemoveConversationBotResult
	if err = p.c.Call(ctx, "RemoveConversationBot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAICallLogs(ctx context.Context, req *chat.ListAICallLogsRequest) (r *chat.ListAICallLogsResponse, err error) {
	var _args chat.ChatServiceListAICallLogsArgs
	_args.Req = req
	var _result chat.ChatServiceListAICallLogsResult
	if err = p.c.Call(ctx, "ListAICallLogs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListNotifications(ctx context.Context, req *chat.ListNotificationsRequest) (r *chat.ListNotificationsResponse, err error) {
	var _args chat.ChatServiceListNotificationsArgs
	_args.Req = req
	var _result chat.ChatServiceListNotificationsResult
	if err = p.c.Call(ctx, "ListNotifications", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkNotificationRead(ctx context.Context, req *chat.MarkNotificationReadRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceMarkNotificationReadArgs
	_args.Req = req
	var _result chat.ChatServiceMarkNotificationReadResult
	if err = p.c.Call(ctx, "MarkNotificationRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkAllNotificationsRead(ctx context.Context, req *chat.MarkAllNotificationsReadRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceMarkAllNotificationsReadArgs
	_args.Req = req
	var _result chat.ChatServiceMarkAllNotificationsReadResult
	if err = p.c.Call(ctx, "MarkAllNotificationsRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateNotification(ctx context.Context, req *chat.CreateNotificationRequest) (r *chat.CreateNotificationResponse, err error) {
	var _args chat.ChatServiceCreateNotificationArgs
	_args.Req = req
	var _result chat.ChatServiceCreateNotificationResult
	if err = p.c.Call(ctx, "CreateNotification", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateKnowledgeBase(ctx context.Context, req *chat.CreateKnowledgeBaseRequest) (r *chat.CreateKnowledgeBaseResponse, err error) {
	var _args chat.ChatServiceCreateKnowledgeBaseArgs
	_args.Req = req
	var _result chat.ChatServiceCreateKnowledgeBaseResult
	if err = p.c.Call(ctx, "CreateKnowledgeBase", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListKnowledgeBases(ctx context.Context, req *chat.ListKnowledgeBasesRequest) (r *chat.ListKnowledgeBasesResponse, err error) {
	var _args chat.ChatServiceListKnowledgeBasesArgs
	_args.Req = req
	var _result chat.ChatServiceListKnowledgeBasesResult
	if err = p.c.Call(ctx, "ListKnowledgeBases", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddKnowledgeDocumentText(ctx context.Context, req *chat.AddKnowledgeDocumentTextRequest) (r *chat.AddKnowledgeDocumentTextResponse, err error) {
	var _args chat.ChatServiceAddKnowledgeDocumentTextArgs
	_args.Req = req
	var _result chat.ChatServiceAddKnowledgeDocumentTextResult
	if err = p.c.Call(ctx, "AddKnowledgeDocumentText", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListKnowledgeDocuments(ctx context.Context, req *chat.ListKnowledgeDocumentsRequest) (r *chat.ListKnowledgeDocumentsResponse, err error) {
	var _args chat.ChatServiceListKnowledgeDocumentsArgs
	_args.Req = req
	var _result chat.ChatServiceListKnowledgeDocumentsResult
	if err = p.c.Call(ctx, "ListKnowledgeDocuments", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchKnowledgeBase(ctx context.Context, req *chat.SearchKnowledgeBaseRequest) (r *chat.SearchKnowledgeBaseResponse, err error) {
	var _args chat.ChatServiceSearchKnowledgeBaseArgs
	_args.Req = req
	var _result chat.ChatServiceSearchKnowledgeBaseResult
	if err = p.c.Call(ctx, "SearchKnowledgeBase", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindConversationKnowledgeBase(ctx context.Context, req *chat.BindConversationKnowledgeBaseRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceBindConversationKnowledgeBaseArgs
	_args.Req = req
	var _result chat.ChatServiceBindConversationKnowledgeBaseResult
	if err = p.c.Call(ctx, "BindConversationKnowledgeBase", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversationKnowledgeBases(ctx context.Context, req *chat.ListConversationKnowledgeBasesRequest) (r *chat.ListConversationKnowledgeBasesResponse, err error) {
	var _args chat.ChatServiceListConversationKnowledgeBasesArgs
	_args.Req = req
	var _result chat.ChatServiceListConversationKnowledgeBasesResult
	if err = p.c.Call(ctx, "ListConversationKnowledgeBases", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnbindConversationKnowledgeBase(ctx context.Context, req *chat.UnbindConversationKnowledgeBaseRequest) (r *chat.CommonResponse, err error) {
	var _args chat.ChatServiceUnbindConversationKnowledgeBaseArgs
	_args.Req = req
	var _result chat.ChatServiceUnbindConversationKnowledgeBaseResult
	if err = p.c.Call(ctx, "UnbindConversationKnowledgeBase", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateMessage(ctx context.Context, req *chat.CreateMessageRequest) (r *chat.CreateMessageResponse, err error) {
	var _args chat.ChatServiceCreateMessageArgs
	_args.Req = req
	var _result chat.ChatServiceCreateMessageResult
	if err = p.c.Call(ctx, "CreateMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FindSingleByUsers(ctx context.Context, req *chat.FindSingleByUsersRequest) (r *chat.FindSingleByUsersResponse, err error) {
	var _args chat.ChatServiceFindSingleByUsersArgs
	_args.Req = req
	var _result chat.ChatServiceFindSingleByUsersResult
	if err = p.c.Call(ctx, "FindSingleByUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) WriteUserMemory(ctx context.Context, req *chat.WriteUserMemoryRequest) (r *chat.WriteUserMemoryResponse, err error) {
	var _args chat.ChatServiceWriteUserMemoryArgs
	_args.Req = req
	var _result chat.ChatServiceWriteUserMemoryResult
	if err = p.c.Call(ctx, "WriteUserMemory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListUserMemories(ctx context.Context, req *chat.ListUserMemoriesRequest) (r *chat.ListUserMemoriesResponse, err error) {
	var _args chat.ChatServiceListUserMemoriesArgs
	_args.Req = req
	var _result chat.ChatServiceListUserMemoriesResult
	if err = p.c.Call(ctx, "ListUserMemories", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserMemory(ctx context.Context, req *chat.UpdateUserMemoryRequest) (r *chat.UpdateUserMemoryResponse, err error) {
	var _args chat.ChatServiceUpdateUserMemoryArgs
	_args.Req = req
	var _result chat.ChatServiceUpdateUserMemoryResult
	if err = p.c.Call(ctx, "UpdateUserMemory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
