// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package rag

import (
	"context"
	"fmt"
)

type HealthRequest struct {
}

func NewHealthRequest() *HealthRequest {
	return &HealthRequest{}
}

func (p *HealthRequest) InitDefault() {
}

func (p *HealthRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HealthRequest(%+v)", *p)
}

var fieldIDToName_HealthRequest = map[int16]string{}

type HealthResponse struct {
	Ok bool `thrift:"ok,1" frugal:"1,default,bool" json:"ok"`
}

func NewHealthResponse() *HealthResponse {
	return &HealthResponse{}
}

func (p *HealthResponse) InitDefault() {
}

func (p *HealthResponse) GetOk() (v bool) {
	return p.Ok
}
func (p *HealthResponse) SetOk(val bool) {
	p.Ok = val
}

func (p *HealthResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HealthResponse(%+v)", *p)
}

var fieldIDToName_HealthResponse = map[int16]string{
	1: "ok",
}

type CommonResponse struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewCommonResponse() *CommonResponse {
	return &CommonResponse{}
}

func (p *CommonResponse) InitDefault() {
}

func (p *CommonResponse) GetSuccess() (v bool) {
	return p.Success
}

func (p *CommonResponse) GetMessage() (v string) {
	return p.Message
}
func (p *CommonResponse) SetSuccess(val bool) {
	p.Success = val
}
func (p *CommonResponse) SetMessage(val string) {
	p.Message = val
}

func (p *CommonResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonResponse(%+v)", *p)
}

var fieldIDToName_CommonResponse = map[int16]string{
	1: "success",
	2: "message",
}

type KnowledgeBaseInfo struct {
	KnowledgeBaseId int64  `thrift:"knowledge_base_id,1" frugal:"1,default,i64" json:"knowledge_base_id"`
	Name            string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Description     string `thrift:"description,3" frugal:"3,default,string" json:"description"`
	Status          string `thrift:"status,4" frugal:"4,default,string" json:"status"`
}

func NewKnowledgeBaseInfo() *KnowledgeBaseInfo {
	return &KnowledgeBaseInfo{}
}

func (p *KnowledgeBaseInfo) InitDefault() {
}

func (p *KnowledgeBaseInfo) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}

func (p *KnowledgeBaseInfo) GetName() (v string) {
	return p.Name
}

func (p *KnowledgeBaseInfo) GetDescription() (v string) {
	return p.Description
}

func (p *KnowledgeBaseInfo) GetStatus() (v string) {
	return p.Status
}
func (p *KnowledgeBaseInfo) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}
func (p *KnowledgeBaseInfo) SetName(val string) {
	p.Name = val
}
func (p *KnowledgeBaseInfo) SetDescription(val string) {
	p.Description = val
}
func (p *KnowledgeBaseInfo) SetStatus(val string) {
	p.Status = val
}

func (p *KnowledgeBaseInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeBaseInfo(%+v)", *p)
}

var fieldIDToName_KnowledgeBaseInfo = map[int16]string{
	1: "knowledge_base_id",
	2: "name",
	3: "description",
	4: "status",
}

type KnowledgeDocumentInfo struct {
	DocumentId      int64  `thrift:"document_id,1" frugal:"1,default,i64" json:"document_id"`
	KnowledgeBaseId int64  `thrift:"knowledge_base_id,2" frugal:"2,default,i64" json:"knowledge_base_id"`
	Title           string `thrift:"title,3" frugal:"3,default,string" json:"title"`
	SourceType      string `thrift:"source_type,4" frugal:"4,default,string" json:"source_type"`
	Status          string `thrift:"status,5" frugal:"5,default,string" json:"status"`
	ErrorMessage    string `thrift:"error_message,6" frugal:"6,default,string" json:"error_message"`
	CreatedAt       int64  `thrift:"created_at,7" frugal:"7,default,i64" json:"created_at"`
}

func NewKnowledgeDocumentInfo() *KnowledgeDocumentInfo {
	return &KnowledgeDocumentInfo{}
}

func (p *KnowledgeDocumentInfo) InitDefault() {
}

func (p *KnowledgeDocumentInfo) GetDocumentId() (v int64) {
	return p.DocumentId
}

func (p *KnowledgeDocumentInfo) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}

func (p *KnowledgeDocumentInfo) GetTitle() (v string) {
	return p.Title
}

func (p *KnowledgeDocumentInfo) GetSourceType() (v string) {
	return p.SourceType
}

func (p *KnowledgeDocumentInfo) GetStatus() (v string) {
	return p.Status
}

func (p *KnowledgeDocumentInfo) GetErrorMessage() (v string) {
	return p.ErrorMessage
}

func (p *KnowledgeDocumentInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}
func (p *KnowledgeDocumentInfo) SetDocumentId(val int64) {
	p.DocumentId = val
}
func (p *KnowledgeDocumentInfo) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}
func (p *KnowledgeDocumentInfo) SetTitle(val string) {
	p.Title = val
}
func (p *KnowledgeDocumentInfo) SetSourceType(val string) {
	p.SourceType = val
}
func (p *KnowledgeDocumentInfo) SetStatus(val string) {
	p.Status = val
}
func (p *KnowledgeDocumentInfo) SetErrorMessage(val string) {
	p.ErrorMessage = val
}
func (p *KnowledgeDocumentInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}

func (p *KnowledgeDocumentInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeDocumentInfo(%+v)", *p)
}

var fieldIDToName_KnowledgeDocumentInfo = map[int16]string{
	1: "document_id",
	2: "knowledge_base_id",
	3: "title",
	4: "source_type",
	5: "status",
	6: "error_message",
	7: "created_at",
}

type KnowledgeDocumentChunkInfo struct {
	ChunkId      int64                        `thrift:"chunk_id,1" frugal:"1,default,i64" json:"chunk_id"`
	DocumentId   int64                        `thrift:"document_id,2" frugal:"2,default,i64" json:"document_id"`
	ChunkIndex   int32                        `thrift:"chunk_index,3" frugal:"3,default,i32" json:"chunk_index"`
	Content      string                       `thrift:"content,4" frugal:"4,default,string" json:"content"`
	SectionTitle string                       `thrift:"section_title,5" frugal:"5,default,string" json:"section_title"`
	ChunkType    string                       `thrift:"chunk_type,6" frugal:"6,default,string" json:"chunk_type"`
	PageStart    int32                        `thrift:"page_start,7" frugal:"7,default,i32" json:"page_start"`
	PageEnd      int32                        `thrift:"page_end,8" frugal:"8,default,i32" json:"page_end"`
	CharStart    int32                        `thrift:"char_start,9" frugal:"9,default,i32" json:"char_start"`
	CharEnd      int32                        `thrift:"char_end,10" frugal:"10,default,i32" json:"char_end"`
	Sentences    []*KnowledgeSentenceSpanInfo `thrift:"sentences,11" frugal:"11,default,list<KnowledgeSentenceSpanInfo>" json:"sentences"`
}

func NewKnowledgeDocumentChunkInfo() *KnowledgeDocumentChunkInfo {
	return &KnowledgeDocumentChunkInfo{}
}

func (p *KnowledgeDocumentChunkInfo) InitDefault() {
}

func (p *KnowledgeDocumentChunkInfo) GetChunkId() (v int64) {
	return p.ChunkId
}

func (p *KnowledgeDocumentChunkInfo) GetDocumentId() (v int64) {
	return p.DocumentId
}

func (p *KnowledgeDocumentChunkInfo) GetChunkIndex() (v int32) {
	return p.ChunkIndex
}

func (p *KnowledgeDocumentChunkInfo) GetContent() (v string) {
	return p.Content
}

func (p *KnowledgeDocumentChunkInfo) GetSectionTitle() (v string) {
	return p.SectionTitle
}

func (p *KnowledgeDocumentChunkInfo) GetChunkType() (v string) {
	return p.ChunkType
}

func (p *KnowledgeDocumentChunkInfo) GetPageStart() (v int32) {
	return p.PageStart
}

func (p *KnowledgeDocumentChunkInfo) GetPageEnd() (v int32) {
	return p.PageEnd
}

func (p *KnowledgeDocumentChunkInfo) GetCharStart() (v int32) {
	return p.CharStart
}

func (p *KnowledgeDocumentChunkInfo) GetCharEnd() (v int32) {
	return p.CharEnd
}

func (p *KnowledgeDocumentChunkInfo) GetSentences() (v []*KnowledgeSentenceSpanInfo) {
	return p.Sentences
}
func (p *KnowledgeDocumentChunkInfo) SetChunkId(val int64) {
	p.ChunkId = val
}
func (p *KnowledgeDocumentChunkInfo) SetDocumentId(val int64) {
	p.DocumentId = val
}
func (p *KnowledgeDocumentChunkInfo) SetChunkIndex(val int32) {
	p.ChunkIndex = val
}
func (p *KnowledgeDocumentChunkInfo) SetContent(val string) {
	p.Content = val
}
func (p *KnowledgeDocumentChunkInfo) SetSectionTitle(val string) {
	p.SectionTitle = val
}
func (p *KnowledgeDocumentChunkInfo) SetChunkType(val string) {
	p.ChunkType = val
}
func (p *KnowledgeDocumentChunkInfo) SetPageStart(val int32) {
	p.PageStart = val
}
func (p *KnowledgeDocumentChunkInfo) SetPageEnd(val int32) {
	p.PageEnd = val
}
func (p *KnowledgeDocumentChunkInfo) SetCharStart(val int32) {
	p.CharStart = val
}
func (p *KnowledgeDocumentChunkInfo) SetCharEnd(val int32) {
	p.CharEnd = val
}
func (p *KnowledgeDocumentChunkInfo) SetSentences(val []*KnowledgeSentenceSpanInfo) {
	p.Sentences = val
}

func (p *KnowledgeDocumentChunkInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeDocumentChunkInfo(%+v)", *p)
}

var fieldIDToName_KnowledgeDocumentChunkInfo = map[int16]string{
	1:  "chunk_id",
	2:  "document_id",
	3:  "chunk_index",
	4:  "content",
	5:  "section_title",
	6:  "chunk_type",
	7:  "page_start",
	8:  "page_end",
	9:  "char_start",
	10: "char_end",
	11: "sentences",
}

type KnowledgeSentenceSpanInfo struct {
	SentenceIndex int32  `thrift:"sentence_index,1" frugal:"1,default,i32" json:"sentence_index"`
	Text          string `thrift:"text,2" frugal:"2,default,string" json:"text"`
	PageStart     int32  `thrift:"page_start,3" frugal:"3,default,i32" json:"page_start"`
	PageEnd       int32  `thrift:"page_end,4" frugal:"4,default,i32" json:"page_end"`
	CharStart     int32  `thrift:"char_start,5" frugal:"5,default,i32" json:"char_start"`
	CharEnd       int32  `thrift:"char_end,6" frugal:"6,default,i32" json:"char_end"`
}

func NewKnowledgeSentenceSpanInfo() *KnowledgeSentenceSpanInfo {
	return &KnowledgeSentenceSpanInfo{}
}

func (p *KnowledgeSentenceSpanInfo) InitDefault() {
}

func (p *KnowledgeSentenceSpanInfo) GetSentenceIndex() (v int32) {
	return p.SentenceIndex
}

func (p *KnowledgeSentenceSpanInfo) GetText() (v string) {
	return p.Text
}

func (p *KnowledgeSentenceSpanInfo) GetPageStart() (v int32) {
	return p.PageStart
}

func (p *KnowledgeSentenceSpanInfo) GetPageEnd() (v int32) {
	return p.PageEnd
}

func (p *KnowledgeSentenceSpanInfo) GetCharStart() (v int32) {
	return p.CharStart
}

func (p *KnowledgeSentenceSpanInfo) GetCharEnd() (v int32) {
	return p.CharEnd
}
func (p *KnowledgeSentenceSpanInfo) SetSentenceIndex(val int32) {
	p.SentenceIndex = val
}
func (p *KnowledgeSentenceSpanInfo) SetText(val string) {
	p.Text = val
}
func (p *KnowledgeSentenceSpanInfo) SetPageStart(val int32) {
	p.PageStart = val
}
func (p *KnowledgeSentenceSpanInfo) SetPageEnd(val int32) {
	p.PageEnd = val
}
func (p *KnowledgeSentenceSpanInfo) SetCharStart(val int32) {
	p.CharStart = val
}
func (p *KnowledgeSentenceSpanInfo) SetCharEnd(val int32) {
	p.CharEnd = val
}

func (p *KnowledgeSentenceSpanInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeSentenceSpanInfo(%+v)", *p)
}

var fieldIDToName_KnowledgeSentenceSpanInfo = map[int16]string{
	1: "sentence_index",
	2: "text",
	3: "page_start",
	4: "page_end",
	5: "char_start",
	6: "char_end",
}

type KnowledgeSearchChunkInfo struct {
	ChunkId    int64   `thrift:"chunk_id,1" frugal:"1,default,i64" json:"chunk_id"`
	DocumentId int64   `thrift:"document_id,2" frugal:"2,default,i64" json:"document_id"`
	Score      float64 `thrift:"score,3" frugal:"3,default,double" json:"score"`
	Content    string  `thrift:"content,4" frugal:"4,default,string" json:"content"`
}

func NewKnowledgeSearchChunkInfo() *KnowledgeSearchChunkInfo {
	return &KnowledgeSearchChunkInfo{}
}

func (p *KnowledgeSearchChunkInfo) InitDefault() {
}

func (p *KnowledgeSearchChunkInfo) GetChunkId() (v int64) {
	return p.ChunkId
}

func (p *KnowledgeSearchChunkInfo) GetDocumentId() (v int64) {
	return p.DocumentId
}

func (p *KnowledgeSearchChunkInfo) GetScore() (v float64) {
	return p.Score
}

func (p *KnowledgeSearchChunkInfo) GetContent() (v string) {
	return p.Content
}
func (p *KnowledgeSearchChunkInfo) SetChunkId(val int64) {
	p.ChunkId = val
}
func (p *KnowledgeSearchChunkInfo) SetDocumentId(val int64) {
	p.DocumentId = val
}
func (p *KnowledgeSearchChunkInfo) SetScore(val float64) {
	p.Score = val
}
func (p *KnowledgeSearchChunkInfo) SetContent(val string) {
	p.Content = val
}

func (p *KnowledgeSearchChunkInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeSearchChunkInfo(%+v)", *p)
}

var fieldIDToName_KnowledgeSearchChunkInfo = map[int16]string{
	1: "chunk_id",
	2: "document_id",
	3: "score",
	4: "content",
}

type CreateKnowledgeBaseRequest struct {
	OperatorId  int64  `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	Name        string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Description string `thrift:"description,3" frugal:"3,default,string" json:"description"`
}

func NewCreateKnowledgeBaseRequest() *CreateKnowledgeBaseRequest {
	return &CreateKnowledgeBaseRequest{}
}

func (p *CreateKnowledgeBaseRequest) InitDefault() {
}

func (p *CreateKnowledgeBaseRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *CreateKnowledgeBaseRequest) GetName() (v string) {
	return p.Name
}

func (p *CreateKnowledgeBaseRequest) GetDescription() (v string) {
	return p.Description
}
func (p *CreateKnowledgeBaseRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *CreateKnowledgeBaseRequest) SetName(val string) {
	p.Name = val
}
func (p *CreateKnowledgeBaseRequest) SetDescription(val string) {
	p.Description = val
}

func (p *CreateKnowledgeBaseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateKnowledgeBaseRequest(%+v)", *p)
}

var fieldIDToName_CreateKnowledgeBaseRequest = map[int16]string{
	1: "operator_id",
	2: "name",
	3: "description",
}

type CreateKnowledgeBaseResponse struct {
	KnowledgeBase *KnowledgeBaseInfo `thrift:"knowledge_base,1" frugal:"1,default,KnowledgeBaseInfo" json:"knowledge_base"`
}

func NewCreateKnowledgeBaseResponse() *CreateKnowledgeBaseResponse {
	return &CreateKnowledgeBaseResponse{}
}

func (p *CreateKnowledgeBaseResponse) InitDefault() {
}

var CreateKnowledgeBaseResponse_KnowledgeBase_DEFAULT *KnowledgeBaseInfo

func (p *CreateKnowledgeBaseResponse) GetKnowledgeBase() (v *KnowledgeBaseInfo) {
	if !p.IsSetKnowledgeBase() {
		return CreateKnowledgeBaseResponse_KnowledgeBase_DEFAULT
	}
	return p.KnowledgeBase
}
func (p *CreateKnowledgeBaseResponse) SetKnowledgeBase(val *KnowledgeBaseInfo) {
	p.KnowledgeBase = val
}

func (p *CreateKnowledgeBaseResponse) IsSetKnowledgeBase() bool {
	return p.KnowledgeBase != nil
}

func (p *CreateKnowledgeBaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateKnowledgeBaseResponse(%+v)", *p)
}

var fieldIDToName_CreateKnowledgeBaseResponse = map[int16]string{
	1: "knowledge_base",
}

type ListKnowledgeBasesRequest struct {
	OperatorId int64 `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
}

func NewListKnowledgeBasesRequest() *ListKnowledgeBasesRequest {
	return &ListKnowledgeBasesRequest{}
}

func (p *ListKnowledgeBasesRequest) InitDefault() {
}

func (p *ListKnowledgeBasesRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}
func (p *ListKnowledgeBasesRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}

func (p *ListKnowledgeBasesRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListKnowledgeBasesRequest(%+v)", *p)
}

var fieldIDToName_ListKnowledgeBasesRequest = map[int16]string{
	1: "operator_id",
}

type ListKnowledgeBasesResponse struct {
	KnowledgeBases []*KnowledgeBaseInfo `thrift:"knowledge_bases,1" frugal:"1,default,list<KnowledgeBaseInfo>" json:"knowledge_bases"`
}

func NewListKnowledgeBasesResponse() *ListKnowledgeBasesResponse {
	return &ListKnowledgeBasesResponse{}
}

func (p *ListKnowledgeBasesResponse) InitDefault() {
}

func (p *ListKnowledgeBasesResponse) GetKnowledgeBases() (v []*KnowledgeBaseInfo) {
	return p.KnowledgeBases
}
func (p *ListKnowledgeBasesResponse) SetKnowledgeBases(val []*KnowledgeBaseInfo) {
	p.KnowledgeBases = val
}

func (p *ListKnowledgeBasesResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListKnowledgeBasesResponse(%+v)", *p)
}

var fieldIDToName_ListKnowledgeBasesResponse = map[int16]string{
	1: "knowledge_bases",
}

type AddKnowledgeDocumentTextRequest struct {
	OperatorId      int64  `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	KnowledgeBaseId int64  `thrift:"knowledge_base_id,2" frugal:"2,default,i64" json:"knowledge_base_id"`
	Title           string `thrift:"title,3" frugal:"3,default,string" json:"title"`
	SourceType      string `thrift:"source_type,4" frugal:"4,default,string" json:"source_type"`
	Content         string `thrift:"content,5" frugal:"5,default,string" json:"content"`
}

func NewAddKnowledgeDocumentTextRequest() *AddKnowledgeDocumentTextRequest {
	return &AddKnowledgeDocumentTextRequest{}
}

func (p *AddKnowledgeDocumentTextRequest) InitDefault() {
}

func (p *AddKnowledgeDocumentTextRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *AddKnowledgeDocumentTextRequest) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}

func (p *AddKnowledgeDocumentTextRequest) GetTitle() (v string) {
	return p.Title
}

func (p *AddKnowledgeDocumentTextRequest) GetSourceType() (v string) {
	return p.SourceType
}

func (p *AddKnowledgeDocumentTextRequest) GetContent() (v string) {
	return p.Content
}
func (p *AddKnowledgeDocumentTextRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *AddKnowledgeDocumentTextRequest) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}
func (p *AddKnowledgeDocumentTextRequest) SetTitle(val string) {
	p.Title = val
}
func (p *AddKnowledgeDocumentTextRequest) SetSourceType(val string) {
	p.SourceType = val
}
func (p *AddKnowledgeDocumentTextRequest) SetContent(val string) {
	p.Content = val
}

func (p *AddKnowledgeDocumentTextRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddKnowledgeDocumentTextRequest(%+v)", *p)
}

var fieldIDToName_AddKnowledgeDocumentTextRequest = map[int16]string{
	1: "operator_id",
	2: "knowledge_base_id",
	3: "title",
	4: "source_type",
	5: "content",
}

type AddKnowledgeDocumentTextResponse struct {
	Document *KnowledgeDocumentInfo `thrift:"document,1" frugal:"1,default,KnowledgeDocumentInfo" json:"document"`
}

func NewAddKnowledgeDocumentTextResponse() *AddKnowledgeDocumentTextResponse {
	return &AddKnowledgeDocumentTextResponse{}
}

func (p *AddKnowledgeDocumentTextResponse) InitDefault() {
}

var AddKnowledgeDocumentTextResponse_Document_DEFAULT *KnowledgeDocumentInfo

func (p *AddKnowledgeDocumentTextResponse) GetDocument() (v *KnowledgeDocumentInfo) {
	if !p.IsSetDocument() {
		return AddKnowledgeDocumentTextResponse_Document_DEFAULT
	}
	return p.Document
}
func (p *AddKnowledgeDocumentTextResponse) SetDocument(val *KnowledgeDocumentInfo) {
	p.Document = val
}

func (p *AddKnowledgeDocumentTextResponse) IsSetDocument() bool {
	return p.Document != nil
}

func (p *AddKnowledgeDocumentTextResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddKnowledgeDocumentTextResponse(%+v)", *p)
}

var fieldIDToName_AddKnowledgeDocumentTextResponse = map[int16]string{
	1: "document",
}

type ListKnowledgeDocumentsRequest struct {
	OperatorId      int64 `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	KnowledgeBaseId int64 `thrift:"knowledge_base_id,2" frugal:"2,default,i64" json:"knowledge_base_id"`
}

func NewListKnowledgeDocumentsRequest() *ListKnowledgeDocumentsRequest {
	return &ListKnowledgeDocumentsRequest{}
}

func (p *ListKnowledgeDocumentsRequest) InitDefault() {
}

func (p *ListKnowledgeDocumentsRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *ListKnowledgeDocumentsRequest) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}
func (p *ListKnowledgeDocumentsRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *ListKnowledgeDocumentsRequest) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}

func (p *ListKnowledgeDocumentsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListKnowledgeDocumentsRequest(%+v)", *p)
}

var fieldIDToName_ListKnowledgeDocumentsRequest = map[int16]string{
	1: "operator_id",
	2: "knowledge_base_id",
}

type ListKnowledgeDocumentsResponse struct {
	Documents []*KnowledgeDocumentInfo `thrift:"documents,1" frugal:"1,default,list<KnowledgeDocumentInfo>" json:"documents"`
}

func NewListKnowledgeDocumentsResponse() *ListKnowledgeDocumentsResponse {
	return &ListKnowledgeDocumentsResponse{}
}

func (p *ListKnowledgeDocumentsResponse) InitDefault() {
}

func (p *ListKnowledgeDocumentsResponse) GetDocuments() (v []*KnowledgeDocumentInfo) {
	return p.Documents
}
func (p *ListKnowledgeDocumentsResponse) SetDocuments(val []*KnowledgeDocumentInfo) {
	p.Documents = val
}

func (p *ListKnowledgeDocumentsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListKnowledgeDocumentsResponse(%+v)", *p)
}

var fieldIDToName_ListKnowledgeDocumentsResponse = map[int16]string{
	1: "documents",
}

type ListKnowledgeDocumentChunksRequest struct {
	OperatorId      int64 `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	KnowledgeBaseId int64 `thrift:"knowledge_base_id,2" frugal:"2,default,i64" json:"knowledge_base_id"`
	DocumentId      int64 `thrift:"document_id,3" frugal:"3,default,i64" json:"document_id"`
}

func NewListKnowledgeDocumentChunksRequest() *ListKnowledgeDocumentChunksRequest {
	return &ListKnowledgeDocumentChunksRequest{}
}

func (p *ListKnowledgeDocumentChunksRequest) InitDefault() {
}

func (p *ListKnowledgeDocumentChunksRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *ListKnowledgeDocumentChunksRequest) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}

func (p *ListKnowledgeDocumentChunksRequest) GetDocumentId() (v int64) {
	return p.DocumentId
}
func (p *ListKnowledgeDocumentChunksRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *ListKnowledgeDocumentChunksRequest) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}
func (p *ListKnowledgeDocumentChunksRequest) SetDocumentId(val int64) {
	p.DocumentId = val
}

func (p *ListKnowledgeDocumentChunksRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListKnowledgeDocumentChunksRequest(%+v)", *p)
}

var fieldIDToName_ListKnowledgeDocumentChunksRequest = map[int16]string{
	1: "operator_id",
	2: "knowledge_base_id",
	3: "document_id",
}

type ListKnowledgeDocumentChunksResponse struct {
	Chunks []*KnowledgeDocumentChunkInfo `thrift:"chunks,1" frugal:"1,default,list<KnowledgeDocumentChunkInfo>" json:"chunks"`
}

func NewListKnowledgeDocumentChunksResponse() *ListKnowledgeDocumentChunksResponse {
	return &ListKnowledgeDocumentChunksResponse{}
}

func (p *ListKnowledgeDocumentChunksResponse) InitDefault() {
}

func (p *ListKnowledgeDocumentChunksResponse) GetChunks() (v []*KnowledgeDocumentChunkInfo) {
	return p.Chunks
}
func (p *ListKnowledgeDocumentChunksResponse) SetChunks(val []*KnowledgeDocumentChunkInfo) {
	p.Chunks = val
}

func (p *ListKnowledgeDocumentChunksResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListKnowledgeDocumentChunksResponse(%+v)", *p)
}

var fieldIDToName_ListKnowledgeDocumentChunksResponse = map[int16]string{
	1: "chunks",
}

type DeleteKnowledgeDocumentRequest struct {
	OperatorId      int64 `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	KnowledgeBaseId int64 `thrift:"knowledge_base_id,2" frugal:"2,default,i64" json:"knowledge_base_id"`
	DocumentId      int64 `thrift:"document_id,3" frugal:"3,default,i64" json:"document_id"`
}

func NewDeleteKnowledgeDocumentRequest() *DeleteKnowledgeDocumentRequest {
	return &DeleteKnowledgeDocumentRequest{}
}

func (p *DeleteKnowledgeDocumentRequest) InitDefault() {
}

func (p *DeleteKnowledgeDocumentRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *DeleteKnowledgeDocumentRequest) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}

func (p *DeleteKnowledgeDocumentRequest) GetDocumentId() (v int64) {
	return p.DocumentId
}
func (p *DeleteKnowledgeDocumentRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *DeleteKnowledgeDocumentRequest) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}
func (p *DeleteKnowledgeDocumentRequest) SetDocumentId(val int64) {
	p.DocumentId = val
}

func (p *DeleteKnowledgeDocumentRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteKnowledgeDocumentRequest(%+v)", *p)
}

var fieldIDToName_DeleteKnowledgeDocumentRequest = map[int16]string{
	1: "operator_id",
	2: "knowledge_base_id",
	3: "document_id",
}

type SearchKnowledgeBaseRequest struct {
	OperatorId      int64  `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	KnowledgeBaseId int64  `thrift:"knowledge_base_id,2" frugal:"2,default,i64" json:"knowledge_base_id"`
	Query           string `thrift:"query,3" frugal:"3,default,string" json:"query"`
	TopK            *int32 `thrift:"top_k,4,optional" frugal:"4,optional,i32" json:"top_k,omitempty"`
}

func NewSearchKnowledgeBaseRequest() *SearchKnowledgeBaseRequest {
	return &SearchKnowledgeBaseRequest{}
}

func (p *SearchKnowledgeBaseRequest) InitDefault() {
}

func (p *SearchKnowledgeBaseRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *SearchKnowledgeBaseRequest) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}

func (p *SearchKnowledgeBaseRequest) GetQuery() (v string) {
	return p.Query
}

var SearchKnowledgeBaseRequest_TopK_DEFAULT int32

func (p *SearchKnowledgeBaseRequest) GetTopK() (v int32) {
	if !p.IsSetTopK() {
		return SearchKnowledgeBaseRequest_TopK_DEFAULT
	}
	return *p.TopK
}
func (p *SearchKnowledgeBaseRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *SearchKnowledgeBaseRequest) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}
func (p *SearchKnowledgeBaseRequest) SetQuery(val string) {
	p.Query = val
}
func (p *SearchKnowledgeBaseRequest) SetTopK(val *int32) {
	p.TopK = val
}

func (p *SearchKnowledgeBaseRequest) IsSetTopK() bool {
	return p.TopK != nil
}

func (p *SearchKnowledgeBaseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchKnowledgeBaseRequest(%+v)", *p)
}

var fieldIDToName_SearchKnowledgeBaseRequest = map[int16]string{
	1: "operator_id",
	2: "knowledge_base_id",
	3: "query",
	4: "top_k",
}

type SearchKnowledgeBaseResponse struct {
	Chunks []*KnowledgeSearchChunkInfo `thrift:"chunks,1" frugal:"1,default,list<KnowledgeSearchChunkInfo>" json:"chunks"`
}

func NewSearchKnowledgeBaseResponse() *SearchKnowledgeBaseResponse {
	return &SearchKnowledgeBaseResponse{}
}

func (p *SearchKnowledgeBaseResponse) InitDefault() {
}

func (p *SearchKnowledgeBaseResponse) GetChunks() (v []*KnowledgeSearchChunkInfo) {
	return p.Chunks
}
func (p *SearchKnowledgeBaseResponse) SetChunks(val []*KnowledgeSearchChunkInfo) {
	p.Chunks = val
}

func (p *SearchKnowledgeBaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchKnowledgeBaseResponse(%+v)", *p)
}

var fieldIDToName_SearchKnowledgeBaseResponse = map[int16]string{
	1: "chunks",
}

type ConversationKnowledgeBaseInfo struct {
	Id              int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	ConversationId  string `thrift:"conversation_id,2" frugal:"2,default,string" json:"conversation_id"`
	KnowledgeBaseId int64  `thrift:"knowledge_base_id,3" frugal:"3,default,i64" json:"knowledge_base_id"`
	Name            string `thrift:"name,4" frugal:"4,default,string" json:"name"`
	Description     string `thrift:"description,5" frugal:"5,default,string" json:"description"`
	Status          string `thrift:"status,6" frugal:"6,default,string" json:"status"`
	Enabled         bool   `thrift:"enabled,7" frugal:"7,default,bool" json:"enabled"`
}

func NewConversationKnowledgeBaseInfo() *ConversationKnowledgeBaseInfo {
	return &ConversationKnowledgeBaseInfo{}
}

func (p *ConversationKnowledgeBaseInfo) InitDefault() {
}

func (p *ConversationKnowledgeBaseInfo) GetId() (v int64) {
	return p.Id
}

func (p *ConversationKnowledgeBaseInfo) GetConversationId() (v string) {
	return p.ConversationId
}

func (p *ConversationKnowledgeBaseInfo) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}

func (p *ConversationKnowledgeBaseInfo) GetName() (v string) {
	return p.Name
}

func (p *ConversationKnowledgeBaseInfo) GetDescription() (v string) {
	return p.Description
}

func (p *ConversationKnowledgeBaseInfo) GetStatus() (v string) {
	return p.Status
}

func (p *ConversationKnowledgeBaseInfo) GetEnabled() (v bool) {
	return p.Enabled
}
func (p *ConversationKnowledgeBaseInfo) SetId(val int64) {
	p.Id = val
}
func (p *ConversationKnowledgeBaseInfo) SetConversationId(val string) {
	p.ConversationId = val
}
func (p *ConversationKnowledgeBaseInfo) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}
func (p *ConversationKnowledgeBaseInfo) SetName(val string) {
	p.Name = val
}
func (p *ConversationKnowledgeBaseInfo) SetDescription(val string) {
	p.Description = val
}
func (p *ConversationKnowledgeBaseInfo) SetStatus(val string) {
	p.Status = val
}
func (p *ConversationKnowledgeBaseInfo) SetEnabled(val bool) {
	p.Enabled = val
}

func (p *ConversationKnowledgeBaseInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConversationKnowledgeBaseInfo(%+v)", *p)
}

var fieldIDToName_ConversationKnowledgeBaseInfo = map[int16]string{
	1: "id",
	2: "conversation_id",
	3: "knowledge_base_id",
	4: "name",
	5: "description",
	6: "status",
	7: "enabled",
}

type BindConversationKnowledgeBaseRequest struct {
	OperatorId      int64  `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	ConversationId  string `thrift:"conversation_id,2" frugal:"2,default,string" json:"conversation_id"`
	KnowledgeBaseId int64  `thrift:"knowledge_base_id,3" frugal:"3,default,i64" json:"knowledge_base_id"`
}

func NewBindConversationKnowledgeBaseRequest() *BindConversationKnowledgeBaseRequest {
	return &BindConversationKnowledgeBaseRequest{}
}

func (p *BindConversationKnowledgeBaseRequest) InitDefault() {
}

func (p *BindConversationKnowledgeBaseRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *BindConversationKnowledgeBaseRequest) GetConversationId() (v string) {
	return p.ConversationId
}

func (p *BindConversationKnowledgeBaseRequest) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}
func (p *BindConversationKnowledgeBaseRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *BindConversationKnowledgeBaseRequest) SetConversationId(val string) {
	p.ConversationId = val
}
func (p *BindConversationKnowledgeBaseRequest) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}

func (p *BindConversationKnowledgeBaseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindConversationKnowledgeBaseRequest(%+v)", *p)
}

var fieldIDToName_BindConversationKnowledgeBaseRequest = map[int16]string{
	1: "operator_id",
	2: "conversation_id",
	3: "knowledge_base_id",
}

type ListConversationKnowledgeBasesRequest struct {
	OperatorId     int64  `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	ConversationId string `thrift:"conversation_id,2" frugal:"2,default,string" json:"conversation_id"`
}

func NewListConversationKnowledgeBasesRequest() *ListConversationKnowledgeBasesRequest {
	return &ListConversationKnowledgeBasesRequest{}
}

func (p *ListConversationKnowledgeBasesRequest) InitDefault() {
}

func (p *ListConversationKnowledgeBasesRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *ListConversationKnowledgeBasesRequest) GetConversationId() (v string) {
	return p.ConversationId
}
func (p *ListConversationKnowledgeBasesRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *ListConversationKnowledgeBasesRequest) SetConversationId(val string) {
	p.ConversationId = val
}

func (p *ListConversationKnowledgeBasesRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListConversationKnowledgeBasesRequest(%+v)", *p)
}

var fieldIDToName_ListConversationKnowledgeBasesRequest = map[int16]string{
	1: "operator_id",
	2: "conversation_id",
}

type ListConversationKnowledgeBasesResponse struct {
	KnowledgeBases []*ConversationKnowledgeBaseInfo `thrift:"knowledge_bases,1" frugal:"1,default,list<ConversationKnowledgeBaseInfo>" json:"knowledge_bases"`
}

func NewListConversationKnowledgeBasesResponse() *ListConversationKnowledgeBasesResponse {
	return &ListConversationKnowledgeBasesResponse{}
}

func (p *ListConversationKnowledgeBasesResponse) InitDefault() {
}

func (p *ListConversationKnowledgeBasesResponse) GetKnowledgeBases() (v []*ConversationKnowledgeBaseInfo) {
	return p.KnowledgeBases
}
func (p *ListConversationKnowledgeBasesResponse) SetKnowledgeBases(val []*ConversationKnowledgeBaseInfo) {
	p.KnowledgeBases = val
}

func (p *ListConversationKnowledgeBasesResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListConversationKnowledgeBasesResponse(%+v)", *p)
}

var fieldIDToName_ListConversationKnowledgeBasesResponse = map[int16]string{
	1: "knowledge_bases",
}

type UnbindConversationKnowledgeBaseRequest struct {
	OperatorId      int64  `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	ConversationId  string `thrift:"conversation_id,2" frugal:"2,default,string" json:"conversation_id"`
	KnowledgeBaseId int64  `thrift:"knowledge_base_id,3" frugal:"3,default,i64" json:"knowledge_base_id"`
}

func NewUnbindConversationKnowledgeBaseRequest() *UnbindConversationKnowledgeBaseRequest {
	return &UnbindConversationKnowledgeBaseRequest{}
}

func (p *UnbindConversationKnowledgeBaseRequest) InitDefault() {
}

func (p *UnbindConversationKnowledgeBaseRequest) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *UnbindConversationKnowledgeBaseRequest) GetConversationId() (v string) {
	return p.ConversationId
}

func (p *UnbindConversationKnowledgeBaseRequest) GetKnowledgeBaseId() (v int64) {
	return p.KnowledgeBaseId
}
func (p *UnbindConversationKnowledgeBaseRequest) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *UnbindConversationKnowledgeBaseRequest) SetConversationId(val string) {
	p.ConversationId = val
}
func (p *UnbindConversationKnowledgeBaseRequest) SetKnowledgeBaseId(val int64) {
	p.KnowledgeBaseId = val
}

func (p *UnbindConversationKnowledgeBaseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnbindConversationKnowledgeBaseRequest(%+v)", *p)
}

var fieldIDToName_UnbindConversationKnowledgeBaseRequest = map[int16]string{
	1: "operator_id",
	2: "conversation_id",
	3: "knowledge_base_id",
}

type RAGService interface {
	Health(ctx context.Context, req *HealthRequest) (r *HealthResponse, err error)

	CreateKnowledgeBase(ctx context.Context, req *CreateKnowledgeBaseRequest) (r *CreateKnowledgeBaseResponse, err error)

	ListKnowledgeBases(ctx context.Context, req *ListKnowledgeBasesRequest) (r *ListKnowledgeBasesResponse, err error)

	AddKnowledgeDocumentText(ctx context.Context, req *AddKnowledgeDocumentTextRequest) (r *AddKnowledgeDocumentTextResponse, err error)

	ListKnowledgeDocuments(ctx context.Context, req *ListKnowledgeDocumentsRequest) (r *ListKnowledgeDocumentsResponse, err error)

	ListKnowledgeDocumentChunks(ctx context.Context, req *ListKnowledgeDocumentChunksRequest) (r *ListKnowledgeDocumentChunksResponse, err error)

	DeleteKnowledgeDocument(ctx context.Context, req *DeleteKnowledgeDocumentRequest) (r *CommonResponse, err error)

	SearchKnowledgeBase(ctx context.Context, req *SearchKnowledgeBaseRequest) (r *SearchKnowledgeBaseResponse, err error)

	BindConversationKnowledgeBase(ctx context.Context, req *BindConversationKnowledgeBaseRequest) (r *CommonResponse, err error)

	ListConversationKnowledgeBases(ctx context.Context, req *ListConversationKnowledgeBasesRequest) (r *ListConversationKnowledgeBasesResponse, err error)

	UnbindConversationKnowledgeBase(ctx context.Context, req *UnbindConversationKnowledgeBaseRequest) (r *CommonResponse, err error)
}

type RAGServiceHealthArgs struct {
	Req *HealthRequest `thrift:"req,1" frugal:"1,default,HealthRequest" json:"req"`
}

func NewRAGServiceHealthArgs() *RAGServiceHealthArgs {
	return &RAGServiceHealthArgs{}
}

func (p *RAGServiceHealthArgs) InitDefault() {
}

var RAGServiceHealthArgs_Req_DEFAULT *HealthRequest

func (p *RAGServiceHealthArgs) GetReq() (v *HealthRequest) {
	if !p.IsSetReq() {
		return RAGServiceHealthArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceHealthArgs) SetReq(val *HealthRequest) {
	p.Req = val
}

func (p *RAGServiceHealthArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceHealthArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceHealthArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceHealthArgs = map[int16]string{
	1: "req",
}

type RAGServiceHealthResult struct {
	Success *HealthResponse `thrift:"success,0,optional" frugal:"0,optional,HealthResponse" json:"success,omitempty"`
}

func NewRAGServiceHealthResult() *RAGServiceHealthResult {
	return &RAGServiceHealthResult{}
}

func (p *RAGServiceHealthResult) InitDefault() {
}

var RAGServiceHealthResult_Success_DEFAULT *HealthResponse

func (p *RAGServiceHealthResult) GetSuccess() (v *HealthResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceHealthResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceHealthResult) SetSuccess(x interface{}) {
	p.Success = x.(*HealthResponse)
}

func (p *RAGServiceHealthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceHealthResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceHealthResult(%+v)", *p)
}

var fieldIDToName_RAGServiceHealthResult = map[int16]string{
	0: "success",
}

type RAGServiceCreateKnowledgeBaseArgs struct {
	Req *CreateKnowledgeBaseRequest `thrift:"req,1" frugal:"1,default,CreateKnowledgeBaseRequest" json:"req"`
}

func NewRAGServiceCreateKnowledgeBaseArgs() *RAGServiceCreateKnowledgeBaseArgs {
	return &RAGServiceCreateKnowledgeBaseArgs{}
}

func (p *RAGServiceCreateKnowledgeBaseArgs) InitDefault() {
}

var RAGServiceCreateKnowledgeBaseArgs_Req_DEFAULT *CreateKnowledgeBaseRequest

func (p *RAGServiceCreateKnowledgeBaseArgs) GetReq() (v *CreateKnowledgeBaseRequest) {
	if !p.IsSetReq() {
		return RAGServiceCreateKnowledgeBaseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceCreateKnowledgeBaseArgs) SetReq(val *CreateKnowledgeBaseRequest) {
	p.Req = val
}

func (p *RAGServiceCreateKnowledgeBaseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceCreateKnowledgeBaseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceCreateKnowledgeBaseArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceCreateKnowledgeBaseArgs = map[int16]string{
	1: "req",
}

type RAGServiceCreateKnowledgeBaseResult struct {
	Success *CreateKnowledgeBaseResponse `thrift:"success,0,optional" frugal:"0,optional,CreateKnowledgeBaseResponse" json:"success,omitempty"`
}

func NewRAGServiceCreateKnowledgeBaseResult() *RAGServiceCreateKnowledgeBaseResult {
	return &RAGServiceCreateKnowledgeBaseResult{}
}

func (p *RAGServiceCreateKnowledgeBaseResult) InitDefault() {
}

var RAGServiceCreateKnowledgeBaseResult_Success_DEFAULT *CreateKnowledgeBaseResponse

func (p *RAGServiceCreateKnowledgeBaseResult) GetSuccess() (v *CreateKnowledgeBaseResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceCreateKnowledgeBaseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceCreateKnowledgeBaseResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateKnowledgeBaseResponse)
}

func (p *RAGServiceCreateKnowledgeBaseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceCreateKnowledgeBaseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceCreateKnowledgeBaseResult(%+v)", *p)
}

var fieldIDToName_RAGServiceCreateKnowledgeBaseResult = map[int16]string{
	0: "success",
}

type RAGServiceListKnowledgeBasesArgs struct {
	Req *ListKnowledgeBasesRequest `thrift:"req,1" frugal:"1,default,ListKnowledgeBasesRequest" json:"req"`
}

func NewRAGServiceListKnowledgeBasesArgs() *RAGServiceListKnowledgeBasesArgs {
	return &RAGServiceListKnowledgeBasesArgs{}
}

func (p *RAGServiceListKnowledgeBasesArgs) InitDefault() {
}

var RAGServiceListKnowledgeBasesArgs_Req_DEFAULT *ListKnowledgeBasesRequest

func (p *RAGServiceListKnowledgeBasesArgs) GetReq() (v *ListKnowledgeBasesRequest) {
	if !p.IsSetReq() {
		return RAGServiceListKnowledgeBasesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceListKnowledgeBasesArgs) SetReq(val *ListKnowledgeBasesRequest) {
	p.Req = val
}

func (p *RAGServiceListKnowledgeBasesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceListKnowledgeBasesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListKnowledgeBasesArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceListKnowledgeBasesArgs = map[int16]string{
	1: "req",
}

type RAGServiceListKnowledgeBasesResult struct {
	Success *ListKnowledgeBasesResponse `thrift:"success,0,optional" frugal:"0,optional,ListKnowledgeBasesResponse" json:"success,omitempty"`
}

func NewRAGServiceListKnowledgeBasesResult() *RAGServiceListKnowledgeBasesResult {
	return &RAGServiceListKnowledgeBasesResult{}
}

func (p *RAGServiceListKnowledgeBasesResult) InitDefault() {
}

var RAGServiceListKnowledgeBasesResult_Success_DEFAULT *ListKnowledgeBasesResponse

func (p *RAGServiceListKnowledgeBasesResult) GetSuccess() (v *ListKnowledgeBasesResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceListKnowledgeBasesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceListKnowledgeBasesResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListKnowledgeBasesResponse)
}

func (p *RAGServiceListKnowledgeBasesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceListKnowledgeBasesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListKnowledgeBasesResult(%+v)", *p)
}

var fieldIDToName_RAGServiceListKnowledgeBasesResult = map[int16]string{
	0: "success",
}

type RAGServiceAddKnowledgeDocumentTextArgs struct {
	Req *AddKnowledgeDocumentTextRequest `thrift:"req,1" frugal:"1,default,AddKnowledgeDocumentTextRequest" json:"req"`
}

func NewRAGServiceAddKnowledgeDocumentTextArgs() *RAGServiceAddKnowledgeDocumentTextArgs {
	return &RAGServiceAddKnowledgeDocumentTextArgs{}
}

func (p *RAGServiceAddKnowledgeDocumentTextArgs) InitDefault() {
}

var RAGServiceAddKnowledgeDocumentTextArgs_Req_DEFAULT *AddKnowledgeDocumentTextRequest

func (p *RAGServiceAddKnowledgeDocumentTextArgs) GetReq() (v *AddKnowledgeDocumentTextRequest) {
	if !p.IsSetReq() {
		return RAGServiceAddKnowledgeDocumentTextArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceAddKnowledgeDocumentTextArgs) SetReq(val *AddKnowledgeDocumentTextRequest) {
	p.Req = val
}

func (p *RAGServiceAddKnowledgeDocumentTextArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceAddKnowledgeDocumentTextArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceAddKnowledgeDocumentTextArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceAddKnowledgeDocumentTextArgs = map[int16]string{
	1: "req",
}

type RAGServiceAddKnowledgeDocumentTextResult struct {
	Success *AddKnowledgeDocumentTextResponse `thrift:"success,0,optional" frugal:"0,optional,AddKnowledgeDocumentTextResponse" json:"success,omitempty"`
}

func NewRAGServiceAddKnowledgeDocumentTextResult() *RAGServiceAddKnowledgeDocumentTextResult {
	return &RAGServiceAddKnowledgeDocumentTextResult{}
}

func (p *RAGServiceAddKnowledgeDocumentTextResult) InitDefault() {
}

var RAGServiceAddKnowledgeDocumentTextResult_Success_DEFAULT *AddKnowledgeDocumentTextResponse

func (p *RAGServiceAddKnowledgeDocumentTextResult) GetSuccess() (v *AddKnowledgeDocumentTextResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceAddKnowledgeDocumentTextResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceAddKnowledgeDocumentTextResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddKnowledgeDocumentTextResponse)
}

func (p *RAGServiceAddKnowledgeDocumentTextResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceAddKnowledgeDocumentTextResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceAddKnowledgeDocumentTextResult(%+v)", *p)
}

var fieldIDToName_RAGServiceAddKnowledgeDocumentTextResult = map[int16]string{
	0: "success",
}

type RAGServiceListKnowledgeDocumentsArgs struct {
	Req *ListKnowledgeDocumentsRequest `thrift:"req,1" frugal:"1,default,ListKnowledgeDocumentsRequest" json:"req"`
}

func NewRAGServiceListKnowledgeDocumentsArgs() *RAGServiceListKnowledgeDocumentsArgs {
	return &RAGServiceListKnowledgeDocumentsArgs{}
}

func (p *RAGServiceListKnowledgeDocumentsArgs) InitDefault() {
}

var RAGServiceListKnowledgeDocumentsArgs_Req_DEFAULT *ListKnowledgeDocumentsRequest

func (p *RAGServiceListKnowledgeDocumentsArgs) GetReq() (v *ListKnowledgeDocumentsRequest) {
	if !p.IsSetReq() {
		return RAGServiceListKnowledgeDocumentsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceListKnowledgeDocumentsArgs) SetReq(val *ListKnowledgeDocumentsRequest) {
	p.Req = val
}

func (p *RAGServiceListKnowledgeDocumentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceListKnowledgeDocumentsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListKnowledgeDocumentsArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceListKnowledgeDocumentsArgs = map[int16]string{
	1: "req",
}

type RAGServiceListKnowledgeDocumentsResult struct {
	Success *ListKnowledgeDocumentsResponse `thrift:"success,0,optional" frugal:"0,optional,ListKnowledgeDocumentsResponse" json:"success,omitempty"`
}

func NewRAGServiceListKnowledgeDocumentsResult() *RAGServiceListKnowledgeDocumentsResult {
	return &RAGServiceListKnowledgeDocumentsResult{}
}

func (p *RAGServiceListKnowledgeDocumentsResult) InitDefault() {
}

var RAGServiceListKnowledgeDocumentsResult_Success_DEFAULT *ListKnowledgeDocumentsResponse

func (p *RAGServiceListKnowledgeDocumentsResult) GetSuccess() (v *ListKnowledgeDocumentsResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceListKnowledgeDocumentsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceListKnowledgeDocumentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListKnowledgeDocumentsResponse)
}

func (p *RAGServiceListKnowledgeDocumentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceListKnowledgeDocumentsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListKnowledgeDocumentsResult(%+v)", *p)
}

var fieldIDToName_RAGServiceListKnowledgeDocumentsResult = map[int16]string{
	0: "success",
}

type RAGServiceListKnowledgeDocumentChunksArgs struct {
	Req *ListKnowledgeDocumentChunksRequest `thrift:"req,1" frugal:"1,default,ListKnowledgeDocumentChunksRequest" json:"req"`
}

func NewRAGServiceListKnowledgeDocumentChunksArgs() *RAGServiceListKnowledgeDocumentChunksArgs {
	return &RAGServiceListKnowledgeDocumentChunksArgs{}
}

func (p *RAGServiceListKnowledgeDocumentChunksArgs) InitDefault() {
}

var RAGServiceListKnowledgeDocumentChunksArgs_Req_DEFAULT *ListKnowledgeDocumentChunksRequest

func (p *RAGServiceListKnowledgeDocumentChunksArgs) GetReq() (v *ListKnowledgeDocumentChunksRequest) {
	if !p.IsSetReq() {
		return RAGServiceListKnowledgeDocumentChunksArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceListKnowledgeDocumentChunksArgs) SetReq(val *ListKnowledgeDocumentChunksRequest) {
	p.Req = val
}

func (p *RAGServiceListKnowledgeDocumentChunksArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceListKnowledgeDocumentChunksArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListKnowledgeDocumentChunksArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceListKnowledgeDocumentChunksArgs = map[int16]string{
	1: "req",
}

type RAGServiceListKnowledgeDocumentChunksResult struct {
	Success *ListKnowledgeDocumentChunksResponse `thrift:"success,0,optional" frugal:"0,optional,ListKnowledgeDocumentChunksResponse" json:"success,omitempty"`
}

func NewRAGServiceListKnowledgeDocumentChunksResult() *RAGServiceListKnowledgeDocumentChunksResult {
	return &RAGServiceListKnowledgeDocumentChunksResult{}
}

func (p *RAGServiceListKnowledgeDocumentChunksResult) InitDefault() {
}

var RAGServiceListKnowledgeDocumentChunksResult_Success_DEFAULT *ListKnowledgeDocumentChunksResponse

func (p *RAGServiceListKnowledgeDocumentChunksResult) GetSuccess() (v *ListKnowledgeDocumentChunksResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceListKnowledgeDocumentChunksResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceListKnowledgeDocumentChunksResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListKnowledgeDocumentChunksResponse)
}

func (p *RAGServiceListKnowledgeDocumentChunksResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceListKnowledgeDocumentChunksResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListKnowledgeDocumentChunksResult(%+v)", *p)
}

var fieldIDToName_RAGServiceListKnowledgeDocumentChunksResult = map[int16]string{
	0: "success",
}

type RAGServiceDeleteKnowledgeDocumentArgs struct {
	Req *DeleteKnowledgeDocumentRequest `thrift:"req,1" frugal:"1,default,DeleteKnowledgeDocumentRequest" json:"req"`
}

func NewRAGServiceDeleteKnowledgeDocumentArgs() *RAGServiceDeleteKnowledgeDocumentArgs {
	return &RAGServiceDeleteKnowledgeDocumentArgs{}
}

func (p *RAGServiceDeleteKnowledgeDocumentArgs) InitDefault() {
}

var RAGServiceDeleteKnowledgeDocumentArgs_Req_DEFAULT *DeleteKnowledgeDocumentRequest

func (p *RAGServiceDeleteKnowledgeDocumentArgs) GetReq() (v *DeleteKnowledgeDocumentRequest) {
	if !p.IsSetReq() {
		return RAGServiceDeleteKnowledgeDocumentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceDeleteKnowledgeDocumentArgs) SetReq(val *DeleteKnowledgeDocumentRequest) {
	p.Req = val
}

func (p *RAGServiceDeleteKnowledgeDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceDeleteKnowledgeDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceDeleteKnowledgeDocumentArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceDeleteKnowledgeDocumentArgs = map[int16]string{
	1: "req",
}

type RAGServiceDeleteKnowledgeDocumentResult struct {
	Success *CommonResponse `thrift:"success,0,optional" frugal:"0,optional,CommonResponse" json:"success,omitempty"`
}

func NewRAGServiceDeleteKnowledgeDocumentResult() *RAGServiceDeleteKnowledgeDocumentResult {
	return &RAGServiceDeleteKnowledgeDocumentResult{}
}

func (p *RAGServiceDeleteKnowledgeDocumentResult) InitDefault() {
}

var RAGServiceDeleteKnowledgeDocumentResult_Success_DEFAULT *CommonResponse

func (p *RAGServiceDeleteKnowledgeDocumentResult) GetSuccess() (v *CommonResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceDeleteKnowledgeDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceDeleteKnowledgeDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonResponse)
}

func (p *RAGServiceDeleteKnowledgeDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceDeleteKnowledgeDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceDeleteKnowledgeDocumentResult(%+v)", *p)
}

var fieldIDToName_RAGServiceDeleteKnowledgeDocumentResult = map[int16]string{
	0: "success",
}

type RAGServiceSearchKnowledgeBaseArgs struct {
	Req *SearchKnowledgeBaseRequest `thrift:"req,1" frugal:"1,default,SearchKnowledgeBaseRequest" json:"req"`
}

func NewRAGServiceSearchKnowledgeBaseArgs() *RAGServiceSearchKnowledgeBaseArgs {
	return &RAGServiceSearchKnowledgeBaseArgs{}
}

func (p *RAGServiceSearchKnowledgeBaseArgs) InitDefault() {
}

var RAGServiceSearchKnowledgeBaseArgs_Req_DEFAULT *SearchKnowledgeBaseRequest

func (p *RAGServiceSearchKnowledgeBaseArgs) GetReq() (v *SearchKnowledgeBaseRequest) {
	if !p.IsSetReq() {
		return RAGServiceSearchKnowledgeBaseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceSearchKnowledgeBaseArgs) SetReq(val *SearchKnowledgeBaseRequest) {
	p.Req = val
}

func (p *RAGServiceSearchKnowledgeBaseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceSearchKnowledgeBaseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceSearchKnowledgeBaseArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceSearchKnowledgeBaseArgs = map[int16]string{
	1: "req",
}

type RAGServiceSearchKnowledgeBaseResult struct {
	Success *SearchKnowledgeBaseResponse `thrift:"success,0,optional" frugal:"0,optional,SearchKnowledgeBaseResponse" json:"success,omitempty"`
}

func NewRAGServiceSearchKnowledgeBaseResult() *RAGServiceSearchKnowledgeBaseResult {
	return &RAGServiceSearchKnowledgeBaseResult{}
}

func (p *RAGServiceSearchKnowledgeBaseResult) InitDefault() {
}

var RAGServiceSearchKnowledgeBaseResult_Success_DEFAULT *SearchKnowledgeBaseResponse

func (p *RAGServiceSearchKnowledgeBaseResult) GetSuccess() (v *SearchKnowledgeBaseResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceSearchKnowledgeBaseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceSearchKnowledgeBaseResult) SetSuccess(x interface{}) {
	p.Success = x.(*SearchKnowledgeBaseResponse)
}

func (p *RAGServiceSearchKnowledgeBaseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceSearchKnowledgeBaseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceSearchKnowledgeBaseResult(%+v)", *p)
}

var fieldIDToName_RAGServiceSearchKnowledgeBaseResult = map[int16]string{
	0: "success",
}

type RAGServiceBindConversationKnowledgeBaseArgs struct {
	Req *BindConversationKnowledgeBaseRequest `thrift:"req,1" frugal:"1,default,BindConversationKnowledgeBaseRequest" json:"req"`
}

func NewRAGServiceBindConversationKnowledgeBaseArgs() *RAGServiceBindConversationKnowledgeBaseArgs {
	return &RAGServiceBindConversationKnowledgeBaseArgs{}
}

func (p *RAGServiceBindConversationKnowledgeBaseArgs) InitDefault() {
}

var RAGServiceBindConversationKnowledgeBaseArgs_Req_DEFAULT *BindConversationKnowledgeBaseRequest

func (p *RAGServiceBindConversationKnowledgeBaseArgs) GetReq() (v *BindConversationKnowledgeBaseRequest) {
	if !p.IsSetReq() {
		return RAGServiceBindConversationKnowledgeBaseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceBindConversationKnowledgeBaseArgs) SetReq(val *BindConversationKnowledgeBaseRequest) {
	p.Req = val
}

func (p *RAGServiceBindConversationKnowledgeBaseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceBindConversationKnowledgeBaseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceBindConversationKnowledgeBaseArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceBindConversationKnowledgeBaseArgs = map[int16]string{
	1: "req",
}

type RAGServiceBindConversationKnowledgeBaseResult struct {
	Success *CommonResponse `thrift:"success,0,optional" frugal:"0,optional,CommonResponse" json:"success,omitempty"`
}

func NewRAGServiceBindConversationKnowledgeBaseResult() *RAGServiceBindConversationKnowledgeBaseResult {
	return &RAGServiceBindConversationKnowledgeBaseResult{}
}

func (p *RAGServiceBindConversationKnowledgeBaseResult) InitDefault() {
}

var RAGServiceBindConversationKnowledgeBaseResult_Success_DEFAULT *CommonResponse

func (p *RAGServiceBindConversationKnowledgeBaseResult) GetSuccess() (v *CommonResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceBindConversationKnowledgeBaseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceBindConversationKnowledgeBaseResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonResponse)
}

func (p *RAGServiceBindConversationKnowledgeBaseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceBindConversationKnowledgeBaseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceBindConversationKnowledgeBaseResult(%+v)", *p)
}

var fieldIDToName_RAGServiceBindConversationKnowledgeBaseResult = map[int16]string{
	0: "success",
}

type RAGServiceListConversationKnowledgeBasesArgs struct {
	Req *ListConversationKnowledgeBasesRequest `thrift:"req,1" frugal:"1,default,ListConversationKnowledgeBasesRequest" json:"req"`
}

func NewRAGServiceListConversationKnowledgeBasesArgs() *RAGServiceListConversationKnowledgeBasesArgs {
	return &RAGServiceListConversationKnowledgeBasesArgs{}
}

func (p *RAGServiceListConversationKnowledgeBasesArgs) InitDefault() {
}

var RAGServiceListConversationKnowledgeBasesArgs_Req_DEFAULT *ListConversationKnowledgeBasesRequest

func (p *RAGServiceListConversationKnowledgeBasesArgs) GetReq() (v *ListConversationKnowledgeBasesRequest) {
	if !p.IsSetReq() {
		return RAGServiceListConversationKnowledgeBasesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceListConversationKnowledgeBasesArgs) SetReq(val *ListConversationKnowledgeBasesRequest) {
	p.Req = val
}

func (p *RAGServiceListConversationKnowledgeBasesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceListConversationKnowledgeBasesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListConversationKnowledgeBasesArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceListConversationKnowledgeBasesArgs = map[int16]string{
	1: "req",
}

type RAGServiceListConversationKnowledgeBasesResult struct {
	Success *ListConversationKnowledgeBasesResponse `thrift:"success,0,optional" frugal:"0,optional,ListConversationKnowledgeBasesResponse" json:"success,omitempty"`
}

func NewRAGServiceListConversationKnowledgeBasesResult() *RAGServiceListConversationKnowledgeBasesResult {
	return &RAGServiceListConversationKnowledgeBasesResult{}
}

func (p *RAGServiceListConversationKnowledgeBasesResult) InitDefault() {
}

var RAGServiceListConversationKnowledgeBasesResult_Success_DEFAULT *ListConversationKnowledgeBasesResponse

func (p *RAGServiceListConversationKnowledgeBasesResult) GetSuccess() (v *ListConversationKnowledgeBasesResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceListConversationKnowledgeBasesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceListConversationKnowledgeBasesResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListConversationKnowledgeBasesResponse)
}

func (p *RAGServiceListConversationKnowledgeBasesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceListConversationKnowledgeBasesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceListConversationKnowledgeBasesResult(%+v)", *p)
}

var fieldIDToName_RAGServiceListConversationKnowledgeBasesResult = map[int16]string{
	0: "success",
}

type RAGServiceUnbindConversationKnowledgeBaseArgs struct {
	Req *UnbindConversationKnowledgeBaseRequest `thrift:"req,1" frugal:"1,default,UnbindConversationKnowledgeBaseRequest" json:"req"`
}

func NewRAGServiceUnbindConversationKnowledgeBaseArgs() *RAGServiceUnbindConversationKnowledgeBaseArgs {
	return &RAGServiceUnbindConversationKnowledgeBaseArgs{}
}

func (p *RAGServiceUnbindConversationKnowledgeBaseArgs) InitDefault() {
}

var RAGServiceUnbindConversationKnowledgeBaseArgs_Req_DEFAULT *UnbindConversationKnowledgeBaseRequest

func (p *RAGServiceUnbindConversationKnowledgeBaseArgs) GetReq() (v *UnbindConversationKnowledgeBaseRequest) {
	if !p.IsSetReq() {
		return RAGServiceUnbindConversationKnowledgeBaseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RAGServiceUnbindConversationKnowledgeBaseArgs) SetReq(val *UnbindConversationKnowledgeBaseRequest) {
	p.Req = val
}

func (p *RAGServiceUnbindConversationKnowledgeBaseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RAGServiceUnbindConversationKnowledgeBaseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceUnbindConversationKnowledgeBaseArgs(%+v)", *p)
}

var fieldIDToName_RAGServiceUnbindConversationKnowledgeBaseArgs = map[int16]string{
	1: "req",
}

type RAGServiceUnbindConversationKnowledgeBaseResult struct {
	Success *CommonResponse `thrift:"success,0,optional" frugal:"0,optional,CommonResponse" json:"success,omitempty"`
}

func NewRAGServiceUnbindConversationKnowledgeBaseResult() *RAGServiceUnbindConversationKnowledgeBaseResult {
	return &RAGServiceUnbindConversationKnowledgeBaseResult{}
}

func (p *RAGServiceUnbindConversationKnowledgeBaseResult) InitDefault() {
}

var RAGServiceUnbindConversationKnowledgeBaseResult_Success_DEFAULT *CommonResponse

func (p *RAGServiceUnbindConversationKnowledgeBaseResult) GetSuccess() (v *CommonResponse) {
	if !p.IsSetSuccess() {
		return RAGServiceUnbindConversationKnowledgeBaseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RAGServiceUnbindConversationKnowledgeBaseResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonResponse)
}

func (p *RAGServiceUnbindConversationKnowledgeBaseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RAGServiceUnbindConversationKnowledgeBaseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RAGServiceUnbindConversationKnowledgeBaseResult(%+v)", *p)
}

var fieldIDToName_RAGServiceUnbindConversationKnowledgeBaseResult = map[int16]string{
	0: "success",
}
