// Code generated by Kitex v0.16.1. DO NOT EDIT.

package userservice

import (
	"context"
	user "example.com/aim/gateway/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateUser(ctx context.Context, req *user.CreateUserRequest, callOptions ...callopt.Option) (r *user.CreateUserResponse, err error)
	GetUser(ctx context.Context, req *user.GetUserRequest, callOptions ...callopt.Option) (r *user.GetUserResponse, err error)
	GetUserByAimID(ctx context.Context, req *user.GetUserByAimIDRequest, callOptions ...callopt.Option) (r *user.GetUserByAimIDResponse, err error)
	VerifyCredential(ctx context.Context, req *user.VerifyCredentialRequest, callOptions ...callopt.Option) (r *user.VerifyCredentialResponse, err error)
	CheckPassword(ctx context.Context, req *user.CheckPasswordRequest, callOptions ...callopt.Option) (r *user.CheckPasswordResponse, err error)
	UpdateLoginState(ctx context.Context, req *user.UpdateLoginStateRequest, callOptions ...callopt.Option) (r *user.CommonResponse, err error)
	BumpTokenVersion(ctx context.Context, req *user.BumpTokenVersionRequest, callOptions ...callopt.Option) (r *user.CommonResponse, err error)
	UpdateAvatar(ctx context.Context, req *user.UpdateAvatarRequest, callOptions ...callopt.Option) (r *user.UpdateAvatarResponse, err error)
	CreateFriendGroup(ctx context.Context, req *user.CreateFriendGroupRequest, callOptions ...callopt.Option) (r *user.CreateFriendGroupResponse, err error)
	ListFriendGroups(ctx context.Context, req *user.ListFriendGroupsRequest, callOptions ...callopt.Option) (r *user.ListFriendGroupsResponse, err error)
	AddFriend(ctx context.Context, req *user.AddFriendRequest, callOptions ...callopt.Option) (r *user.AddFriendResponse, err error)
	ListFriends(ctx context.Context, req *user.ListFriendsRequest, callOptions ...callopt.Option) (r *user.ListFriendsResponse, err error)
	CheckFriendRelation(ctx context.Context, req *user.CheckFriendRelationRequest, callOptions ...callopt.Option) (r *user.CheckFriendRelationResponse, err error)
	UpdateFriend(ctx context.Context, req *user.UpdateFriendRequest, callOptions ...callopt.Option) (r *user.UpdateFriendResponse, err error)
	DeleteFriend(ctx context.Context, req *user.DeleteFriendRequest, callOptions ...callopt.Option) (r *user.CommonResponse, err error)
	ListFriendRequests(ctx context.Context, req *user.ListFriendRequestsRequest, callOptions ...callopt.Option) (r *user.ListFriendRequestsResponse, err error)
	RespondFriendRequest(ctx context.Context, req *user.RespondFriendRequestRequest, callOptions ...callopt.Option) (r *user.RespondFriendRequestResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) CreateUser(ctx context.Context, req *user.CreateUserRequest, callOptions ...callopt.Option) (r *user.CreateUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, req)
}

func (p *kUserServiceClient) GetUser(ctx context.Context, req *user.GetUserRequest, callOptions ...callopt.Option) (r *user.GetUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, req)
}

func (p *kUserServiceClient) GetUserByAimID(ctx context.Context, req *user.GetUserByAimIDRequest, callOptions ...callopt.Option) (r *user.GetUserByAimIDResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserByAimID(ctx, req)
}

func (p *kUserServiceClient) VerifyCredential(ctx context.Context, req *user.VerifyCredentialRequest, callOptions ...callopt.Option) (r *user.VerifyCredentialResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyCredential(ctx, req)
}

func (p *kUserServiceClient) CheckPassword(ctx context.Context, req *user.CheckPasswordRequest, callOptions ...callopt.Option) (r *user.CheckPasswordResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckPassword(ctx, req)
}

func (p *kUserServiceClient) UpdateLoginState(ctx context.Context, req *user.UpdateLoginStateRequest, callOptions ...callopt.Option) (r *user.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateLoginState(ctx, req)
}

func (p *kUserServiceClient) BumpTokenVersion(ctx context.Context, req *user.BumpTokenVersionRequest, callOptions ...callopt.Option) (r *user.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BumpTokenVersion(ctx, req)
}

func (p *kUserServiceClient) UpdateAvatar(ctx context.Context, req *user.UpdateAvatarRequest, callOptions ...callopt.Option) (r *user.UpdateAvatarResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAvatar(ctx, req)
}

func (p *kUserServiceClient) CreateFriendGroup(ctx context.Context, req *user.CreateFriendGroupRequest, callOptions ...callopt.Option) (r *user.CreateFriendGroupResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateFriendGroup(ctx, req)
}

func (p *kUserServiceClient) ListFriendGroups(ctx context.Context, req *user.ListFriendGroupsRequest, callOptions ...callopt.Option) (r *user.ListFriendGroupsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriendGroups(ctx, req)
}

func (p *kUserServiceClient) AddFriend(ctx context.Context, req *user.AddFriendRequest, callOptions ...callopt.Option) (r *user.AddFriendResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddFriend(ctx, req)
}

func (p *kUserServiceClient) ListFriends(ctx context.Context, req *user.ListFriendsRequest, callOptions ...callopt.Option) (r *user.ListFriendsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriends(ctx, req)
}

func (p *kUserServiceClient) CheckFriendRelation(ctx context.Context, req *user.CheckFriendRelationRequest, callOptions ...callopt.Option) (r *user.CheckFriendRelationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckFriendRelation(ctx, req)
}

func (p *kUserServiceClient) UpdateFriend(ctx context.Context, req *user.UpdateFriendRequest, callOptions ...callopt.Option) (r *user.UpdateFriendResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateFriend(ctx, req)
}

func (p *kUserServiceClient) DeleteFriend(ctx context.Context, req *user.DeleteFriendRequest, callOptions ...callopt.Option) (r *user.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFriend(ctx, req)
}

func (p *kUserServiceClient) ListFriendRequests(ctx context.Context, req *user.ListFriendRequestsRequest, callOptions ...callopt.Option) (r *user.ListFriendRequestsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriendRequests(ctx, req)
}

func (p *kUserServiceClient) RespondFriendRequest(ctx context.Context, req *user.RespondFriendRequestRequest, callOptions ...callopt.Option) (r *user.RespondFriendRequestResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RespondFriendRequest(ctx, req)
}
