// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type UserInfo struct {
	UserId       int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	AimId        string `thrift:"aim_id,2" frugal:"2,default,string" json:"aim_id"`
	Email        string `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Nickname     string `thrift:"nickname,4" frugal:"4,default,string" json:"nickname"`
	Avatar       string `thrift:"avatar,5" frugal:"5,default,string" json:"avatar"`
	Status       string `thrift:"status,6" frugal:"6,default,string" json:"status"`
	Role         string `thrift:"role,7" frugal:"7,default,string" json:"role"`
	TokenVersion int64  `thrift:"token_version,8" frugal:"8,default,i64" json:"token_version"`
	CreatedAt    int64  `thrift:"created_at,9" frugal:"9,default,i64" json:"created_at"`
	UpdatedAt    int64  `thrift:"updated_at,10" frugal:"10,default,i64" json:"updated_at"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserInfo) GetAimId() (v string) {
	return p.AimId
}

func (p *UserInfo) GetEmail() (v string) {
	return p.Email
}

func (p *UserInfo) GetNickname() (v string) {
	return p.Nickname
}

func (p *UserInfo) GetAvatar() (v string) {
	return p.Avatar
}

func (p *UserInfo) GetStatus() (v string) {
	return p.Status
}

func (p *UserInfo) GetRole() (v string) {
	return p.Role
}

func (p *UserInfo) GetTokenVersion() (v int64) {
	return p.TokenVersion
}

func (p *UserInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *UserInfo) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}
func (p *UserInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserInfo) SetAimId(val string) {
	p.AimId = val
}
func (p *UserInfo) SetEmail(val string) {
	p.Email = val
}
func (p *UserInfo) SetNickname(val string) {
	p.Nickname = val
}
func (p *UserInfo) SetAvatar(val string) {
	p.Avatar = val
}
func (p *UserInfo) SetStatus(val string) {
	p.Status = val
}
func (p *UserInfo) SetRole(val string) {
	p.Role = val
}
func (p *UserInfo) SetTokenVersion(val int64) {
	p.TokenVersion = val
}
func (p *UserInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *UserInfo) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1:  "user_id",
	2:  "aim_id",
	3:  "email",
	4:  "nickname",
	5:  "avatar",
	6:  "status",
	7:  "role",
	8:  "token_version",
	9:  "created_at",
	10: "updated_at",
}

type CreateUserRequest struct {
	AimId    string `thrift:"aim_id,1" frugal:"1,default,string" json:"aim_id"`
	Email    string `thrift:"email,2" frugal:"2,default,string" json:"email"`
	Nickname string `thrift:"nickname,3" frugal:"3,default,string" json:"nickname"`
	Password string `thrift:"password,4" frugal:"4,default,string" json:"password"`
}

func NewCreateUserRequest() *CreateUserRequest {
	return &CreateUserRequest{}
}

func (p *CreateUserRequest) InitDefault() {
}

func (p *CreateUserRequest) GetAimId() (v string) {
	return p.AimId
}

func (p *CreateUserRequest) GetEmail() (v string) {
	return p.Email
}

func (p *CreateUserRequest) GetNickname() (v string) {
	return p.Nickname
}

func (p *CreateUserRequest) GetPassword() (v string) {
	return p.Password
}
func (p *CreateUserRequest) SetAimId(val string) {
	p.AimId = val
}
func (p *CreateUserRequest) SetEmail(val string) {
	p.Email = val
}
func (p *CreateUserRequest) SetNickname(val string) {
	p.Nickname = val
}
func (p *CreateUserRequest) SetPassword(val string) {
	p.Password = val
}

func (p *CreateUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserRequest(%+v)", *p)
}

var fieldIDToName_CreateUserRequest = map[int16]string{
	1: "aim_id",
	2: "email",
	3: "nickname",
	4: "password",
}

type CreateUserResponse struct {
	User *UserInfo `thrift:"user,1" frugal:"1,default,UserInfo" json:"user"`
}

func NewCreateUserResponse() *CreateUserResponse {
	return &CreateUserResponse{}
}

func (p *CreateUserResponse) InitDefault() {
}

var CreateUserResponse_User_DEFAULT *UserInfo

func (p *CreateUserResponse) GetUser() (v *UserInfo) {
	if !p.IsSetUser() {
		return CreateUserResponse_User_DEFAULT
	}
	return p.User
}
func (p *CreateUserResponse) SetUser(val *UserInfo) {
	p.User = val
}

func (p *CreateUserResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *CreateUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserResponse(%+v)", *p)
}

var fieldIDToName_CreateUserResponse = map[int16]string{
	1: "user",
}

type GetUserRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetUserRequest() *GetUserRequest {
	return &GetUserRequest{}
}

func (p *GetUserRequest) InitDefault() {
}

func (p *GetUserRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRequest(%+v)", *p)
}

var fieldIDToName_GetUserRequest = map[int16]string{
	1: "user_id",
}

type GetUserResponse struct {
	User *UserInfo `thrift:"user,1" frugal:"1,default,UserInfo" json:"user"`
}

func NewGetUserResponse() *GetUserResponse {
	return &GetUserResponse{}
}

func (p *GetUserResponse) InitDefault() {
}

var GetUserResponse_User_DEFAULT *UserInfo

func (p *GetUserResponse) GetUser() (v *UserInfo) {
	if !p.IsSetUser() {
		return GetUserResponse_User_DEFAULT
	}
	return p.User
}
func (p *GetUserResponse) SetUser(val *UserInfo) {
	p.User = val
}

func (p *GetUserResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *GetUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserResponse(%+v)", *p)
}

var fieldIDToName_GetUserResponse = map[int16]string{
	1: "user",
}

type GetUserByAimIDRequest struct {
	AimId string `thrift:"aim_id,1" frugal:"1,default,string" json:"aim_id"`
}

func NewGetUserByAimIDRequest() *GetUserByAimIDRequest {
	return &GetUserByAimIDRequest{}
}

func (p *GetUserByAimIDRequest) InitDefault() {
}

func (p *GetUserByAimIDRequest) GetAimId() (v string) {
	return p.AimId
}
func (p *GetUserByAimIDRequest) SetAimId(val string) {
	p.AimId = val
}

func (p *GetUserByAimIDRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserByAimIDRequest(%+v)", *p)
}

var fieldIDToName_GetUserByAimIDRequest = map[int16]string{
	1: "aim_id",
}

type GetUserByAimIDResponse struct {
	User *UserInfo `thrift:"user,1" frugal:"1,default,UserInfo" json:"user"`
}

func NewGetUserByAimIDResponse() *GetUserByAimIDResponse {
	return &GetUserByAimIDResponse{}
}

func (p *GetUserByAimIDResponse) InitDefault() {
}

var GetUserByAimIDResponse_User_DEFAULT *UserInfo

func (p *GetUserByAimIDResponse) GetUser() (v *UserInfo) {
	if !p.IsSetUser() {
		return GetUserByAimIDResponse_User_DEFAULT
	}
	return p.User
}
func (p *GetUserByAimIDResponse) SetUser(val *UserInfo) {
	p.User = val
}

func (p *GetUserByAimIDResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *GetUserByAimIDResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserByAimIDResponse(%+v)", *p)
}

var fieldIDToName_GetUserByAimIDResponse = map[int16]string{
	1: "user",
}

type VerifyCredentialRequest struct {
	Email    string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewVerifyCredentialRequest() *VerifyCredentialRequest {
	return &VerifyCredentialRequest{}
}

func (p *VerifyCredentialRequest) InitDefault() {
}

func (p *VerifyCredentialRequest) GetEmail() (v string) {
	return p.Email
}

func (p *VerifyCredentialRequest) GetPassword() (v string) {
	return p.Password
}
func (p *VerifyCredentialRequest) SetEmail(val string) {
	p.Email = val
}
func (p *VerifyCredentialRequest) SetPassword(val string) {
	p.Password = val
}

func (p *VerifyCredentialRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyCredentialRequest(%+v)", *p)
}

var fieldIDToName_VerifyCredentialRequest = map[int16]string{
	1: "email",
	2: "password",
}

type VerifyCredentialResponse struct {
	Ok     bool      `thrift:"ok,1" frugal:"1,default,bool" json:"ok"`
	User   *UserInfo `thrift:"user,2" frugal:"2,default,UserInfo" json:"user"`
	Reason string    `thrift:"reason,3" frugal:"3,default,string" json:"reason"`
}

func NewVerifyCredentialResponse() *VerifyCredentialResponse {
	return &VerifyCredentialResponse{}
}

func (p *VerifyCredentialResponse) InitDefault() {
}

func (p *VerifyCredentialResponse) GetOk() (v bool) {
	return p.Ok
}

var VerifyCredentialResponse_User_DEFAULT *UserInfo

func (p *VerifyCredentialResponse) GetUser() (v *UserInfo) {
	if !p.IsSetUser() {
		return VerifyCredentialResponse_User_DEFAULT
	}
	return p.User
}

func (p *VerifyCredentialResponse) GetReason() (v string) {
	return p.Reason
}
func (p *VerifyCredentialResponse) SetOk(val bool) {
	p.Ok = val
}
func (p *VerifyCredentialResponse) SetUser(val *UserInfo) {
	p.User = val
}
func (p *VerifyCredentialResponse) SetReason(val string) {
	p.Reason = val
}

func (p *VerifyCredentialResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *VerifyCredentialResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyCredentialResponse(%+v)", *p)
}

var fieldIDToName_VerifyCredentialResponse = map[int16]string{
	1: "ok",
	2: "user",
	3: "reason",
}

type CheckPasswordRequest struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewCheckPasswordRequest() *CheckPasswordRequest {
	return &CheckPasswordRequest{}
}

func (p *CheckPasswordRequest) InitDefault() {
}

func (p *CheckPasswordRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CheckPasswordRequest) GetPassword() (v string) {
	return p.Password
}
func (p *CheckPasswordRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CheckPasswordRequest) SetPassword(val string) {
	p.Password = val
}

func (p *CheckPasswordRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckPasswordRequest(%+v)", *p)
}

var fieldIDToName_CheckPasswordRequest = map[int16]string{
	1: "user_id",
	2: "password",
}

type CheckPasswordResponse struct {
	Ok bool `thrift:"ok,1" frugal:"1,default,bool" json:"ok"`
}

func NewCheckPasswordResponse() *CheckPasswordResponse {
	return &CheckPasswordResponse{}
}

func (p *CheckPasswordResponse) InitDefault() {
}

func (p *CheckPasswordResponse) GetOk() (v bool) {
	return p.Ok
}
func (p *CheckPasswordResponse) SetOk(val bool) {
	p.Ok = val
}

func (p *CheckPasswordResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckPasswordResponse(%+v)", *p)
}

var fieldIDToName_CheckPasswordResponse = map[int16]string{
	1: "ok",
}

type UpdateLoginStateRequest struct {
	UserId      int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	LastLoginIp string `thrift:"last_login_ip,2" frugal:"2,default,string" json:"last_login_ip"`
}

func NewUpdateLoginStateRequest() *UpdateLoginStateRequest {
	return &UpdateLoginStateRequest{}
}

func (p *UpdateLoginStateRequest) InitDefault() {
}

func (p *UpdateLoginStateRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateLoginStateRequest) GetLastLoginIp() (v string) {
	return p.LastLoginIp
}
func (p *UpdateLoginStateRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateLoginStateRequest) SetLastLoginIp(val string) {
	p.LastLoginIp = val
}

func (p *UpdateLoginStateRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateLoginStateRequest(%+v)", *p)
}

var fieldIDToName_UpdateLoginStateRequest = map[int16]string{
	1: "user_id",
	2: "last_login_ip",
}

type CommonResponse struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewCommonResponse() *CommonResponse {
	return &CommonResponse{}
}

func (p *CommonResponse) InitDefault() {
}

func (p *CommonResponse) GetSuccess() (v bool) {
	return p.Success
}

func (p *CommonResponse) GetMessage() (v string) {
	return p.Message
}
func (p *CommonResponse) SetSuccess(val bool) {
	p.Success = val
}
func (p *CommonResponse) SetMessage(val string) {
	p.Message = val
}

func (p *CommonResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonResponse(%+v)", *p)
}

var fieldIDToName_CommonResponse = map[int16]string{
	1: "success",
	2: "message",
}

type BumpTokenVersionRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewBumpTokenVersionRequest() *BumpTokenVersionRequest {
	return &BumpTokenVersionRequest{}
}

func (p *BumpTokenVersionRequest) InitDefault() {
}

func (p *BumpTokenVersionRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *BumpTokenVersionRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *BumpTokenVersionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BumpTokenVersionRequest(%+v)", *p)
}

var fieldIDToName_BumpTokenVersionRequest = map[int16]string{
	1: "user_id",
}

type UpdateAvatarRequest struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Avatar string `thrift:"avatar,2" frugal:"2,default,string" json:"avatar"`
}

func NewUpdateAvatarRequest() *UpdateAvatarRequest {
	return &UpdateAvatarRequest{}
}

func (p *UpdateAvatarRequest) InitDefault() {
}

func (p *UpdateAvatarRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateAvatarRequest) GetAvatar() (v string) {
	return p.Avatar
}
func (p *UpdateAvatarRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateAvatarRequest) SetAvatar(val string) {
	p.Avatar = val
}

func (p *UpdateAvatarRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAvatarRequest(%+v)", *p)
}

var fieldIDToName_UpdateAvatarRequest = map[int16]string{
	1: "user_id",
	2: "avatar",
}

type UpdateAvatarResponse struct {
	User *UserInfo `thrift:"user,1" frugal:"1,default,UserInfo" json:"user"`
}

func NewUpdateAvatarResponse() *UpdateAvatarResponse {
	return &UpdateAvatarResponse{}
}

func (p *UpdateAvatarResponse) InitDefault() {
}

var UpdateAvatarResponse_User_DEFAULT *UserInfo

func (p *UpdateAvatarResponse) GetUser() (v *UserInfo) {
	if !p.IsSetUser() {
		return UpdateAvatarResponse_User_DEFAULT
	}
	return p.User
}
func (p *UpdateAvatarResponse) SetUser(val *UserInfo) {
	p.User = val
}

func (p *UpdateAvatarResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *UpdateAvatarResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAvatarResponse(%+v)", *p)
}

var fieldIDToName_UpdateAvatarResponse = map[int16]string{
	1: "user",
}

type FriendGroupInfo struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name      string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	SortOrder int32  `thrift:"sort_order,3" frugal:"3,default,i32" json:"sort_order"`
	CreatedAt int64  `thrift:"created_at,4" frugal:"4,default,i64" json:"created_at"`
	UpdatedAt int64  `thrift:"updated_at,5" frugal:"5,default,i64" json:"updated_at"`
}

func NewFriendGroupInfo() *FriendGroupInfo {
	return &FriendGroupInfo{}
}

func (p *FriendGroupInfo) InitDefault() {
}

func (p *FriendGroupInfo) GetId() (v int64) {
	return p.Id
}

func (p *FriendGroupInfo) GetName() (v string) {
	return p.Name
}

func (p *FriendGroupInfo) GetSortOrder() (v int32) {
	return p.SortOrder
}

func (p *FriendGroupInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *FriendGroupInfo) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}
func (p *FriendGroupInfo) SetId(val int64) {
	p.Id = val
}
func (p *FriendGroupInfo) SetName(val string) {
	p.Name = val
}
func (p *FriendGroupInfo) SetSortOrder(val int32) {
	p.SortOrder = val
}
func (p *FriendGroupInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *FriendGroupInfo) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}

func (p *FriendGroupInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendGroupInfo(%+v)", *p)
}

var fieldIDToName_FriendGroupInfo = map[int16]string{
	1: "id",
	2: "name",
	3: "sort_order",
	4: "created_at",
	5: "updated_at",
}

type CreateFriendGroupRequest struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Name   string `thrift:"name,2" frugal:"2,default,string" json:"name"`
}

func NewCreateFriendGroupRequest() *CreateFriendGroupRequest {
	return &CreateFriendGroupRequest{}
}

func (p *CreateFriendGroupRequest) InitDefault() {
}

func (p *CreateFriendGroupRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateFriendGroupRequest) GetName() (v string) {
	return p.Name
}
func (p *CreateFriendGroupRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateFriendGroupRequest) SetName(val string) {
	p.Name = val
}

func (p *CreateFriendGroupRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateFriendGroupRequest(%+v)", *p)
}

var fieldIDToName_CreateFriendGroupRequest = map[int16]string{
	1: "user_id",
	2: "name",
}

type CreateFriendGroupResponse struct {
	Group *FriendGroupInfo `thrift:"group,1" frugal:"1,default,FriendGroupInfo" json:"group"`
}

func NewCreateFriendGroupResponse() *CreateFriendGroupResponse {
	return &CreateFriendGroupResponse{}
}

func (p *CreateFriendGroupResponse) InitDefault() {
}

var CreateFriendGroupResponse_Group_DEFAULT *FriendGroupInfo

func (p *CreateFriendGroupResponse) GetGroup() (v *FriendGroupInfo) {
	if !p.IsSetGroup() {
		return CreateFriendGroupResponse_Group_DEFAULT
	}
	return p.Group
}
func (p *CreateFriendGroupResponse) SetGroup(val *FriendGroupInfo) {
	p.Group = val
}

func (p *CreateFriendGroupResponse) IsSetGroup() bool {
	return p.Group != nil
}

func (p *CreateFriendGroupResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateFriendGroupResponse(%+v)", *p)
}

var fieldIDToName_CreateFriendGroupResponse = map[int16]string{
	1: "group",
}

type ListFriendGroupsRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewListFriendGroupsRequest() *ListFriendGroupsRequest {
	return &ListFriendGroupsRequest{}
}

func (p *ListFriendGroupsRequest) InitDefault() {
}

func (p *ListFriendGroupsRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *ListFriendGroupsRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *ListFriendGroupsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendGroupsRequest(%+v)", *p)
}

var fieldIDToName_ListFriendGroupsRequest = map[int16]string{
	1: "user_id",
}

type ListFriendGroupsResponse struct {
	Groups []*FriendGroupInfo `thrift:"groups,1" frugal:"1,default,list<FriendGroupInfo>" json:"groups"`
}

func NewListFriendGroupsResponse() *ListFriendGroupsResponse {
	return &ListFriendGroupsResponse{}
}

func (p *ListFriendGroupsResponse) InitDefault() {
}

func (p *ListFriendGroupsResponse) GetGroups() (v []*FriendGroupInfo) {
	return p.Groups
}
func (p *ListFriendGroupsResponse) SetGroups(val []*FriendGroupInfo) {
	p.Groups = val
}

func (p *ListFriendGroupsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendGroupsResponse(%+v)", *p)
}

var fieldIDToName_ListFriendGroupsResponse = map[int16]string{
	1: "groups",
}

type FriendInfo struct {
	UserId    int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	AimId     string `thrift:"aim_id,2" frugal:"2,default,string" json:"aim_id"`
	Nickname  string `thrift:"nickname,3" frugal:"3,default,string" json:"nickname"`
	Avatar    string `thrift:"avatar,4" frugal:"4,default,string" json:"avatar"`
	Remark    string `thrift:"remark,5" frugal:"5,default,string" json:"remark"`
	GroupId   *int64 `thrift:"group_id,6,optional" frugal:"6,optional,i64" json:"group_id,omitempty"`
	Status    string `thrift:"status,7" frugal:"7,default,string" json:"status"`
	CreatedAt int64  `thrift:"created_at,8" frugal:"8,default,i64" json:"created_at"`
	UpdatedAt int64  `thrift:"updated_at,9" frugal:"9,default,i64" json:"updated_at"`
}

func NewFriendInfo() *FriendInfo {
	return &FriendInfo{}
}

func (p *FriendInfo) InitDefault() {
}

func (p *FriendInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *FriendInfo) GetAimId() (v string) {
	return p.AimId
}

func (p *FriendInfo) GetNickname() (v string) {
	return p.Nickname
}

func (p *FriendInfo) GetAvatar() (v string) {
	return p.Avatar
}

func (p *FriendInfo) GetRemark() (v string) {
	return p.Remark
}

var FriendInfo_GroupId_DEFAULT int64

func (p *FriendInfo) GetGroupId() (v int64) {
	if !p.IsSetGroupId() {
		return FriendInfo_GroupId_DEFAULT
	}
	return *p.GroupId
}

func (p *FriendInfo) GetStatus() (v string) {
	return p.Status
}

func (p *FriendInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *FriendInfo) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}
func (p *FriendInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *FriendInfo) SetAimId(val string) {
	p.AimId = val
}
func (p *FriendInfo) SetNickname(val string) {
	p.Nickname = val
}
func (p *FriendInfo) SetAvatar(val string) {
	p.Avatar = val
}
func (p *FriendInfo) SetRemark(val string) {
	p.Remark = val
}
func (p *FriendInfo) SetGroupId(val *int64) {
	p.GroupId = val
}
func (p *FriendInfo) SetStatus(val string) {
	p.Status = val
}
func (p *FriendInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *FriendInfo) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}

func (p *FriendInfo) IsSetGroupId() bool {
	return p.GroupId != nil
}

func (p *FriendInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendInfo(%+v)", *p)
}

var fieldIDToName_FriendInfo = map[int16]string{
	1: "user_id",
	2: "aim_id",
	3: "nickname",
	4: "avatar",
	5: "remark",
	6: "group_id",
	7: "status",
	8: "created_at",
	9: "updated_at",
}

type FriendRequestInfo struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId    int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	AimId     string `thrift:"aim_id,3" frugal:"3,default,string" json:"aim_id"`
	Nickname  string `thrift:"nickname,4" frugal:"4,default,string" json:"nickname"`
	Avatar    string `thrift:"avatar,5" frugal:"5,default,string" json:"avatar"`
	Direction string `thrift:"direction,6" frugal:"6,default,string" json:"direction"`
	Status    string `thrift:"status,7" frugal:"7,default,string" json:"status"`
	Remark    string `thrift:"remark,8" frugal:"8,default,string" json:"remark"`
	GroupId   *int64 `thrift:"group_id,9,optional" frugal:"9,optional,i64" json:"group_id,omitempty"`
	CreatedAt int64  `thrift:"created_at,10" frugal:"10,default,i64" json:"created_at"`
	UpdatedAt int64  `thrift:"updated_at,11" frugal:"11,default,i64" json:"updated_at"`
}

func NewFriendRequestInfo() *FriendRequestInfo {
	return &FriendRequestInfo{}
}

func (p *FriendRequestInfo) InitDefault() {
}

func (p *FriendRequestInfo) GetId() (v int64) {
	return p.Id
}

func (p *FriendRequestInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *FriendRequestInfo) GetAimId() (v string) {
	return p.AimId
}

func (p *FriendRequestInfo) GetNickname() (v string) {
	return p.Nickname
}

func (p *FriendRequestInfo) GetAvatar() (v string) {
	return p.Avatar
}

func (p *FriendRequestInfo) GetDirection() (v string) {
	return p.Direction
}

func (p *FriendRequestInfo) GetStatus() (v string) {
	return p.Status
}

func (p *FriendRequestInfo) GetRemark() (v string) {
	return p.Remark
}

var FriendRequestInfo_GroupId_DEFAULT int64

func (p *FriendRequestInfo) GetGroupId() (v int64) {
	if !p.IsSetGroupId() {
		return FriendRequestInfo_GroupId_DEFAULT
	}
	return *p.GroupId
}

func (p *FriendRequestInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *FriendRequestInfo) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}
func (p *FriendRequestInfo) SetId(val int64) {
	p.Id = val
}
func (p *FriendRequestInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *FriendRequestInfo) SetAimId(val string) {
	p.AimId = val
}
func (p *FriendRequestInfo) SetNickname(val string) {
	p.Nickname = val
}
func (p *FriendRequestInfo) SetAvatar(val string) {
	p.Avatar = val
}
func (p *FriendRequestInfo) SetDirection(val string) {
	p.Direction = val
}
func (p *FriendRequestInfo) SetStatus(val string) {
	p.Status = val
}
func (p *FriendRequestInfo) SetRemark(val string) {
	p.Remark = val
}
func (p *FriendRequestInfo) SetGroupId(val *int64) {
	p.GroupId = val
}
func (p *FriendRequestInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *FriendRequestInfo) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}

func (p *FriendRequestInfo) IsSetGroupId() bool {
	return p.GroupId != nil
}

func (p *FriendRequestInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendRequestInfo(%+v)", *p)
}

var fieldIDToName_FriendRequestInfo = map[int16]string{
	1:  "id",
	2:  "user_id",
	3:  "aim_id",
	4:  "nickname",
	5:  "avatar",
	6:  "direction",
	7:  "status",
	8:  "remark",
	9:  "group_id",
	10: "created_at",
	11: "updated_at",
}

type AddFriendRequest struct {
	UserId      int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	TargetAimId string `thrift:"target_aim_id,2" frugal:"2,default,string" json:"target_aim_id"`
	Remark      string `thrift:"remark,3" frugal:"3,default,string" json:"remark"`
	GroupId     *int64 `thrift:"group_id,4,optional" frugal:"4,optional,i64" json:"group_id,omitempty"`
}

func NewAddFriendRequest() *AddFriendRequest {
	return &AddFriendRequest{}
}

func (p *AddFriendRequest) InitDefault() {
}

func (p *AddFriendRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *AddFriendRequest) GetTargetAimId() (v string) {
	return p.TargetAimId
}

func (p *AddFriendRequest) GetRemark() (v string) {
	return p.Remark
}

var AddFriendRequest_GroupId_DEFAULT int64

func (p *AddFriendRequest) GetGroupId() (v int64) {
	if !p.IsSetGroupId() {
		return AddFriendRequest_GroupId_DEFAULT
	}
	return *p.GroupId
}
func (p *AddFriendRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *AddFriendRequest) SetTargetAimId(val string) {
	p.TargetAimId = val
}
func (p *AddFriendRequest) SetRemark(val string) {
	p.Remark = val
}
func (p *AddFriendRequest) SetGroupId(val *int64) {
	p.GroupId = val
}

func (p *AddFriendRequest) IsSetGroupId() bool {
	return p.GroupId != nil
}

func (p *AddFriendRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddFriendRequest(%+v)", *p)
}

var fieldIDToName_AddFriendRequest = map[int16]string{
	1: "user_id",
	2: "target_aim_id",
	3: "remark",
	4: "group_id",
}

type AddFriendResponse struct {
	Request *FriendRequestInfo `thrift:"request,1" frugal:"1,default,FriendRequestInfo" json:"request"`
}

func NewAddFriendResponse() *AddFriendResponse {
	return &AddFriendResponse{}
}

func (p *AddFriendResponse) InitDefault() {
}

var AddFriendResponse_Request_DEFAULT *FriendRequestInfo

func (p *AddFriendResponse) GetRequest() (v *FriendRequestInfo) {
	if !p.IsSetRequest() {
		return AddFriendResponse_Request_DEFAULT
	}
	return p.Request
}
func (p *AddFriendResponse) SetRequest(val *FriendRequestInfo) {
	p.Request = val
}

func (p *AddFriendResponse) IsSetRequest() bool {
	return p.Request != nil
}

func (p *AddFriendResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddFriendResponse(%+v)", *p)
}

var fieldIDToName_AddFriendResponse = map[int16]string{
	1: "request",
}

type ListFriendsRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewListFriendsRequest() *ListFriendsRequest {
	return &ListFriendsRequest{}
}

func (p *ListFriendsRequest) InitDefault() {
}

func (p *ListFriendsRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *ListFriendsRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *ListFriendsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendsRequest(%+v)", *p)
}

var fieldIDToName_ListFriendsRequest = map[int16]string{
	1: "user_id",
}

type ListFriendsResponse struct {
	Friends []*FriendInfo `thrift:"friends,1" frugal:"1,default,list<FriendInfo>" json:"friends"`
}

func NewListFriendsResponse() *ListFriendsResponse {
	return &ListFriendsResponse{}
}

func (p *ListFriendsResponse) InitDefault() {
}

func (p *ListFriendsResponse) GetFriends() (v []*FriendInfo) {
	return p.Friends
}
func (p *ListFriendsResponse) SetFriends(val []*FriendInfo) {
	p.Friends = val
}

func (p *ListFriendsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendsResponse(%+v)", *p)
}

var fieldIDToName_ListFriendsResponse = map[int16]string{
	1: "friends",
}

type UpdateFriendRequest struct {
	UserId       int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendUserId int64  `thrift:"friend_user_id,2" frugal:"2,default,i64" json:"friend_user_id"`
	Remark       string `thrift:"remark,3" frugal:"3,default,string" json:"remark"`
	GroupId      *int64 `thrift:"group_id,4,optional" frugal:"4,optional,i64" json:"group_id,omitempty"`
}

func NewUpdateFriendRequest() *UpdateFriendRequest {
	return &UpdateFriendRequest{}
}

func (p *UpdateFriendRequest) InitDefault() {
}

func (p *UpdateFriendRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateFriendRequest) GetFriendUserId() (v int64) {
	return p.FriendUserId
}

func (p *UpdateFriendRequest) GetRemark() (v string) {
	return p.Remark
}

var UpdateFriendRequest_GroupId_DEFAULT int64

func (p *UpdateFriendRequest) GetGroupId() (v int64) {
	if !p.IsSetGroupId() {
		return UpdateFriendRequest_GroupId_DEFAULT
	}
	return *p.GroupId
}
func (p *UpdateFriendRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateFriendRequest) SetFriendUserId(val int64) {
	p.FriendUserId = val
}
func (p *UpdateFriendRequest) SetRemark(val string) {
	p.Remark = val
}
func (p *UpdateFriendRequest) SetGroupId(val *int64) {
	p.GroupId = val
}

func (p *UpdateFriendRequest) IsSetGroupId() bool {
	return p.GroupId != nil
}

func (p *UpdateFriendRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateFriendRequest(%+v)", *p)
}

var fieldIDToName_UpdateFriendRequest = map[int16]string{
	1: "user_id",
	2: "friend_user_id",
	3: "remark",
	4: "group_id",
}

type UpdateFriendResponse struct {
	Friend *FriendInfo `thrift:"friend,1" frugal:"1,default,FriendInfo" json:"friend"`
}

func NewUpdateFriendResponse() *UpdateFriendResponse {
	return &UpdateFriendResponse{}
}

func (p *UpdateFriendResponse) InitDefault() {
}

var UpdateFriendResponse_Friend_DEFAULT *FriendInfo

func (p *UpdateFriendResponse) GetFriend() (v *FriendInfo) {
	if !p.IsSetFriend() {
		return UpdateFriendResponse_Friend_DEFAULT
	}
	return p.Friend
}
func (p *UpdateFriendResponse) SetFriend(val *FriendInfo) {
	p.Friend = val
}

func (p *UpdateFriendResponse) IsSetFriend() bool {
	return p.Friend != nil
}

func (p *UpdateFriendResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateFriendResponse(%+v)", *p)
}

var fieldIDToName_UpdateFriendResponse = map[int16]string{
	1: "friend",
}

type DeleteFriendRequest struct {
	UserId       int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendUserId int64 `thrift:"friend_user_id,2" frugal:"2,default,i64" json:"friend_user_id"`
}

func NewDeleteFriendRequest() *DeleteFriendRequest {
	return &DeleteFriendRequest{}
}

func (p *DeleteFriendRequest) InitDefault() {
}

func (p *DeleteFriendRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *DeleteFriendRequest) GetFriendUserId() (v int64) {
	return p.FriendUserId
}
func (p *DeleteFriendRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *DeleteFriendRequest) SetFriendUserId(val int64) {
	p.FriendUserId = val
}

func (p *DeleteFriendRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFriendRequest(%+v)", *p)
}

var fieldIDToName_DeleteFriendRequest = map[int16]string{
	1: "user_id",
	2: "friend_user_id",
}

type CheckFriendRelationRequest struct {
	UserId       int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendUserId int64 `thrift:"friend_user_id,2" frugal:"2,default,i64" json:"friend_user_id"`
}

func NewCheckFriendRelationRequest() *CheckFriendRelationRequest {
	return &CheckFriendRelationRequest{}
}

func (p *CheckFriendRelationRequest) InitDefault() {
}

func (p *CheckFriendRelationRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CheckFriendRelationRequest) GetFriendUserId() (v int64) {
	return p.FriendUserId
}
func (p *CheckFriendRelationRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CheckFriendRelationRequest) SetFriendUserId(val int64) {
	p.FriendUserId = val
}

func (p *CheckFriendRelationRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckFriendRelationRequest(%+v)", *p)
}

var fieldIDToName_CheckFriendRelationRequest = map[int16]string{
	1: "user_id",
	2: "friend_user_id",
}

type CheckFriendRelationResponse struct {
	IsFriend bool `thrift:"is_friend,1" frugal:"1,default,bool" json:"is_friend"`
}

func NewCheckFriendRelationResponse() *CheckFriendRelationResponse {
	return &CheckFriendRelationResponse{}
}

func (p *CheckFriendRelationResponse) InitDefault() {
}

func (p *CheckFriendRelationResponse) GetIsFriend() (v bool) {
	return p.IsFriend
}
func (p *CheckFriendRelationResponse) SetIsFriend(val bool) {
	p.IsFriend = val
}

func (p *CheckFriendRelationResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckFriendRelationResponse(%+v)", *p)
}

var fieldIDToName_CheckFriendRelationResponse = map[int16]string{
	1: "is_friend",
}

type ListFriendRequestsRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewListFriendRequestsRequest() *ListFriendRequestsRequest {
	return &ListFriendRequestsRequest{}
}

func (p *ListFriendRequestsRequest) InitDefault() {
}

func (p *ListFriendRequestsRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *ListFriendRequestsRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *ListFriendRequestsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendRequestsRequest(%+v)", *p)
}

var fieldIDToName_ListFriendRequestsRequest = map[int16]string{
	1: "user_id",
}

type ListFriendRequestsResponse struct {
	Requests []*FriendRequestInfo `thrift:"requests,1" frugal:"1,default,list<FriendRequestInfo>" json:"requests"`
}

func NewListFriendRequestsResponse() *ListFriendRequestsResponse {
	return &ListFriendRequestsResponse{}
}

func (p *ListFriendRequestsResponse) InitDefault() {
}

func (p *ListFriendRequestsResponse) GetRequests() (v []*FriendRequestInfo) {
	return p.Requests
}
func (p *ListFriendRequestsResponse) SetRequests(val []*FriendRequestInfo) {
	p.Requests = val
}

func (p *ListFriendRequestsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendRequestsResponse(%+v)", *p)
}

var fieldIDToName_ListFriendRequestsResponse = map[int16]string{
	1: "requests",
}

type RespondFriendRequestRequest struct {
	UserId    int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	RequestId int64  `thrift:"request_id,2" frugal:"2,default,i64" json:"request_id"`
	Action    string `thrift:"action,3" frugal:"3,default,string" json:"action"`
}

func NewRespondFriendRequestRequest() *RespondFriendRequestRequest {
	return &RespondFriendRequestRequest{}
}

func (p *RespondFriendRequestRequest) InitDefault() {
}

func (p *RespondFriendRequestRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *RespondFriendRequestRequest) GetRequestId() (v int64) {
	return p.RequestId
}

func (p *RespondFriendRequestRequest) GetAction() (v string) {
	return p.Action
}
func (p *RespondFriendRequestRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *RespondFriendRequestRequest) SetRequestId(val int64) {
	p.RequestId = val
}
func (p *RespondFriendRequestRequest) SetAction(val string) {
	p.Action = val
}

func (p *RespondFriendRequestRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RespondFriendRequestRequest(%+v)", *p)
}

var fieldIDToName_RespondFriendRequestRequest = map[int16]string{
	1: "user_id",
	2: "request_id",
	3: "action",
}

type RespondFriendRequestResponse struct {
	Request *FriendRequestInfo `thrift:"request,1" frugal:"1,default,FriendRequestInfo" json:"request"`
	Friend  *FriendInfo        `thrift:"friend,2,optional" frugal:"2,optional,FriendInfo" json:"friend,omitempty"`
}

func NewRespondFriendRequestResponse() *RespondFriendRequestResponse {
	return &RespondFriendRequestResponse{}
}

func (p *RespondFriendRequestResponse) InitDefault() {
}

var RespondFriendRequestResponse_Request_DEFAULT *FriendRequestInfo

func (p *RespondFriendRequestResponse) GetRequest() (v *FriendRequestInfo) {
	if !p.IsSetRequest() {
		return RespondFriendRequestResponse_Request_DEFAULT
	}
	return p.Request
}

var RespondFriendRequestResponse_Friend_DEFAULT *FriendInfo

func (p *RespondFriendRequestResponse) GetFriend() (v *FriendInfo) {
	if !p.IsSetFriend() {
		return RespondFriendRequestResponse_Friend_DEFAULT
	}
	return p.Friend
}
func (p *RespondFriendRequestResponse) SetRequest(val *FriendRequestInfo) {
	p.Request = val
}
func (p *RespondFriendRequestResponse) SetFriend(val *FriendInfo) {
	p.Friend = val
}

func (p *RespondFriendRequestResponse) IsSetRequest() bool {
	return p.Request != nil
}

func (p *RespondFriendRequestResponse) IsSetFriend() bool {
	return p.Friend != nil
}

func (p *RespondFriendRequestResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RespondFriendRequestResponse(%+v)", *p)
}

var fieldIDToName_RespondFriendRequestResponse = map[int16]string{
	1: "request",
	2: "friend",
}

type UserService interface {
	CreateUser(ctx context.Context, req *CreateUserRequest) (r *CreateUserResponse, err error)

	GetUser(ctx context.Context, req *GetUserRequest) (r *GetUserResponse, err error)

	GetUserByAimID(ctx context.Context, req *GetUserByAimIDRequest) (r *GetUserByAimIDResponse, err error)

	VerifyCredential(ctx context.Context, req *VerifyCredentialRequest) (r *VerifyCredentialResponse, err error)

	CheckPassword(ctx context.Context, req *CheckPasswordRequest) (r *CheckPasswordResponse, err error)

	UpdateLoginState(ctx context.Context, req *UpdateLoginStateRequest) (r *CommonResponse, err error)

	BumpTokenVersion(ctx context.Context, req *BumpTokenVersionRequest) (r *CommonResponse, err error)

	UpdateAvatar(ctx context.Context, req *UpdateAvatarRequest) (r *UpdateAvatarResponse, err error)

	CreateFriendGroup(ctx context.Context, req *CreateFriendGroupRequest) (r *CreateFriendGroupResponse, err error)

	ListFriendGroups(ctx context.Context, req *ListFriendGroupsRequest) (r *ListFriendGroupsResponse, err error)

	AddFriend(ctx context.Context, req *AddFriendRequest) (r *AddFriendResponse, err error)

	ListFriends(ctx context.Context, req *ListFriendsRequest) (r *ListFriendsResponse, err error)

	CheckFriendRelation(ctx context.Context, req *CheckFriendRelationRequest) (r *CheckFriendRelationResponse, err error)

	UpdateFriend(ctx context.Context, req *UpdateFriendRequest) (r *UpdateFriendResponse, err error)

	DeleteFriend(ctx context.Context, req *DeleteFriendRequest) (r *CommonResponse, err error)

	ListFriendRequests(ctx context.Context, req *ListFriendRequestsRequest) (r *ListFriendRequestsResponse, err error)

	RespondFriendRequest(ctx context.Context, req *RespondFriendRequestRequest) (r *RespondFriendRequestResponse, err error)
}

type UserServiceCreateUserArgs struct {
	Req *CreateUserRequest `thrift:"req,1" frugal:"1,default,CreateUserRequest" json:"req"`
}

func NewUserServiceCreateUserArgs() *UserServiceCreateUserArgs {
	return &UserServiceCreateUserArgs{}
}

func (p *UserServiceCreateUserArgs) InitDefault() {
}

var UserServiceCreateUserArgs_Req_DEFAULT *CreateUserRequest

func (p *UserServiceCreateUserArgs) GetReq() (v *CreateUserRequest) {
	if !p.IsSetReq() {
		return UserServiceCreateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateUserArgs) SetReq(val *CreateUserRequest) {
	p.Req = val
}

func (p *UserServiceCreateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceCreateUserResult struct {
	Success *CreateUserResponse `thrift:"success,0,optional" frugal:"0,optional,CreateUserResponse" json:"success,omitempty"`
}

func NewUserServiceCreateUserResult() *UserServiceCreateUserResult {
	return &UserServiceCreateUserResult{}
}

func (p *UserServiceCreateUserResult) InitDefault() {
}

var UserServiceCreateUserResult_Success_DEFAULT *CreateUserResponse

func (p *UserServiceCreateUserResult) GetSuccess() (v *CreateUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCreateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCreateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateUserResponse)
}

func (p *UserServiceCreateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserArgs struct {
	Req *GetUserRequest `thrift:"req,1" frugal:"1,default,GetUserRequest" json:"req"`
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

var UserServiceGetUserArgs_Req_DEFAULT *GetUserRequest

func (p *UserServiceGetUserArgs) GetReq() (v *GetUserRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserArgs) SetReq(val *GetUserRequest) {
	p.Req = val
}

func (p *UserServiceGetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserResult struct {
	Success *GetUserResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *GetUserResponse

func (p *UserServiceGetUserResult) GetSuccess() (v *GetUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserResponse)
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserByAimIDArgs struct {
	Req *GetUserByAimIDRequest `thrift:"req,1" frugal:"1,default,GetUserByAimIDRequest" json:"req"`
}

func NewUserServiceGetUserByAimIDArgs() *UserServiceGetUserByAimIDArgs {
	return &UserServiceGetUserByAimIDArgs{}
}

func (p *UserServiceGetUserByAimIDArgs) InitDefault() {
}

var UserServiceGetUserByAimIDArgs_Req_DEFAULT *GetUserByAimIDRequest

func (p *UserServiceGetUserByAimIDArgs) GetReq() (v *GetUserByAimIDRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserByAimIDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserByAimIDArgs) SetReq(val *GetUserByAimIDRequest) {
	p.Req = val
}

func (p *UserServiceGetUserByAimIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserByAimIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserByAimIDArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserByAimIDArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserByAimIDResult struct {
	Success *GetUserByAimIDResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserByAimIDResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserByAimIDResult() *UserServiceGetUserByAimIDResult {
	return &UserServiceGetUserByAimIDResult{}
}

func (p *UserServiceGetUserByAimIDResult) InitDefault() {
}

var UserServiceGetUserByAimIDResult_Success_DEFAULT *GetUserByAimIDResponse

func (p *UserServiceGetUserByAimIDResult) GetSuccess() (v *GetUserByAimIDResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserByAimIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserByAimIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserByAimIDResponse)
}

func (p *UserServiceGetUserByAimIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserByAimIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserByAimIDResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserByAimIDResult = map[int16]string{
	0: "success",
}

type UserServiceVerifyCredentialArgs struct {
	Req *VerifyCredentialRequest `thrift:"req,1" frugal:"1,default,VerifyCredentialRequest" json:"req"`
}

func NewUserServiceVerifyCredentialArgs() *UserServiceVerifyCredentialArgs {
	return &UserServiceVerifyCredentialArgs{}
}

func (p *UserServiceVerifyCredentialArgs) InitDefault() {
}

var UserServiceVerifyCredentialArgs_Req_DEFAULT *VerifyCredentialRequest

func (p *UserServiceVerifyCredentialArgs) GetReq() (v *VerifyCredentialRequest) {
	if !p.IsSetReq() {
		return UserServiceVerifyCredentialArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceVerifyCredentialArgs) SetReq(val *VerifyCredentialRequest) {
	p.Req = val
}

func (p *UserServiceVerifyCredentialArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceVerifyCredentialArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyCredentialArgs(%+v)", *p)
}

var fieldIDToName_UserServiceVerifyCredentialArgs = map[int16]string{
	1: "req",
}

type UserServiceVerifyCredentialResult struct {
	Success *VerifyCredentialResponse `thrift:"success,0,optional" frugal:"0,optional,VerifyCredentialResponse" json:"success,omitempty"`
}

func NewUserServiceVerifyCredentialResult() *UserServiceVerifyCredentialResult {
	return &UserServiceVerifyCredentialResult{}
}

func (p *UserServiceVerifyCredentialResult) InitDefault() {
}

var UserServiceVerifyCredentialResult_Success_DEFAULT *VerifyCredentialResponse

func (p *UserServiceVerifyCredentialResult) GetSuccess() (v *VerifyCredentialResponse) {
	if !p.IsSetSuccess() {
		return UserServiceVerifyCredentialResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceVerifyCredentialResult) SetSuccess(x interface{}) {
	p.Success = x.(*VerifyCredentialResponse)
}

func (p *UserServiceVerifyCredentialResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceVerifyCredentialResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyCredentialResult(%+v)", *p)
}

var fieldIDToName_UserServiceVerifyCredentialResult = map[int16]string{
	0: "success",
}

type UserServiceCheckPasswordArgs struct {
	Req *CheckPasswordRequest `thrift:"req,1" frugal:"1,default,CheckPasswordRequest" json:"req"`
}

func NewUserServiceCheckPasswordArgs() *UserServiceCheckPasswordArgs {
	return &UserServiceCheckPasswordArgs{}
}

func (p *UserServiceCheckPasswordArgs) InitDefault() {
}

var UserServiceCheckPasswordArgs_Req_DEFAULT *CheckPasswordRequest

func (p *UserServiceCheckPasswordArgs) GetReq() (v *CheckPasswordRequest) {
	if !p.IsSetReq() {
		return UserServiceCheckPasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCheckPasswordArgs) SetReq(val *CheckPasswordRequest) {
	p.Req = val
}

func (p *UserServiceCheckPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCheckPasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCheckPasswordArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCheckPasswordArgs = map[int16]string{
	1: "req",
}

type UserServiceCheckPasswordResult struct {
	Success *CheckPasswordResponse `thrift:"success,0,optional" frugal:"0,optional,CheckPasswordResponse" json:"success,omitempty"`
}

func NewUserServiceCheckPasswordResult() *UserServiceCheckPasswordResult {
	return &UserServiceCheckPasswordResult{}
}

func (p *UserServiceCheckPasswordResult) InitDefault() {
}

var UserServiceCheckPasswordResult_Success_DEFAULT *CheckPasswordResponse

func (p *UserServiceCheckPasswordResult) GetSuccess() (v *CheckPasswordResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCheckPasswordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCheckPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckPasswordResponse)
}

func (p *UserServiceCheckPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCheckPasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCheckPasswordResult(%+v)", *p)
}

var fieldIDToName_UserServiceCheckPasswordResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateLoginStateArgs struct {
	Req *UpdateLoginStateRequest `thrift:"req,1" frugal:"1,default,UpdateLoginStateRequest" json:"req"`
}

func NewUserServiceUpdateLoginStateArgs() *UserServiceUpdateLoginStateArgs {
	return &UserServiceUpdateLoginStateArgs{}
}

func (p *UserServiceUpdateLoginStateArgs) InitDefault() {
}

var UserServiceUpdateLoginStateArgs_Req_DEFAULT *UpdateLoginStateRequest

func (p *UserServiceUpdateLoginStateArgs) GetReq() (v *UpdateLoginStateRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateLoginStateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateLoginStateArgs) SetReq(val *UpdateLoginStateRequest) {
	p.Req = val
}

func (p *UserServiceUpdateLoginStateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateLoginStateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateLoginStateArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateLoginStateArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateLoginStateResult struct {
	Success *CommonResponse `thrift:"success,0,optional" frugal:"0,optional,CommonResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateLoginStateResult() *UserServiceUpdateLoginStateResult {
	return &UserServiceUpdateLoginStateResult{}
}

func (p *UserServiceUpdateLoginStateResult) InitDefault() {
}

var UserServiceUpdateLoginStateResult_Success_DEFAULT *CommonResponse

func (p *UserServiceUpdateLoginStateResult) GetSuccess() (v *CommonResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateLoginStateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateLoginStateResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonResponse)
}

func (p *UserServiceUpdateLoginStateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateLoginStateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateLoginStateResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateLoginStateResult = map[int16]string{
	0: "success",
}

type UserServiceBumpTokenVersionArgs struct {
	Req *BumpTokenVersionRequest `thrift:"req,1" frugal:"1,default,BumpTokenVersionRequest" json:"req"`
}

func NewUserServiceBumpTokenVersionArgs() *UserServiceBumpTokenVersionArgs {
	return &UserServiceBumpTokenVersionArgs{}
}

func (p *UserServiceBumpTokenVersionArgs) InitDefault() {
}

var UserServiceBumpTokenVersionArgs_Req_DEFAULT *BumpTokenVersionRequest

func (p *UserServiceBumpTokenVersionArgs) GetReq() (v *BumpTokenVersionRequest) {
	if !p.IsSetReq() {
		return UserServiceBumpTokenVersionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceBumpTokenVersionArgs) SetReq(val *BumpTokenVersionRequest) {
	p.Req = val
}

func (p *UserServiceBumpTokenVersionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceBumpTokenVersionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceBumpTokenVersionArgs(%+v)", *p)
}

var fieldIDToName_UserServiceBumpTokenVersionArgs = map[int16]string{
	1: "req",
}

type UserServiceBumpTokenVersionResult struct {
	Success *CommonResponse `thrift:"success,0,optional" frugal:"0,optional,CommonResponse" json:"success,omitempty"`
}

func NewUserServiceBumpTokenVersionResult() *UserServiceBumpTokenVersionResult {
	return &UserServiceBumpTokenVersionResult{}
}

func (p *UserServiceBumpTokenVersionResult) InitDefault() {
}

var UserServiceBumpTokenVersionResult_Success_DEFAULT *CommonResponse

func (p *UserServiceBumpTokenVersionResult) GetSuccess() (v *CommonResponse) {
	if !p.IsSetSuccess() {
		return UserServiceBumpTokenVersionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceBumpTokenVersionResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonResponse)
}

func (p *UserServiceBumpTokenVersionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceBumpTokenVersionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceBumpTokenVersionResult(%+v)", *p)
}

var fieldIDToName_UserServiceBumpTokenVersionResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateAvatarArgs struct {
	Req *UpdateAvatarRequest `thrift:"req,1" frugal:"1,default,UpdateAvatarRequest" json:"req"`
}

func NewUserServiceUpdateAvatarArgs() *UserServiceUpdateAvatarArgs {
	return &UserServiceUpdateAvatarArgs{}
}

func (p *UserServiceUpdateAvatarArgs) InitDefault() {
}

var UserServiceUpdateAvatarArgs_Req_DEFAULT *UpdateAvatarRequest

func (p *UserServiceUpdateAvatarArgs) GetReq() (v *UpdateAvatarRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateAvatarArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateAvatarArgs) SetReq(val *UpdateAvatarRequest) {
	p.Req = val
}

func (p *UserServiceUpdateAvatarArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateAvatarArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateAvatarArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateAvatarArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateAvatarResult struct {
	Success *UpdateAvatarResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateAvatarResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateAvatarResult() *UserServiceUpdateAvatarResult {
	return &UserServiceUpdateAvatarResult{}
}

func (p *UserServiceUpdateAvatarResult) InitDefault() {
}

var UserServiceUpdateAvatarResult_Success_DEFAULT *UpdateAvatarResponse

func (p *UserServiceUpdateAvatarResult) GetSuccess() (v *UpdateAvatarResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateAvatarResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateAvatarResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateAvatarResponse)
}

func (p *UserServiceUpdateAvatarResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateAvatarResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateAvatarResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateAvatarResult = map[int16]string{
	0: "success",
}

type UserServiceCreateFriendGroupArgs struct {
	Req *CreateFriendGroupRequest `thrift:"req,1" frugal:"1,default,CreateFriendGroupRequest" json:"req"`
}

func NewUserServiceCreateFriendGroupArgs() *UserServiceCreateFriendGroupArgs {
	return &UserServiceCreateFriendGroupArgs{}
}

func (p *UserServiceCreateFriendGroupArgs) InitDefault() {
}

var UserServiceCreateFriendGroupArgs_Req_DEFAULT *CreateFriendGroupRequest

func (p *UserServiceCreateFriendGroupArgs) GetReq() (v *CreateFriendGroupRequest) {
	if !p.IsSetReq() {
		return UserServiceCreateFriendGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateFriendGroupArgs) SetReq(val *CreateFriendGroupRequest) {
	p.Req = val
}

func (p *UserServiceCreateFriendGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateFriendGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateFriendGroupArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateFriendGroupArgs = map[int16]string{
	1: "req",
}

type UserServiceCreateFriendGroupResult struct {
	Success *CreateFriendGroupResponse `thrift:"success,0,optional" frugal:"0,optional,CreateFriendGroupResponse" json:"success,omitempty"`
}

func NewUserServiceCreateFriendGroupResult() *UserServiceCreateFriendGroupResult {
	return &UserServiceCreateFriendGroupResult{}
}

func (p *UserServiceCreateFriendGroupResult) InitDefault() {
}

var UserServiceCreateFriendGroupResult_Success_DEFAULT *CreateFriendGroupResponse

func (p *UserServiceCreateFriendGroupResult) GetSuccess() (v *CreateFriendGroupResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCreateFriendGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCreateFriendGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateFriendGroupResponse)
}

func (p *UserServiceCreateFriendGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateFriendGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateFriendGroupResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateFriendGroupResult = map[int16]string{
	0: "success",
}

type UserServiceListFriendGroupsArgs struct {
	Req *ListFriendGroupsRequest `thrift:"req,1" frugal:"1,default,ListFriendGroupsRequest" json:"req"`
}

func NewUserServiceListFriendGroupsArgs() *UserServiceListFriendGroupsArgs {
	return &UserServiceListFriendGroupsArgs{}
}

func (p *UserServiceListFriendGroupsArgs) InitDefault() {
}

var UserServiceListFriendGroupsArgs_Req_DEFAULT *ListFriendGroupsRequest

func (p *UserServiceListFriendGroupsArgs) GetReq() (v *ListFriendGroupsRequest) {
	if !p.IsSetReq() {
		return UserServiceListFriendGroupsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceListFriendGroupsArgs) SetReq(val *ListFriendGroupsRequest) {
	p.Req = val
}

func (p *UserServiceListFriendGroupsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceListFriendGroupsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListFriendGroupsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceListFriendGroupsArgs = map[int16]string{
	1: "req",
}

type UserServiceListFriendGroupsResult struct {
	Success *ListFriendGroupsResponse `thrift:"success,0,optional" frugal:"0,optional,ListFriendGroupsResponse" json:"success,omitempty"`
}

func NewUserServiceListFriendGroupsResult() *UserServiceListFriendGroupsResult {
	return &UserServiceListFriendGroupsResult{}
}

func (p *UserServiceListFriendGroupsResult) InitDefault() {
}

var UserServiceListFriendGroupsResult_Success_DEFAULT *ListFriendGroupsResponse

func (p *UserServiceListFriendGroupsResult) GetSuccess() (v *ListFriendGroupsResponse) {
	if !p.IsSetSuccess() {
		return UserServiceListFriendGroupsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceListFriendGroupsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListFriendGroupsResponse)
}

func (p *UserServiceListFriendGroupsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceListFriendGroupsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListFriendGroupsResult(%+v)", *p)
}

var fieldIDToName_UserServiceListFriendGroupsResult = map[int16]string{
	0: "success",
}

type UserServiceAddFriendArgs struct {
	Req *AddFriendRequest `thrift:"req,1" frugal:"1,default,AddFriendRequest" json:"req"`
}

func NewUserServiceAddFriendArgs() *UserServiceAddFriendArgs {
	return &UserServiceAddFriendArgs{}
}

func (p *UserServiceAddFriendArgs) InitDefault() {
}

var UserServiceAddFriendArgs_Req_DEFAULT *AddFriendRequest

func (p *UserServiceAddFriendArgs) GetReq() (v *AddFriendRequest) {
	if !p.IsSetReq() {
		return UserServiceAddFriendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceAddFriendArgs) SetReq(val *AddFriendRequest) {
	p.Req = val
}

func (p *UserServiceAddFriendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceAddFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAddFriendArgs(%+v)", *p)
}

var fieldIDToName_UserServiceAddFriendArgs = map[int16]string{
	1: "req",
}

type UserServiceAddFriendResult struct {
	Success *AddFriendResponse `thrift:"success,0,optional" frugal:"0,optional,AddFriendResponse" json:"success,omitempty"`
}

func NewUserServiceAddFriendResult() *UserServiceAddFriendResult {
	return &UserServiceAddFriendResult{}
}

func (p *UserServiceAddFriendResult) InitDefault() {
}

var UserServiceAddFriendResult_Success_DEFAULT *AddFriendResponse

func (p *UserServiceAddFriendResult) GetSuccess() (v *AddFriendResponse) {
	if !p.IsSetSuccess() {
		return UserServiceAddFriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceAddFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddFriendResponse)
}

func (p *UserServiceAddFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceAddFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAddFriendResult(%+v)", *p)
}

var fieldIDToName_UserServiceAddFriendResult = map[int16]string{
	0: "success",
}

type UserServiceListFriendsArgs struct {
	Req *ListFriendsRequest `thrift:"req,1" frugal:"1,default,ListFriendsRequest" json:"req"`
}

func NewUserServiceListFriendsArgs() *UserServiceListFriendsArgs {
	return &UserServiceListFriendsArgs{}
}

func (p *UserServiceListFriendsArgs) InitDefault() {
}

var UserServiceListFriendsArgs_Req_DEFAULT *ListFriendsRequest

func (p *UserServiceListFriendsArgs) GetReq() (v *ListFriendsRequest) {
	if !p.IsSetReq() {
		return UserServiceListFriendsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceListFriendsArgs) SetReq(val *ListFriendsRequest) {
	p.Req = val
}

func (p *UserServiceListFriendsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceListFriendsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListFriendsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceListFriendsArgs = map[int16]string{
	1: "req",
}

type UserServiceListFriendsResult struct {
	Success *ListFriendsResponse `thrift:"success,0,optional" frugal:"0,optional,ListFriendsResponse" json:"success,omitempty"`
}

func NewUserServiceListFriendsResult() *UserServiceListFriendsResult {
	return &UserServiceListFriendsResult{}
}

func (p *UserServiceListFriendsResult) InitDefault() {
}

var UserServiceListFriendsResult_Success_DEFAULT *ListFriendsResponse

func (p *UserServiceListFriendsResult) GetSuccess() (v *ListFriendsResponse) {
	if !p.IsSetSuccess() {
		return UserServiceListFriendsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceListFriendsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListFriendsResponse)
}

func (p *UserServiceListFriendsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceListFriendsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListFriendsResult(%+v)", *p)
}

var fieldIDToName_UserServiceListFriendsResult = map[int16]string{
	0: "success",
}

type UserServiceCheckFriendRelationArgs struct {
	Req *CheckFriendRelationRequest `thrift:"req,1" frugal:"1,default,CheckFriendRelationRequest" json:"req"`
}

func NewUserServiceCheckFriendRelationArgs() *UserServiceCheckFriendRelationArgs {
	return &UserServiceCheckFriendRelationArgs{}
}

func (p *UserServiceCheckFriendRelationArgs) InitDefault() {
}

var UserServiceCheckFriendRelationArgs_Req_DEFAULT *CheckFriendRelationRequest

func (p *UserServiceCheckFriendRelationArgs) GetReq() (v *CheckFriendRelationRequest) {
	if !p.IsSetReq() {
		return UserServiceCheckFriendRelationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCheckFriendRelationArgs) SetReq(val *CheckFriendRelationRequest) {
	p.Req = val
}

func (p *UserServiceCheckFriendRelationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCheckFriendRelationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCheckFriendRelationArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCheckFriendRelationArgs = map[int16]string{
	1: "req",
}

type UserServiceCheckFriendRelationResult struct {
	Success *CheckFriendRelationResponse `thrift:"success,0,optional" frugal:"0,optional,CheckFriendRelationResponse" json:"success,omitempty"`
}

func NewUserServiceCheckFriendRelationResult() *UserServiceCheckFriendRelationResult {
	return &UserServiceCheckFriendRelationResult{}
}

func (p *UserServiceCheckFriendRelationResult) InitDefault() {
}

var UserServiceCheckFriendRelationResult_Success_DEFAULT *CheckFriendRelationResponse

func (p *UserServiceCheckFriendRelationResult) GetSuccess() (v *CheckFriendRelationResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCheckFriendRelationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCheckFriendRelationResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckFriendRelationResponse)
}

func (p *UserServiceCheckFriendRelationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCheckFriendRelationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCheckFriendRelationResult(%+v)", *p)
}

var fieldIDToName_UserServiceCheckFriendRelationResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateFriendArgs struct {
	Req *UpdateFriendRequest `thrift:"req,1" frugal:"1,default,UpdateFriendRequest" json:"req"`
}

func NewUserServiceUpdateFriendArgs() *UserServiceUpdateFriendArgs {
	return &UserServiceUpdateFriendArgs{}
}

func (p *UserServiceUpdateFriendArgs) InitDefault() {
}

var UserServiceUpdateFriendArgs_Req_DEFAULT *UpdateFriendRequest

func (p *UserServiceUpdateFriendArgs) GetReq() (v *UpdateFriendRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateFriendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateFriendArgs) SetReq(val *UpdateFriendRequest) {
	p.Req = val
}

func (p *UserServiceUpdateFriendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateFriendArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateFriendArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateFriendResult struct {
	Success *UpdateFriendResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateFriendResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateFriendResult() *UserServiceUpdateFriendResult {
	return &UserServiceUpdateFriendResult{}
}

func (p *UserServiceUpdateFriendResult) InitDefault() {
}

var UserServiceUpdateFriendResult_Success_DEFAULT *UpdateFriendResponse

func (p *UserServiceUpdateFriendResult) GetSuccess() (v *UpdateFriendResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateFriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateFriendResponse)
}

func (p *UserServiceUpdateFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateFriendResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateFriendResult = map[int16]string{
	0: "success",
}

type UserServiceDeleteFriendArgs struct {
	Req *DeleteFriendRequest `thrift:"req,1" frugal:"1,default,DeleteFriendRequest" json:"req"`
}

func NewUserServiceDeleteFriendArgs() *UserServiceDeleteFriendArgs {
	return &UserServiceDeleteFriendArgs{}
}

func (p *UserServiceDeleteFriendArgs) InitDefault() {
}

var UserServiceDeleteFriendArgs_Req_DEFAULT *DeleteFriendRequest

func (p *UserServiceDeleteFriendArgs) GetReq() (v *DeleteFriendRequest) {
	if !p.IsSetReq() {
		return UserServiceDeleteFriendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceDeleteFriendArgs) SetReq(val *DeleteFriendRequest) {
	p.Req = val
}

func (p *UserServiceDeleteFriendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceDeleteFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteFriendArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteFriendArgs = map[int16]string{
	1: "req",
}

type UserServiceDeleteFriendResult struct {
	Success *CommonResponse `thrift:"success,0,optional" frugal:"0,optional,CommonResponse" json:"success,omitempty"`
}

func NewUserServiceDeleteFriendResult() *UserServiceDeleteFriendResult {
	return &UserServiceDeleteFriendResult{}
}

func (p *UserServiceDeleteFriendResult) InitDefault() {
}

var UserServiceDeleteFriendResult_Success_DEFAULT *CommonResponse

func (p *UserServiceDeleteFriendResult) GetSuccess() (v *CommonResponse) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteFriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceDeleteFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonResponse)
}

func (p *UserServiceDeleteFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteFriendResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteFriendResult = map[int16]string{
	0: "success",
}

type UserServiceListFriendRequestsArgs struct {
	Req *ListFriendRequestsRequest `thrift:"req,1" frugal:"1,default,ListFriendRequestsRequest" json:"req"`
}

func NewUserServiceListFriendRequestsArgs() *UserServiceListFriendRequestsArgs {
	return &UserServiceListFriendRequestsArgs{}
}

func (p *UserServiceListFriendRequestsArgs) InitDefault() {
}

var UserServiceListFriendRequestsArgs_Req_DEFAULT *ListFriendRequestsRequest

func (p *UserServiceListFriendRequestsArgs) GetReq() (v *ListFriendRequestsRequest) {
	if !p.IsSetReq() {
		return UserServiceListFriendRequestsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceListFriendRequestsArgs) SetReq(val *ListFriendRequestsRequest) {
	p.Req = val
}

func (p *UserServiceListFriendRequestsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceListFriendRequestsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListFriendRequestsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceListFriendRequestsArgs = map[int16]string{
	1: "req",
}

type UserServiceListFriendRequestsResult struct {
	Success *ListFriendRequestsResponse `thrift:"success,0,optional" frugal:"0,optional,ListFriendRequestsResponse" json:"success,omitempty"`
}

func NewUserServiceListFriendRequestsResult() *UserServiceListFriendRequestsResult {
	return &UserServiceListFriendRequestsResult{}
}

func (p *UserServiceListFriendRequestsResult) InitDefault() {
}

var UserServiceListFriendRequestsResult_Success_DEFAULT *ListFriendRequestsResponse

func (p *UserServiceListFriendRequestsResult) GetSuccess() (v *ListFriendRequestsResponse) {
	if !p.IsSetSuccess() {
		return UserServiceListFriendRequestsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceListFriendRequestsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListFriendRequestsResponse)
}

func (p *UserServiceListFriendRequestsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceListFriendRequestsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceListFriendRequestsResult(%+v)", *p)
}

var fieldIDToName_UserServiceListFriendRequestsResult = map[int16]string{
	0: "success",
}

type UserServiceRespondFriendRequestArgs struct {
	Req *RespondFriendRequestRequest `thrift:"req,1" frugal:"1,default,RespondFriendRequestRequest" json:"req"`
}

func NewUserServiceRespondFriendRequestArgs() *UserServiceRespondFriendRequestArgs {
	return &UserServiceRespondFriendRequestArgs{}
}

func (p *UserServiceRespondFriendRequestArgs) InitDefault() {
}

var UserServiceRespondFriendRequestArgs_Req_DEFAULT *RespondFriendRequestRequest

func (p *UserServiceRespondFriendRequestArgs) GetReq() (v *RespondFriendRequestRequest) {
	if !p.IsSetReq() {
		return UserServiceRespondFriendRequestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRespondFriendRequestArgs) SetReq(val *RespondFriendRequestRequest) {
	p.Req = val
}

func (p *UserServiceRespondFriendRequestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRespondFriendRequestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRespondFriendRequestArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRespondFriendRequestArgs = map[int16]string{
	1: "req",
}

type UserServiceRespondFriendRequestResult struct {
	Success *RespondFriendRequestResponse `thrift:"success,0,optional" frugal:"0,optional,RespondFriendRequestResponse" json:"success,omitempty"`
}

func NewUserServiceRespondFriendRequestResult() *UserServiceRespondFriendRequestResult {
	return &UserServiceRespondFriendRequestResult{}
}

func (p *UserServiceRespondFriendRequestResult) InitDefault() {
}

var UserServiceRespondFriendRequestResult_Success_DEFAULT *RespondFriendRequestResponse

func (p *UserServiceRespondFriendRequestResult) GetSuccess() (v *RespondFriendRequestResponse) {
	if !p.IsSetSuccess() {
		return UserServiceRespondFriendRequestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRespondFriendRequestResult) SetSuccess(x interface{}) {
	p.Success = x.(*RespondFriendRequestResponse)
}

func (p *UserServiceRespondFriendRequestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRespondFriendRequestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRespondFriendRequestResult(%+v)", *p)
}

var fieldIDToName_UserServiceRespondFriendRequestResult = map[int16]string{
	0: "success",
}
