// Code generated by Kitex v0.16.1. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	user "example.com/aim/auth-service/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateUser": kitex.NewMethodInfo(
		createUserHandler,
		newUserServiceCreateUserArgs,
		newUserServiceCreateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUser": kitex.NewMethodInfo(
		getUserHandler,
		newUserServiceGetUserArgs,
		newUserServiceGetUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserByAimID": kitex.NewMethodInfo(
		getUserByAimIDHandler,
		newUserServiceGetUserByAimIDArgs,
		newUserServiceGetUserByAimIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyCredential": kitex.NewMethodInfo(
		verifyCredentialHandler,
		newUserServiceVerifyCredentialArgs,
		newUserServiceVerifyCredentialResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckPassword": kitex.NewMethodInfo(
		checkPasswordHandler,
		newUserServiceCheckPasswordArgs,
		newUserServiceCheckPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateLoginState": kitex.NewMethodInfo(
		updateLoginStateHandler,
		newUserServiceUpdateLoginStateArgs,
		newUserServiceUpdateLoginStateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BumpTokenVersion": kitex.NewMethodInfo(
		bumpTokenVersionHandler,
		newUserServiceBumpTokenVersionArgs,
		newUserServiceBumpTokenVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAvatar": kitex.NewMethodInfo(
		updateAvatarHandler,
		newUserServiceUpdateAvatarArgs,
		newUserServiceUpdateAvatarResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateFriendGroup": kitex.NewMethodInfo(
		createFriendGroupHandler,
		newUserServiceCreateFriendGroupArgs,
		newUserServiceCreateFriendGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListFriendGroups": kitex.NewMethodInfo(
		listFriendGroupsHandler,
		newUserServiceListFriendGroupsArgs,
		newUserServiceListFriendGroupsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddFriend": kitex.NewMethodInfo(
		addFriendHandler,
		newUserServiceAddFriendArgs,
		newUserServiceAddFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListFriends": kitex.NewMethodInfo(
		listFriendsHandler,
		newUserServiceListFriendsArgs,
		newUserServiceListFriendsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckFriendRelation": kitex.NewMethodInfo(
		checkFriendRelationHandler,
		newUserServiceCheckFriendRelationArgs,
		newUserServiceCheckFriendRelationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateFriend": kitex.NewMethodInfo(
		updateFriendHandler,
		newUserServiceUpdateFriendArgs,
		newUserServiceUpdateFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteFriend": kitex.NewMethodInfo(
		deleteFriendHandler,
		newUserServiceDeleteFriendArgs,
		newUserServiceDeleteFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListFriendRequests": kitex.NewMethodInfo(
		listFriendRequestsHandler,
		newUserServiceListFriendRequestsArgs,
		newUserServiceListFriendRequestsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RespondFriendRequest": kitex.NewMethodInfo(
		respondFriendRequestHandler,
		newUserServiceRespondFriendRequestArgs,
		newUserServiceRespondFriendRequestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCreateUserArgs)
	realResult := result.(*user.UserServiceCreateUserResult)
	success, err := handler.(user.UserService).CreateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCreateUserArgs() interface{} {
	return user.NewUserServiceCreateUserArgs()
}

func newUserServiceCreateUserResult() interface{} {
	return user.NewUserServiceCreateUserResult()
}

func getUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserArgs)
	realResult := result.(*user.UserServiceGetUserResult)
	success, err := handler.(user.UserService).GetUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserArgs() interface{} {
	return user.NewUserServiceGetUserArgs()
}

func newUserServiceGetUserResult() interface{} {
	return user.NewUserServiceGetUserResult()
}

func getUserByAimIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserByAimIDArgs)
	realResult := result.(*user.UserServiceGetUserByAimIDResult)
	success, err := handler.(user.UserService).GetUserByAimID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserByAimIDArgs() interface{} {
	return user.NewUserServiceGetUserByAimIDArgs()
}

func newUserServiceGetUserByAimIDResult() interface{} {
	return user.NewUserServiceGetUserByAimIDResult()
}

func verifyCredentialHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceVerifyCredentialArgs)
	realResult := result.(*user.UserServiceVerifyCredentialResult)
	success, err := handler.(user.UserService).VerifyCredential(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceVerifyCredentialArgs() interface{} {
	return user.NewUserServiceVerifyCredentialArgs()
}

func newUserServiceVerifyCredentialResult() interface{} {
	return user.NewUserServiceVerifyCredentialResult()
}

func checkPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCheckPasswordArgs)
	realResult := result.(*user.UserServiceCheckPasswordResult)
	success, err := handler.(user.UserService).CheckPassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCheckPasswordArgs() interface{} {
	return user.NewUserServiceCheckPasswordArgs()
}

func newUserServiceCheckPasswordResult() interface{} {
	return user.NewUserServiceCheckPasswordResult()
}

func updateLoginStateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateLoginStateArgs)
	realResult := result.(*user.UserServiceUpdateLoginStateResult)
	success, err := handler.(user.UserService).UpdateLoginState(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateLoginStateArgs() interface{} {
	return user.NewUserServiceUpdateLoginStateArgs()
}

func newUserServiceUpdateLoginStateResult() interface{} {
	return user.NewUserServiceUpdateLoginStateResult()
}

func bumpTokenVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceBumpTokenVersionArgs)
	realResult := result.(*user.UserServiceBumpTokenVersionResult)
	success, err := handler.(user.UserService).BumpTokenVersion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceBumpTokenVersionArgs() interface{} {
	return user.NewUserServiceBumpTokenVersionArgs()
}

func newUserServiceBumpTokenVersionResult() interface{} {
	return user.NewUserServiceBumpTokenVersionResult()
}

func updateAvatarHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateAvatarArgs)
	realResult := result.(*user.UserServiceUpdateAvatarResult)
	success, err := handler.(user.UserService).UpdateAvatar(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateAvatarArgs() interface{} {
	return user.NewUserServiceUpdateAvatarArgs()
}

func newUserServiceUpdateAvatarResult() interface{} {
	return user.NewUserServiceUpdateAvatarResult()
}

func createFriendGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCreateFriendGroupArgs)
	realResult := result.(*user.UserServiceCreateFriendGroupResult)
	success, err := handler.(user.UserService).CreateFriendGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCreateFriendGroupArgs() interface{} {
	return user.NewUserServiceCreateFriendGroupArgs()
}

func newUserServiceCreateFriendGroupResult() interface{} {
	return user.NewUserServiceCreateFriendGroupResult()
}

func listFriendGroupsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceListFriendGroupsArgs)
	realResult := result.(*user.UserServiceListFriendGroupsResult)
	success, err := handler.(user.UserService).ListFriendGroups(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceListFriendGroupsArgs() interface{} {
	return user.NewUserServiceListFriendGroupsArgs()
}

func newUserServiceListFriendGroupsResult() interface{} {
	return user.NewUserServiceListFriendGroupsResult()
}

func addFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAddFriendArgs)
	realResult := result.(*user.UserServiceAddFriendResult)
	success, err := handler.(user.UserService).AddFriend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAddFriendArgs() interface{} {
	return user.NewUserServiceAddFriendArgs()
}

func newUserServiceAddFriendResult() interface{} {
	return user.NewUserServiceAddFriendResult()
}

func listFriendsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceListFriendsArgs)
	realResult := result.(*user.UserServiceListFriendsResult)
	success, err := handler.(user.UserService).ListFriends(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceListFriendsArgs() interface{} {
	return user.NewUserServiceListFriendsArgs()
}

func newUserServiceListFriendsResult() interface{} {
	return user.NewUserServiceListFriendsResult()
}

func checkFriendRelationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCheckFriendRelationArgs)
	realResult := result.(*user.UserServiceCheckFriendRelationResult)
	success, err := handler.(user.UserService).CheckFriendRelation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCheckFriendRelationArgs() interface{} {
	return user.NewUserServiceCheckFriendRelationArgs()
}

func newUserServiceCheckFriendRelationResult() interface{} {
	return user.NewUserServiceCheckFriendRelationResult()
}

func updateFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateFriendArgs)
	realResult := result.(*user.UserServiceUpdateFriendResult)
	success, err := handler.(user.UserService).UpdateFriend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateFriendArgs() interface{} {
	return user.NewUserServiceUpdateFriendArgs()
}

func newUserServiceUpdateFriendResult() interface{} {
	return user.NewUserServiceUpdateFriendResult()
}

func deleteFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceDeleteFriendArgs)
	realResult := result.(*user.UserServiceDeleteFriendResult)
	success, err := handler.(user.UserService).DeleteFriend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceDeleteFriendArgs() interface{} {
	return user.NewUserServiceDeleteFriendArgs()
}

func newUserServiceDeleteFriendResult() interface{} {
	return user.NewUserServiceDeleteFriendResult()
}

func listFriendRequestsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceListFriendRequestsArgs)
	realResult := result.(*user.UserServiceListFriendRequestsResult)
	success, err := handler.(user.UserService).ListFriendRequests(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceListFriendRequestsArgs() interface{} {
	return user.NewUserServiceListFriendRequestsArgs()
}

func newUserServiceListFriendRequestsResult() interface{} {
	return user.NewUserServiceListFriendRequestsResult()
}

func respondFriendRequestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRespondFriendRequestArgs)
	realResult := result.(*user.UserServiceRespondFriendRequestResult)
	success, err := handler.(user.UserService).RespondFriendRequest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRespondFriendRequestArgs() interface{} {
	return user.NewUserServiceRespondFriendRequestArgs()
}

func newUserServiceRespondFriendRequestResult() interface{} {
	return user.NewUserServiceRespondFriendRequestResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateUser(ctx context.Context, req *user.CreateUserRequest) (r *user.CreateUserResponse, err error) {
	var _args user.UserServiceCreateUserArgs
	_args.Req = req
	var _result user.UserServiceCreateUserResult
	if err = p.c.Call(ctx, "CreateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUser(ctx context.Context, req *user.GetUserRequest) (r *user.GetUserResponse, err error) {
	var _args user.UserServiceGetUserArgs
	_args.Req = req
	var _result user.UserServiceGetUserResult
	if err = p.c.Call(ctx, "GetUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserByAimID(ctx context.Context, req *user.GetUserByAimIDRequest) (r *user.GetUserByAimIDResponse, err error) {
	var _args user.UserServiceGetUserByAimIDArgs
	_args.Req = req
	var _result user.UserServiceGetUserByAimIDResult
	if err = p.c.Call(ctx, "GetUserByAimID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyCredential(ctx context.Context, req *user.VerifyCredentialRequest) (r *user.VerifyCredentialResponse, err error) {
	var _args user.UserServiceVerifyCredentialArgs
	_args.Req = req
	var _result user.UserServiceVerifyCredentialResult
	if err = p.c.Call(ctx, "VerifyCredential", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckPassword(ctx context.Context, req *user.CheckPasswordRequest) (r *user.CheckPasswordResponse, err error) {
	var _args user.UserServiceCheckPasswordArgs
	_args.Req = req
	var _result user.UserServiceCheckPasswordResult
	if err = p.c.Call(ctx, "CheckPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateLoginState(ctx context.Context, req *user.UpdateLoginStateRequest) (r *user.CommonResponse, err error) {
	var _args user.UserServiceUpdateLoginStateArgs
	_args.Req = req
	var _result user.UserServiceUpdateLoginStateResult
	if err = p.c.Call(ctx, "UpdateLoginState", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BumpTokenVersion(ctx context.Context, req *user.BumpTokenVersionRequest) (r *user.CommonResponse, err error) {
	var _args user.UserServiceBumpTokenVersionArgs
	_args.Req = req
	var _result user.UserServiceBumpTokenVersionResult
	if err = p.c.Call(ctx, "BumpTokenVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAvatar(ctx context.Context, req *user.UpdateAvatarRequest) (r *user.UpdateAvatarResponse, err error) {
	var _args user.UserServiceUpdateAvatarArgs
	_args.Req = req
	var _result user.UserServiceUpdateAvatarResult
	if err = p.c.Call(ctx, "UpdateAvatar", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateFriendGroup(ctx context.Context, req *user.CreateFriendGroupRequest) (r *user.CreateFriendGroupResponse, err error) {
	var _args user.UserServiceCreateFriendGroupArgs
	_args.Req = req
	var _result user.UserServiceCreateFriendGroupResult
	if err = p.c.Call(ctx, "CreateFriendGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListFriendGroups(ctx context.Context, req *user.ListFriendGroupsRequest) (r *user.ListFriendGroupsResponse, err error) {
	var _args user.UserServiceListFriendGroupsArgs
	_args.Req = req
	var _result user.UserServiceListFriendGroupsResult
	if err = p.c.Call(ctx, "ListFriendGroups", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddFriend(ctx context.Context, req *user.AddFriendRequest) (r *user.AddFriendResponse, err error) {
	var _args user.UserServiceAddFriendArgs
	_args.Req = req
	var _result user.UserServiceAddFriendResult
	if err = p.c.Call(ctx, "AddFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListFriends(ctx context.Context, req *user.ListFriendsRequest) (r *user.ListFriendsResponse, err error) {
	var _args user.UserServiceListFriendsArgs
	_args.Req = req
	var _result user.UserServiceListFriendsResult
	if err = p.c.Call(ctx, "ListFriends", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckFriendRelation(ctx context.Context, req *user.CheckFriendRelationRequest) (r *user.CheckFriendRelationResponse, err error) {
	var _args user.UserServiceCheckFriendRelationArgs
	_args.Req = req
	var _result user.UserServiceCheckFriendRelationResult
	if err = p.c.Call(ctx, "CheckFriendRelation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateFriend(ctx context.Context, req *user.UpdateFriendRequest) (r *user.UpdateFriendResponse, err error) {
	var _args user.UserServiceUpdateFriendArgs
	_args.Req = req
	var _result user.UserServiceUpdateFriendResult
	if err = p.c.Call(ctx, "UpdateFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteFriend(ctx context.Context, req *user.DeleteFriendRequest) (r *user.CommonResponse, err error) {
	var _args user.UserServiceDeleteFriendArgs
	_args.Req = req
	var _result user.UserServiceDeleteFriendResult
	if err = p.c.Call(ctx, "DeleteFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListFriendRequests(ctx context.Context, req *user.ListFriendRequestsRequest) (r *user.ListFriendRequestsResponse, err error) {
	var _args user.UserServiceListFriendRequestsArgs
	_args.Req = req
	var _result user.UserServiceListFriendRequestsResult
	if err = p.c.Call(ctx, "ListFriendRequests", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RespondFriendRequest(ctx context.Context, req *user.RespondFriendRequestRequest) (r *user.RespondFriendRequestResponse, err error) {
	var _args user.UserServiceRespondFriendRequestArgs
	_args.Req = req
	var _result user.UserServiceRespondFriendRequestResult
	if err = p.c.Call(ctx, "RespondFriendRequest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
