// Code generated by Kitex v0.16.1. DO NOT EDIT.

package ragservice

import (
	"context"
	rag "example.com/aim/gateway/kitex_gen/rag"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Health(ctx context.Context, req *rag.HealthRequest, callOptions ...callopt.Option) (r *rag.HealthResponse, err error)
	CreateKnowledgeBase(ctx context.Context, req *rag.CreateKnowledgeBaseRequest, callOptions ...callopt.Option) (r *rag.CreateKnowledgeBaseResponse, err error)
	ListKnowledgeBases(ctx context.Context, req *rag.ListKnowledgeBasesRequest, callOptions ...callopt.Option) (r *rag.ListKnowledgeBasesResponse, err error)
	AddKnowledgeDocumentText(ctx context.Context, req *rag.AddKnowledgeDocumentTextRequest, callOptions ...callopt.Option) (r *rag.AddKnowledgeDocumentTextResponse, err error)
	ListKnowledgeDocuments(ctx context.Context, req *rag.ListKnowledgeDocumentsRequest, callOptions ...callopt.Option) (r *rag.ListKnowledgeDocumentsResponse, err error)
	ListKnowledgeDocumentChunks(ctx context.Context, req *rag.ListKnowledgeDocumentChunksRequest, callOptions ...callopt.Option) (r *rag.ListKnowledgeDocumentChunksResponse, err error)
	DeleteKnowledgeDocument(ctx context.Context, req *rag.DeleteKnowledgeDocumentRequest, callOptions ...callopt.Option) (r *rag.CommonResponse, err error)
	SearchKnowledgeBase(ctx context.Context, req *rag.SearchKnowledgeBaseRequest, callOptions ...callopt.Option) (r *rag.SearchKnowledgeBaseResponse, err error)
	BindConversationKnowledgeBase(ctx context.Context, req *rag.BindConversationKnowledgeBaseRequest, callOptions ...callopt.Option) (r *rag.CommonResponse, err error)
	ListConversationKnowledgeBases(ctx context.Context, req *rag.ListConversationKnowledgeBasesRequest, callOptions ...callopt.Option) (r *rag.ListConversationKnowledgeBasesResponse, err error)
	UnbindConversationKnowledgeBase(ctx context.Context, req *rag.UnbindConversationKnowledgeBaseRequest, callOptions ...callopt.Option) (r *rag.CommonResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRAGServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRAGServiceClient struct {
	*kClient
}

func (p *kRAGServiceClient) Health(ctx context.Context, req *rag.HealthRequest, callOptions ...callopt.Option) (r *rag.HealthResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx, req)
}

func (p *kRAGServiceClient) CreateKnowledgeBase(ctx context.Context, req *rag.CreateKnowledgeBaseRequest, callOptions ...callopt.Option) (r *rag.CreateKnowledgeBaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateKnowledgeBase(ctx, req)
}

func (p *kRAGServiceClient) ListKnowledgeBases(ctx context.Context, req *rag.ListKnowledgeBasesRequest, callOptions ...callopt.Option) (r *rag.ListKnowledgeBasesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListKnowledgeBases(ctx, req)
}

func (p *kRAGServiceClient) AddKnowledgeDocumentText(ctx context.Context, req *rag.AddKnowledgeDocumentTextRequest, callOptions ...callopt.Option) (r *rag.AddKnowledgeDocumentTextResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddKnowledgeDocumentText(ctx, req)
}

func (p *kRAGServiceClient) ListKnowledgeDocuments(ctx context.Context, req *rag.ListKnowledgeDocumentsRequest, callOptions ...callopt.Option) (r *rag.ListKnowledgeDocumentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListKnowledgeDocuments(ctx, req)
}

func (p *kRAGServiceClient) ListKnowledgeDocumentChunks(ctx context.Context, req *rag.ListKnowledgeDocumentChunksRequest, callOptions ...callopt.Option) (r *rag.ListKnowledgeDocumentChunksResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListKnowledgeDocumentChunks(ctx, req)
}

func (p *kRAGServiceClient) DeleteKnowledgeDocument(ctx context.Context, req *rag.DeleteKnowledgeDocumentRequest, callOptions ...callopt.Option) (r *rag.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteKnowledgeDocument(ctx, req)
}

func (p *kRAGServiceClient) SearchKnowledgeBase(ctx context.Context, req *rag.SearchKnowledgeBaseRequest, callOptions ...callopt.Option) (r *rag.SearchKnowledgeBaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchKnowledgeBase(ctx, req)
}

func (p *kRAGServiceClient) BindConversationKnowledgeBase(ctx context.Context, req *rag.BindConversationKnowledgeBaseRequest, callOptions ...callopt.Option) (r *rag.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindConversationKnowledgeBase(ctx, req)
}

func (p *kRAGServiceClient) ListConversationKnowledgeBases(ctx context.Context, req *rag.ListConversationKnowledgeBasesRequest, callOptions ...callopt.Option) (r *rag.ListConversationKnowledgeBasesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConversationKnowledgeBases(ctx, req)
}

func (p *kRAGServiceClient) UnbindConversationKnowledgeBase(ctx context.Context, req *rag.UnbindConversationKnowledgeBaseRequest, callOptions ...callopt.Option) (r *rag.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnbindConversationKnowledgeBase(ctx, req)
}
