// Code generated by Kitex v0.16.1. DO NOT EDIT.

package ragservice

import (
	"context"
	"errors"
	rag "example.com/aim/gateway/kitex_gen/rag"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newRAGServiceHealthArgs,
		newRAGServiceHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateKnowledgeBase": kitex.NewMethodInfo(
		createKnowledgeBaseHandler,
		newRAGServiceCreateKnowledgeBaseArgs,
		newRAGServiceCreateKnowledgeBaseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListKnowledgeBases": kitex.NewMethodInfo(
		listKnowledgeBasesHandler,
		newRAGServiceListKnowledgeBasesArgs,
		newRAGServiceListKnowledgeBasesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddKnowledgeDocumentText": kitex.NewMethodInfo(
		addKnowledgeDocumentTextHandler,
		newRAGServiceAddKnowledgeDocumentTextArgs,
		newRAGServiceAddKnowledgeDocumentTextResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListKnowledgeDocuments": kitex.NewMethodInfo(
		listKnowledgeDocumentsHandler,
		newRAGServiceListKnowledgeDocumentsArgs,
		newRAGServiceListKnowledgeDocumentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListKnowledgeDocumentChunks": kitex.NewMethodInfo(
		listKnowledgeDocumentChunksHandler,
		newRAGServiceListKnowledgeDocumentChunksArgs,
		newRAGServiceListKnowledgeDocumentChunksResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteKnowledgeDocument": kitex.NewMethodInfo(
		deleteKnowledgeDocumentHandler,
		newRAGServiceDeleteKnowledgeDocumentArgs,
		newRAGServiceDeleteKnowledgeDocumentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchKnowledgeBase": kitex.NewMethodInfo(
		searchKnowledgeBaseHandler,
		newRAGServiceSearchKnowledgeBaseArgs,
		newRAGServiceSearchKnowledgeBaseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindConversationKnowledgeBase": kitex.NewMethodInfo(
		bindConversationKnowledgeBaseHandler,
		newRAGServiceBindConversationKnowledgeBaseArgs,
		newRAGServiceBindConversationKnowledgeBaseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversationKnowledgeBases": kitex.NewMethodInfo(
		listConversationKnowledgeBasesHandler,
		newRAGServiceListConversationKnowledgeBasesArgs,
		newRAGServiceListConversationKnowledgeBasesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnbindConversationKnowledgeBase": kitex.NewMethodInfo(
		unbindConversationKnowledgeBaseHandler,
		newRAGServiceUnbindConversationKnowledgeBaseArgs,
		newRAGServiceUnbindConversationKnowledgeBaseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	rAGServiceServiceInfo                = NewServiceInfo()
	rAGServiceServiceInfoForClient       = NewServiceInfoForClient()
	rAGServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return rAGServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return rAGServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return rAGServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RAGService"
	handlerType := (*rag.RAGService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "rag",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceHealthArgs)
	realResult := result.(*rag.RAGServiceHealthResult)
	success, err := handler.(rag.RAGService).Health(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceHealthArgs() interface{} {
	return rag.NewRAGServiceHealthArgs()
}

func newRAGServiceHealthResult() interface{} {
	return rag.NewRAGServiceHealthResult()
}

func createKnowledgeBaseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceCreateKnowledgeBaseArgs)
	realResult := result.(*rag.RAGServiceCreateKnowledgeBaseResult)
	success, err := handler.(rag.RAGService).CreateKnowledgeBase(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceCreateKnowledgeBaseArgs() interface{} {
	return rag.NewRAGServiceCreateKnowledgeBaseArgs()
}

func newRAGServiceCreateKnowledgeBaseResult() interface{} {
	return rag.NewRAGServiceCreateKnowledgeBaseResult()
}

func listKnowledgeBasesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceListKnowledgeBasesArgs)
	realResult := result.(*rag.RAGServiceListKnowledgeBasesResult)
	success, err := handler.(rag.RAGService).ListKnowledgeBases(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceListKnowledgeBasesArgs() interface{} {
	return rag.NewRAGServiceListKnowledgeBasesArgs()
}

func newRAGServiceListKnowledgeBasesResult() interface{} {
	return rag.NewRAGServiceListKnowledgeBasesResult()
}

func addKnowledgeDocumentTextHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceAddKnowledgeDocumentTextArgs)
	realResult := result.(*rag.RAGServiceAddKnowledgeDocumentTextResult)
	success, err := handler.(rag.RAGService).AddKnowledgeDocumentText(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceAddKnowledgeDocumentTextArgs() interface{} {
	return rag.NewRAGServiceAddKnowledgeDocumentTextArgs()
}

func newRAGServiceAddKnowledgeDocumentTextResult() interface{} {
	return rag.NewRAGServiceAddKnowledgeDocumentTextResult()
}

func listKnowledgeDocumentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceListKnowledgeDocumentsArgs)
	realResult := result.(*rag.RAGServiceListKnowledgeDocumentsResult)
	success, err := handler.(rag.RAGService).ListKnowledgeDocuments(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceListKnowledgeDocumentsArgs() interface{} {
	return rag.NewRAGServiceListKnowledgeDocumentsArgs()
}

func newRAGServiceListKnowledgeDocumentsResult() interface{} {
	return rag.NewRAGServiceListKnowledgeDocumentsResult()
}

func listKnowledgeDocumentChunksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceListKnowledgeDocumentChunksArgs)
	realResult := result.(*rag.RAGServiceListKnowledgeDocumentChunksResult)
	success, err := handler.(rag.RAGService).ListKnowledgeDocumentChunks(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceListKnowledgeDocumentChunksArgs() interface{} {
	return rag.NewRAGServiceListKnowledgeDocumentChunksArgs()
}

func newRAGServiceListKnowledgeDocumentChunksResult() interface{} {
	return rag.NewRAGServiceListKnowledgeDocumentChunksResult()
}

func deleteKnowledgeDocumentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceDeleteKnowledgeDocumentArgs)
	realResult := result.(*rag.RAGServiceDeleteKnowledgeDocumentResult)
	success, err := handler.(rag.RAGService).DeleteKnowledgeDocument(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceDeleteKnowledgeDocumentArgs() interface{} {
	return rag.NewRAGServiceDeleteKnowledgeDocumentArgs()
}

func newRAGServiceDeleteKnowledgeDocumentResult() interface{} {
	return rag.NewRAGServiceDeleteKnowledgeDocumentResult()
}

func searchKnowledgeBaseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceSearchKnowledgeBaseArgs)
	realResult := result.(*rag.RAGServiceSearchKnowledgeBaseResult)
	success, err := handler.(rag.RAGService).SearchKnowledgeBase(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceSearchKnowledgeBaseArgs() interface{} {
	return rag.NewRAGServiceSearchKnowledgeBaseArgs()
}

func newRAGServiceSearchKnowledgeBaseResult() interface{} {
	return rag.NewRAGServiceSearchKnowledgeBaseResult()
}

func bindConversationKnowledgeBaseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceBindConversationKnowledgeBaseArgs)
	realResult := result.(*rag.RAGServiceBindConversationKnowledgeBaseResult)
	success, err := handler.(rag.RAGService).BindConversationKnowledgeBase(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceBindConversationKnowledgeBaseArgs() interface{} {
	return rag.NewRAGServiceBindConversationKnowledgeBaseArgs()
}

func newRAGServiceBindConversationKnowledgeBaseResult() interface{} {
	return rag.NewRAGServiceBindConversationKnowledgeBaseResult()
}

func listConversationKnowledgeBasesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceListConversationKnowledgeBasesArgs)
	realResult := result.(*rag.RAGServiceListConversationKnowledgeBasesResult)
	success, err := handler.(rag.RAGService).ListConversationKnowledgeBases(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceListConversationKnowledgeBasesArgs() interface{} {
	return rag.NewRAGServiceListConversationKnowledgeBasesArgs()
}

func newRAGServiceListConversationKnowledgeBasesResult() interface{} {
	return rag.NewRAGServiceListConversationKnowledgeBasesResult()
}

func unbindConversationKnowledgeBaseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rag.RAGServiceUnbindConversationKnowledgeBaseArgs)
	realResult := result.(*rag.RAGServiceUnbindConversationKnowledgeBaseResult)
	success, err := handler.(rag.RAGService).UnbindConversationKnowledgeBase(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRAGServiceUnbindConversationKnowledgeBaseArgs() interface{} {
	return rag.NewRAGServiceUnbindConversationKnowledgeBaseArgs()
}

func newRAGServiceUnbindConversationKnowledgeBaseResult() interface{} {
	return rag.NewRAGServiceUnbindConversationKnowledgeBaseResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Health(ctx context.Context, req *rag.HealthRequest) (r *rag.HealthResponse, err error) {
	var _args rag.RAGServiceHealthArgs
	_args.Req = req
	var _result rag.RAGServiceHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateKnowledgeBase(ctx context.Context, req *rag.CreateKnowledgeBaseRequest) (r *rag.CreateKnowledgeBaseResponse, err error) {
	var _args rag.RAGServiceCreateKnowledgeBaseArgs
	_args.Req = req
	var _result rag.RAGServiceCreateKnowledgeBaseResult
	if err = p.c.Call(ctx, "CreateKnowledgeBase", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListKnowledgeBases(ctx context.Context, req *rag.ListKnowledgeBasesRequest) (r *rag.ListKnowledgeBasesResponse, err error) {
	var _args rag.RAGServiceListKnowledgeBasesArgs
	_args.Req = req
	var _result rag.RAGServiceListKnowledgeBasesResult
	if err = p.c.Call(ctx, "ListKnowledgeBases", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddKnowledgeDocumentText(ctx context.Context, req *rag.AddKnowledgeDocumentTextRequest) (r *rag.AddKnowledgeDocumentTextResponse, err error) {
	var _args rag.RAGServiceAddKnowledgeDocumentTextArgs
	_args.Req = req
	var _result rag.RAGServiceAddKnowledgeDocumentTextResult
	if err = p.c.Call(ctx, "AddKnowledgeDocumentText", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListKnowledgeDocuments(ctx context.Context, req *rag.ListKnowledgeDocumentsRequest) (r *rag.ListKnowledgeDocumentsResponse, err error) {
	var _args rag.RAGServiceListKnowledgeDocumentsArgs
	_args.Req = req
	var _result rag.RAGServiceListKnowledgeDocumentsResult
	if err = p.c.Call(ctx, "ListKnowledgeDocuments", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListKnowledgeDocumentChunks(ctx context.Context, req *rag.ListKnowledgeDocumentChunksRequest) (r *rag.ListKnowledgeDocumentChunksResponse, err error) {
	var _args rag.RAGServiceListKnowledgeDocumentChunksArgs
	_args.Req = req
	var _result rag.RAGServiceListKnowledgeDocumentChunksResult
	if err = p.c.Call(ctx, "ListKnowledgeDocumentChunks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteKnowledgeDocument(ctx context.Context, req *rag.DeleteKnowledgeDocumentRequest) (r *rag.CommonResponse, err error) {
	var _args rag.RAGServiceDeleteKnowledgeDocumentArgs
	_args.Req = req
	var _result rag.RAGServiceDeleteKnowledgeDocumentResult
	if err = p.c.Call(ctx, "DeleteKnowledgeDocument", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchKnowledgeBase(ctx context.Context, req *rag.SearchKnowledgeBaseRequest) (r *rag.SearchKnowledgeBaseResponse, err error) {
	var _args rag.RAGServiceSearchKnowledgeBaseArgs
	_args.Req = req
	var _result rag.RAGServiceSearchKnowledgeBaseResult
	if err = p.c.Call(ctx, "SearchKnowledgeBase", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindConversationKnowledgeBase(ctx context.Context, req *rag.BindConversationKnowledgeBaseRequest) (r *rag.CommonResponse, err error) {
	var _args rag.RAGServiceBindConversationKnowledgeBaseArgs
	_args.Req = req
	var _result rag.RAGServiceBindConversationKnowledgeBaseResult
	if err = p.c.Call(ctx, "BindConversationKnowledgeBase", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversationKnowledgeBases(ctx context.Context, req *rag.ListConversationKnowledgeBasesRequest) (r *rag.ListConversationKnowledgeBasesResponse, err error) {
	var _args rag.RAGServiceListConversationKnowledgeBasesArgs
	_args.Req = req
	var _result rag.RAGServiceListConversationKnowledgeBasesResult
	if err = p.c.Call(ctx, "ListConversationKnowledgeBases", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnbindConversationKnowledgeBase(ctx context.Context, req *rag.UnbindConversationKnowledgeBaseRequest) (r *rag.CommonResponse, err error) {
	var _args rag.RAGServiceUnbindConversationKnowledgeBaseArgs
	_args.Req = req
	var _result rag.RAGServiceUnbindConversationKnowledgeBaseResult
	if err = p.c.Call(ctx, "UnbindConversationKnowledgeBase", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
